const searchList = [
  {
    label: '类型(收/支)',
    labelI18nCode: '',
    prop: 'F_Type',
    jnpfKey: 'radio',
    searchType: 1,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_Type',
    fullName: '类型(收/支)',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'radio',
      label: '类型(收/支)',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfRadio',
      tagIcon: 'icon-ym icon-ym-generator-radio',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_ctc_finance',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'static',
      dictionaryType: '',
      propsUrl: '',
      propsName: '',
      useCache: true,
      templateJson: [],
      formId: 'formItemf7381c',
      renderKey: 1768267347631,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [
      {
        fullName: '收入',
        id: '收入',
      },
      {
        fullName: '支出',
        id: '支出',
      },
    ],
    props: {
      label: 'fullName',
      value: 'id',
    },
    direction: 'horizontal',
    optionType: 'default',
    buttonStyle: 'solid',
    size: 'default',
    disabled: false,
    __vModel__: 'F_Type',
  },
  {
    label: '金额',
    labelI18nCode: '',
    prop: 'F_Money',
    jnpfKey: 'inputNumber',
    value: [],
    searchType: 3,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_Money',
    fullName: '金额',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'inputNumber',
      label: '金额',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInputNumber',
      tagIcon: 'icon-ym icon-ym-generator-number',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_ctc_finance',
      noShow: false,
      regList: [],
      trigger: ['blur', 'change'],
      formId: 'formItemb3d4e4',
      renderKey: 1768267402747,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    controls: false,
    addonBefore: '',
    addonAfter: '',
    thousands: false,
    isAmountChinese: false,
    step: 1,
    disabled: false,
    __vModel__: 'F_Money',
  },

  {
    label: '创建时间',
    labelI18nCode: '',
    prop: 'F_CreatorTime',
    jnpfKey: 'createTime',
    searchType: 3,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_CreatorTime',
    fullName: '创建时间',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'createTime',
      label: '创建时间',
      showLabel: true,
      tag: 'JnpfOpenData',
      tagIcon: 'icon-ym icon-ym-generator-createtime',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      layout: 'colFormItem',
      required: false,
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_ctc_finance',
      noShow: false,
      formId: 'formItem0fc974',
      renderKey: 1768267445345,
    },
    style: {
      width: '100%',
    },
    type: 'currTime',
    readonly: true,
    placeholder: '',
    __vModel__: 'F_CreatorTime',
  },
];
export default searchList;
