const columnList = [
  {
    label: '排单序号',
    labelI18nCode: '',
    prop: 'F_SequenceNo',
    fixed: 'none',
    align: 'center',
    jnpfKey: 'inputNumber',
    sortable: false,
    width: null,
    resizable: true,
    id: 'F_SequenceNo',
    fullName: '排单序号',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'inputNumber',
      label: '排单序号',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInputNumber',
      tagIcon: 'icon-ym icon-ym-generator-number',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: true,
      regList: [],
      trigger: ['blur', 'change'],
      formId: 'formItemacde3d',
      renderKey: 1768976059551,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    min: 1,
    controls: false,
    addonBefore: '',
    addonAfter: '',
    thousands: false,
    isAmountChinese: false,
    step: 1,
    precision: 0,
    disabled: false,
    __vModel__: 'F_SequenceNo',
  },
  {
    label: '加工单号',
    labelI18nCode: '',
    prop: 'F_ProcessNo',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'input',
    sortable: false,
    width: 150,
    resizable: true,
    id: 'F_ProcessNo',
    fullName: '加工单号',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '加工单号',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItem58c1b4',
      renderKey: 1768965791541,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请填写，忽略将自动生成',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_ProcessNo',
  },
  {
    label: '商品',
    labelI18nCode: '',
    prop: 'F_GoodsId',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'popupSelect',
    sortable: false,
    width: 210,
    resizable: true,
    id: 'F_GoodsId',
    fullName: '商品',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'popupSelect',
      label: '商品',
      tipLabel: '',
      showLabel: true,
      required: true,
      tag: 'JnpfPopupSelect',
      tagIcon: 'icon-ym icon-ym-generator-popup',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: false,
      regList: [],
      trigger: 'change',
      transferList: [],
      useCache: true,
      formId: 'formItem1c701c',
      renderKey: 1768965800513,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    interfaceId: '2012085692393459712',
    interfaceName: '弹窗获取商品列表（可传合同ID）',
    templateJson: [
      {
        id: 'b6217b',
        field: 'contractId',
        dataType: 'varchar',
        defaultValue: '',
        required: 0,
        fieldName: '合同ID',
        relationField: '',
        sourceType: 3,
      },
    ],
    hasPage: true,
    pageSize: 20,
    extraOptions: [],
    columnOptions: [
      {
        value: 'F_GoodsName',
        label: '商品名',
      },
      {
        value: 'F_GoodsNo',
        label: '商品编号',
      },
      {
        value: 'F_Specification',
        label: '商品规格',
      },
      {
        value: 'F_CategoryId',
        label: '商品类别',
      },
      {
        value: 'F_Unit',
        label: '单位',
      },
      {
        value: 'F_InspectRule',
        label: '检验规范',
      },
      {
        value: 'F_Remark',
        label: '备注',
      },
    ],
    propsValue: 'id',
    relationField: 'F_GoodsName',
    popupType: 'dialog',
    popupTitle: '选择数据',
    popupWidth: '1000px',
    disabled: false,
    clearable: true,
    __vModel__: 'F_GoodsId',
    interfaceHasPage: 0,
  },
  {
    label: '计划数',
    labelI18nCode: '',
    prop: 'F_PlanQty',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'inputNumber',
    sortable: false,
    width: null,
    resizable: true,
    id: 'F_PlanQty',
    fullName: '计划数',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'inputNumber',
      label: '计划数',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInputNumber',
      tagIcon: 'icon-ym icon-ym-generator-number',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: true,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: false,
      regList: [],
      trigger: ['blur', 'change'],
      formId: 'formItem0684e1',
      renderKey: 1768965820882,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    min: 1,
    controls: false,
    addonBefore: '',
    addonAfter: '',
    thousands: false,
    isAmountChinese: false,
    step: 1,
    precision: 0,
    disabled: false,
    __vModel__: 'F_PlanQty',
  },
  {
    label: '状态',
    labelI18nCode: '',
    prop: 'F_State',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'select',
    sortable: false,
    width: null,
    resizable: true,
    id: 'F_State',
    fullName: '状态',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '状态',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: true,
      regList: [],
      trigger: 'change',
      dataType: 'dictionary',
      dictionaryType: '2013819135649255424',
      propsUrl: '',
      propsName: '',
      useCache: true,
      templateJson: [],
      formId: 'formItem19f927',
      renderKey: 1768967117997,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [],
    props: {
      label: 'fullName',
      value: 'enCode',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_State',
  },
  {
    label: '交货日期',
    labelI18nCode: '',
    prop: 'F_DeliveryDate',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'datePicker',
    sortable: false,
    width: null,
    resizable: true,
    id: 'F_DeliveryDate',
    fullName: '交货日期',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'datePicker',
      label: '交货日期',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfDatePicker',
      tagIcon: 'icon-ym icon-ym-generator-date',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      defaultCurrent: false,
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: false,
      regList: [],
      trigger: 'change',
      startTimeRule: false,
      startTimeType: 1,
      startTimeTarget: 1,
      startTimeValue: null,
      startRelationField: '',
      endTimeRule: false,
      endTimeType: 1,
      endTimeTarget: 1,
      endTimeValue: null,
      endRelationField: '',
      formId: 'formItem36fe16',
      renderKey: 1768965822279,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    format: 'yyyy-MM-dd',
    startTime: null,
    endTime: null,
    disabled: false,
    clearable: true,
    __vModel__: 'F_DeliveryDate',
  },
  {
    label: '优先级',
    labelI18nCode: '',
    prop: 'F_Priority',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'select',
    sortable: false,
    width: null,
    resizable: true,
    id: 'F_Priority',
    fullName: '优先级',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '优先级',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dictionary',
      dictionaryType: '2013182853290004480',
      propsUrl: '',
      propsName: '',
      useCache: true,
      templateJson: [],
      formId: 'formItem3492d8',
      renderKey: 1768965825289,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [],
    props: {
      label: 'fullName',
      value: 'enCode',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: false,
    multiple: false,
    __vModel__: 'F_Priority',
  },
  {
    label: '来源',
    labelI18nCode: '',
    prop: 'F_Source',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'select',
    sortable: false,
    width: null,
    resizable: true,
    id: 'F_Source',
    fullName: '来源',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '来源',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: true,
      regList: [],
      trigger: 'change',
      dataType: 'dictionary',
      dictionaryType: '2013819135649255424',
      propsUrl: '',
      propsName: '',
      useCache: true,
      templateJson: [],
      formId: 'formItem19f927',
      renderKey: 1768967117997,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [],
    props: {
      label: 'fullName',
      value: 'enCode',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_Source',
  },
  {
    label: '计划开始',
    labelI18nCode: '',
    prop: 'F_PlanStartDate',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'datePicker',
    sortable: false,
    width: null,
    resizable: true,
    id: 'F_PlanStartDate',
    fullName: '计划开始',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'datePicker',
      label: '计划开始',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfDatePicker',
      tagIcon: 'icon-ym icon-ym-generator-date',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      defaultCurrent: false,
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: false,
      regList: [],
      trigger: 'change',
      startTimeRule: false,
      startTimeType: 1,
      startTimeTarget: 1,
      startTimeValue: null,
      startRelationField: '',
      endTimeRule: false,
      endTimeType: 1,
      endTimeTarget: 1,
      endTimeValue: null,
      endRelationField: '',
      formId: 'formItem390b0f',
      renderKey: 1768965828597,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    format: 'yyyy-MM-dd',
    startTime: null,
    endTime: null,
    disabled: false,
    clearable: true,
    __vModel__: 'F_PlanStartDate',
  },
  {
    label: '计划结束',
    labelI18nCode: '',
    prop: 'F_PlanEndDate',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'datePicker',
    sortable: false,
    width: null,
    resizable: true,
    id: 'F_PlanEndDate',
    fullName: '计划结束',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'datePicker',
      label: '计划结束',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfDatePicker',
      tagIcon: 'icon-ym icon-ym-generator-date',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      defaultCurrent: false,
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: false,
      regList: [],
      trigger: 'change',
      startTimeRule: false,
      startTimeType: 1,
      startTimeTarget: 1,
      startTimeValue: null,
      startRelationField: '',
      endTimeRule: false,
      endTimeType: 1,
      endTimeTarget: 1,
      endTimeValue: null,
      endRelationField: '',
      formId: 'formItem6b9034',
      renderKey: 1768965828821,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    format: 'yyyy-MM-dd',
    startTime: null,
    endTime: null,
    disabled: false,
    clearable: true,
    __vModel__: 'F_PlanEndDate',
  },
  {
    label: '图纸',
    labelI18nCode: '',
    prop: 'F_DrawingFile',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'uploadFile',
    sortable: false,
    width: 150,
    resizable: true,
    id: 'F_DrawingFile',
    fullName: '图纸',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'uploadFile',
      label: '图纸',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfUploadFile',
      tagIcon: 'icon-ym icon-ym-generator-upload',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: [],
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: false,
      regList: [],
      trigger: 'change',
      formId: 'formItembeedf8',
      renderKey: 1768965834509,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    disabled: false,
    accept: '',
    fileSize: 10,
    sizeUnit: 'MB',
    buttonText: '点击上传',
    limit: 9,
    pathType: 'selfPath',
    sortRule: ['1', '2'],
    timeFormat: 'YYYYMMDD',
    folder: '',
    tipText: '',
    __vModel__: 'F_DrawingFile',
  },
  {
    label: '合同',
    labelI18nCode: '',
    prop: 'F_ContractId',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'input',
    sortable: false,
    width: 210,
    resizable: true,
    id: 'F_ContractId',
    fullName: '合同',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '合同',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: true,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItem77740c',
      renderKey: 1768965847106,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_ContractId',
  },
  {
    label: '客户',
    labelI18nCode: '',
    prop: 'F_CustomerName',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'input',
    sortable: false,
    width: 210,
    resizable: true,
    id: 'F_CustomerName',
    fullName: '客户',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '客户',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: true,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItem77740c',
      renderKey: 1768965847106,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_CustomerName',
  },
  {
    label: '锁具',
    labelI18nCode: '',
    prop: 'F_LockSet',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'input',
    sortable: false,
    width: null,
    resizable: true,
    id: 'F_LockSet',
    fullName: '锁具',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '锁具',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: true,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItem93964c',
      renderKey: 1768965851588,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_LockSet',
  },
  {
    label: '铰链',
    labelI18nCode: '',
    prop: 'F_Hinge',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'input',
    sortable: false,
    width: null,
    resizable: true,
    id: 'F_Hinge',
    fullName: '铰链',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '铰链',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: true,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItemc5f75a',
      renderKey: 1768965851885,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_Hinge',
  },
  {
    label: '颜色',
    labelI18nCode: '',
    prop: 'F_Color',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'input',
    sortable: false,
    width: null,
    resizable: true,
    id: 'F_Color',
    fullName: '颜色',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '颜色',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: true,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItem29a867',
      renderKey: 1768965852254,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_Color',
  },
  {
    label: '类别',
    labelI18nCode: '',
    prop: 'F_Type',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'cascader',
    sortable: false,
    width: 150,
    resizable: true,
    id: 'F_Type',
    fullName: '类别',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'cascader',
      label: '类别',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfCascader',
      tagIcon: 'icon-ym icon-ym-generator-cascader',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: [],
      required: true,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dynamic',
      propsUrl: '2008414575283802112',
      propsName: '设备管理类别',
      useCache: true,
      templateJson: [],
      dictionaryType: '',
      formId: 'formIteme77d77',
      renderKey: 1768965854736,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [],
    props: {
      value: 'id',
      label: 'F_Name',
      children: 'children',
    },
    placeholder: '请选择',
    disabled: false,
    clearable: true,
    filterable: true,
    multiple: false,
    __vModel__: 'F_Type',
  },
  {
    label: 'BOM图片',
    labelI18nCode: '',
    prop: 'F_BOMImages',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'uploadImg',
    sortable: false,
    width: 150,
    resizable: true,
    id: 'F_BOMImages',
    fullName: 'BOM图片',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'uploadImg',
      label: 'BOM图片',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfUploadImg',
      tagIcon: 'icon-ym icon-ym-generator-upload',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: [],
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: false,
      regList: [],
      trigger: 'change',
      formId: 'formItem4feab6',
      renderKey: 1768965859851,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    disabled: false,
    fileSize: 10,
    sizeUnit: 'MB',
    buttonText: '点击上传',
    limit: 9,
    pathType: 'selfPath',
    sortRule: ['1', '2'],
    timeFormat: 'YYYYMMDD',
    folder: '',
    tipText: '',
    showType: 'button',
    __vModel__: 'F_BOMImages',
  },
  {
    label: '备注',
    labelI18nCode: '',
    prop: 'F_Description',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'textarea',
    sortable: false,
    width: 280,
    resizable: true,
    id: 'F_Description',
    fullName: '备注',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'textarea',
      label: '备注',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfTextarea',
      tagIcon: 'icon-ym icon-ym-generator-textarea',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItem5c9c3f',
      renderKey: 1768965855486,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    autoSize: {
      minRows: 2,
      maxRows: 2,
    },
    clearable: true,
    maxlength: 500,
    showCount: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_Description',
  },
  {
    label: '创建时间',
    labelI18nCode: '',
    prop: 'F_CreatorTime',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'createTime',
    sortable: false,
    width: 150,
    resizable: true,
    id: 'F_CreatorTime',
    fullName: '创建时间',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'createTime',
      label: '创建时间',
      showLabel: true,
      tag: 'JnpfOpenData',
      tagIcon: 'icon-ym icon-ym-generator-createtime',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      layout: 'colFormItem',
      required: false,
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: false,
      formId: 'formItem3930be',
      renderKey: 1768965863740,
    },
    style: {
      width: '100%',
    },
    type: 'currTime',
    readonly: true,
    placeholder: '',
    __vModel__: 'F_CreatorTime',
  },
];
export default columnList;
