const searchList = [
  {
    label: '加工单号',
    labelI18nCode: '',
    prop: 'F_ProcessNo',
    jnpfKey: 'input',
    searchType: 2,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_ProcessNo',
    fullName: '加工单号',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '加工单号',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItem58c1b4',
      renderKey: 1768965791541,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请填写，忽略将自动生成',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_ProcessNo',
  },
  {
    label: '商品',
    labelI18nCode: '',
    prop: 'F_GoodstId',
    jnpfKey: 'select',
    searchType: 1,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_GoodstId',
    fullName: '商品',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '商品',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: true,
      regList: [],
      trigger: 'change',
      dataType: 'dynamic',
      dictionaryType: '',
      propsUrl: '2012085692393459712',
      propsName: '弹窗获取商品列表（可传合同ID）',
      useCache: true,
      templateJson: [
        {
          id: 'b6217b',
          field: 'contractId',
          dataType: 'varchar',
          defaultValue: '',
          required: 0,
          fieldName: '合同ID',
          relationField: '',
          sourceType: 3,
        },
      ],
      formId: 'formItem8b6951',
      renderKey: 1768966957741,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [
      {
        id: '2011713069100699648',
        F_GoodsNo: 'SP20260115160001',
        F_GoodsName: 'CS2-SP20260115160001',
        F_CategoryId: '超市',
        F_Unit: '个',
        F_SalePrice: null,
        F_CostPrice: null,
        F_CommissionFixed: null,
        F_Source: null,
        F_OutsourcePrice: null,
        F_SupplierId: null,
        F_Specification: null,
        F_InspectRule: null,
        F_StockUpperLimit: null,
        F_StockLowerLimit: null,
        F_Image: null,
        F_AttachmentUrl: null,
        F_CreatorTime: '2026-01-15T16:12:26Z',
        F_CreatorUserId: null,
        F_Remark: null,
      },
      {
        id: '2011713010275586048',
        F_GoodsNo: 'sp20260115160001',
        F_GoodsName: 'CS1-sp20260115160001',
        F_CategoryId: null,
        F_Unit: '台',
        F_SalePrice: null,
        F_CostPrice: null,
        F_CommissionFixed: null,
        F_Source: null,
        F_OutsourcePrice: null,
        F_SupplierId: null,
        F_Specification: null,
        F_InspectRule: null,
        F_StockUpperLimit: null,
        F_StockLowerLimit: null,
        F_Image: null,
        F_AttachmentUrl: null,
        F_CreatorTime: '2026-01-15T16:12:12Z',
        F_CreatorUserId: null,
        F_Remark: null,
      },
      {
        id: '2010976325753507840',
        F_GoodsNo: 'SP20260115160003',
        F_GoodsName: '苹果-SP20260115160003',
        F_CategoryId: '超市',
        F_Unit: '个',
        F_SalePrice: null,
        F_CostPrice: null,
        F_CommissionFixed: null,
        F_Source: null,
        F_OutsourcePrice: null,
        F_SupplierId: null,
        F_Specification: '1*1',
        F_InspectRule: '无',
        F_StockUpperLimit: null,
        F_StockLowerLimit: null,
        F_Image: null,
        F_AttachmentUrl: null,
        F_CreatorTime: '2026-01-13T07:24:53Z',
        F_CreatorUserId: null,
        F_Remark: '测试备注',
      },
      {
        id: '2008839754363310080',
        F_GoodsNo: 'sp20260107170001',
        F_GoodsName: '木材-sp20260107170001',
        F_CategoryId: null,
        F_Unit: '台',
        F_SalePrice: null,
        F_CostPrice: null,
        F_CommissionFixed: null,
        F_Source: null,
        F_OutsourcePrice: null,
        F_SupplierId: null,
        F_Specification: null,
        F_InspectRule: null,
        F_StockUpperLimit: null,
        F_StockLowerLimit: null,
        F_Image: null,
        F_AttachmentUrl: null,
        F_CreatorTime: '2026-01-07T17:54:54Z',
        F_CreatorUserId: null,
        F_Remark: null,
      },
    ],
    props: {
      label: 'F_GoodsName',
      value: 'id',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: false,
    multiple: false,
    __vModel__: 'F_GoodstId',
  },
  {
    label: '合同',
    labelI18nCode: '',
    prop: 'F_ContractId',
    jnpfKey: 'select',
    searchType: 1,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_ContractId',
    fullName: '合同',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '合同',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: true,
      regList: [],
      trigger: 'change',
      dataType: 'dynamic',
      dictionaryType: '',
      propsUrl: '2010889611072638976',
      propsName: '合同',
      useCache: true,
      templateJson: [],
      formId: 'formItem8b6951',
      renderKey: 1768966957741,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [
      {
        F_Id: '2041854330214158336',
        F_ContractCode: 'HT20260408001',
        F_PrepayAmount: null,
        F_SaleTotal: 8,
        F_ContractAmount: 1900,
        F_IsTaxable: '0',
        F_AuditStatus: null,
        F_Description: null,
        F_CreatorTime: '2026-04-08T20:23:02Z',
        F_CustomerId: '2027656090354847744',
      },
    ],
    props: {
      label: 'F_ContractCode',
      value: 'F_Id',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: false,
    multiple: false,
    __vModel__: 'F_ContractId',
  },
  {
    label: '项目',
    labelI18nCode: '',
    prop: 'F_ProjectId',
    jnpfKey: 'select',
    searchType: 1,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_ProjectId',
    fullName: '项目',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '项目',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: true,
      regList: [],
      trigger: 'change',
      dataType: 'dynamic',
      dictionaryType: '',
      propsUrl: '2013822233163730944',
      propsName: '弹窗获取项目列表',
      useCache: true,
      templateJson: [],
      formId: 'formItemf336aa',
      renderKey: 1768967758694,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [
      {
        id: '2042863311355252736',
        F_ProjectNo: '20260411001',
        F_ProjectName: '测试项目1',
        F_ContractId: '2042542761554612224',
        F_ProjectType: '合同项目',
        F_ProjectTypeCode: null,
        F_Status: null,
        F_ProjectProgress: null,
        F_WorkOrderQty: null,
        F_CompletedQtyStatus: null,
        F_PlanQty: null,
        F_CreatorUserId: null,
        F_CreatorTime: '2026-04-11T15:12:22Z',
        F_CreatorOrganizeId: null,
        F_UpdateUserId: null,
        F_UpdateTime: null,
      },
    ],
    props: {
      label: 'F_ProjectName',
      value: 'id',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_ProjectId',
  },
  // {
  //   label: '生产计划',
  //   labelI18nCode: '',
  //   prop: 'F_ProdPlanId',
  //   jnpfKey: 'select',
  //   searchType: 1,
  //   searchMultiple: false,
  //   isKeyword: false,
  //   id: 'F_ProdPlanId',
  //   fullName: '生产计划',
  //   fullNameI18nCode: [''],
  //   __config__: {
  //     jnpfKey: 'select',
  //     label: '生产计划',
  //     tipLabel: '',
  //     showLabel: true,
  //     tag: 'JnpfSelect',
  //     tagIcon: 'icon-ym icon-ym-generator-select',
  //     tableAlign: 'left',
  //     tableFixed: 'none',
  //     className: [],
  //     defaultValue: '',
  //     required: false,
  //     layout: 'colFormItem',
  //     span: 12,
  //     dragDisabled: false,
  //     visibility: ['pc', 'app'],
  //     tableName: 'a_prod_processing',
  //     noShow: true,
  //     regList: [],
  //     trigger: 'change',
  //     dataType: 'dynamic',
  //     dictionaryType: '',
  //     propsUrl: '2013822515994038272',
  //     propsName: '弹窗获取生产计划列表',
  //     useCache: true,
  //     templateJson: [],
  //     formId: 'formItem71ee12',
  //     renderKey: 1768967756912,
  //   },
  //   on: {
  //     change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
  //   },
  //   style: {
  //     width: '100%',
  //   },
  //   options: [
  //     {
  //       id: '2013800049699590144',
  //       F_PlanNo: 'JH2026012110001',
  //       F_PlanName: '测试生产计划',
  //       F_DeliveryDate: '2026-01-22',
  //       F_State: '未分析',
  //       F_CreatorUserId: null,
  //       F_CreatorTime: '2026-01-21T10:25:21Z',
  //     },
  //   ],
  //   props: {
  //     label: 'F_PlanName',
  //     value: 'id',
  //   },
  //   placeholder: '请选择',
  //   clearable: true,
  //   disabled: false,
  //   filterable: true,
  //   multiple: false,
  //   __vModel__: 'F_ProdPlanId',
  // },
  {
    label: '优先级',
    labelI18nCode: '',
    prop: 'F_Priority',
    jnpfKey: 'select',
    searchType: 1,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_Priority',
    fullName: '优先级',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '优先级',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dictionary',
      dictionaryType: '2013182853290004480',
      propsUrl: '',
      propsName: '',
      useCache: true,
      templateJson: [],
      formId: 'formItem3492d8',
      renderKey: 1768965825289,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [
      {
        id: '2013182929399844864',
        fullName: '加急',
        enCode: '0',
        sortCode: 0,
      },
      {
        id: '2013182949784162304',
        fullName: '正常',
        enCode: '1',
        sortCode: 1,
      },
      {
        id: '2013182977315573760',
        fullName: '延期',
        enCode: '2',
        sortCode: 2,
      },
    ],
    props: {
      label: 'fullName',
      value: 'enCode',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: false,
    multiple: false,
    __vModel__: 'F_Priority',
  },
  {
    label: '计划数',
    labelI18nCode: '',
    prop: 'F_PlanQty',
    jnpfKey: 'inputNumber',
    value: [],
    searchType: 3,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_PlanQty',
    fullName: '计划数',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'inputNumber',
      label: '计划数',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInputNumber',
      tagIcon: 'icon-ym icon-ym-generator-number',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: true,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: false,
      regList: [],
      trigger: ['blur', 'change'],
      formId: 'formItem0684e1',
      renderKey: 1768965820882,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    min: 1,
    controls: false,
    addonBefore: '',
    addonAfter: '',
    thousands: false,
    isAmountChinese: false,
    step: 1,
    precision: 0,
    disabled: false,
    __vModel__: 'F_PlanQty',
  },
  {
    label: '计划开始',
    labelI18nCode: '',
    prop: 'F_PlanStartDate',
    jnpfKey: 'datePicker',
    value: [],
    searchType: 3,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_PlanStartDate',
    fullName: '计划开始',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'datePicker',
      label: '计划开始',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfDatePicker',
      tagIcon: 'icon-ym icon-ym-generator-date',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      defaultCurrent: false,
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: false,
      regList: [],
      trigger: 'change',
      startTimeRule: false,
      startTimeType: 1,
      startTimeTarget: 1,
      startTimeValue: null,
      startRelationField: '',
      endTimeRule: false,
      endTimeType: 1,
      endTimeTarget: 1,
      endTimeValue: null,
      endRelationField: '',
      formId: 'formItem390b0f',
      renderKey: 1768965828597,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    format: 'yyyy-MM-dd',
    startTime: null,
    endTime: null,
    disabled: false,
    clearable: true,
    __vModel__: 'F_PlanStartDate',
  },
  {
    label: '计划结束',
    labelI18nCode: '',
    prop: 'F_PlanEndDate',
    jnpfKey: 'datePicker',
    value: [],
    searchType: 3,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_PlanEndDate',
    fullName: '计划结束',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'datePicker',
      label: '计划结束',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfDatePicker',
      tagIcon: 'icon-ym icon-ym-generator-date',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      defaultCurrent: false,
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: false,
      regList: [],
      trigger: 'change',
      startTimeRule: false,
      startTimeType: 1,
      startTimeTarget: 1,
      startTimeValue: null,
      startRelationField: '',
      endTimeRule: false,
      endTimeType: 1,
      endTimeTarget: 1,
      endTimeValue: null,
      endRelationField: '',
      formId: 'formItem6b9034',
      renderKey: 1768965828821,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    format: 'yyyy-MM-dd',
    startTime: null,
    endTime: null,
    disabled: false,
    clearable: true,
    __vModel__: 'F_PlanEndDate',
  },
  {
    label: '交货日期',
    labelI18nCode: '',
    prop: 'F_DeliveryDate',
    jnpfKey: 'datePicker',
    value: [],
    searchType: 3,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_DeliveryDate',
    fullName: '交货日期',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'datePicker',
      label: '交货日期',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfDatePicker',
      tagIcon: 'icon-ym icon-ym-generator-date',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      defaultCurrent: false,
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: false,
      regList: [],
      trigger: 'change',
      startTimeRule: false,
      startTimeType: 1,
      startTimeTarget: 1,
      startTimeValue: null,
      startRelationField: '',
      endTimeRule: false,
      endTimeType: 1,
      endTimeTarget: 1,
      endTimeValue: null,
      endRelationField: '',
      formId: 'formItem36fe16',
      renderKey: 1768965822279,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    format: 'yyyy-MM-dd',
    startTime: null,
    endTime: null,
    disabled: false,
    clearable: true,
    __vModel__: 'F_DeliveryDate',
  },
  {
    label: '状态',
    labelI18nCode: '',
    prop: 'F_State',
    jnpfKey: 'select',
    searchType: 1,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_State',
    fullName: '状态',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '状态',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: true,
      regList: [],
      trigger: 'change',
      dataType: 'dictionary',
      dictionaryType: '2013819135649255424',
      propsUrl: '',
      propsName: '',
      useCache: true,
      templateJson: [],
      formId: 'formItem19f927',
      renderKey: 1768967117997,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [
      {
        id: '2013819262619226112',
        fullName: '未开始',
        enCode: '0',
        sortCode: 0,
      },
      {
        id: '2013819307468918784',
        fullName: '生产中',
        enCode: '1',
        sortCode: 1,
      },
      {
        id: '2013819331418394624',
        fullName: '已完成',
        enCode: '2',
        sortCode: 2,
      },
      {
        id: '2013819399760384000',
        fullName: '已暂停',
        enCode: '3',
        sortCode: 3,
      },
      {
        id: '2013819371796959232',
        fullName: '已取消',
        enCode: '4',
        sortCode: 4,
      },
    ],
    props: {
      label: 'fullName',
      value: 'enCode',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_State',
  },
  {
    label: '创建时间',
    labelI18nCode: '',
    prop: 'F_CreatorTime',
    jnpfKey: 'createTime',
    searchType: 3,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_CreatorTime',
    fullName: '创建时间',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'createTime',
      label: '创建时间',
      showLabel: true,
      tag: 'JnpfOpenData',
      tagIcon: 'icon-ym icon-ym-generator-createtime',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      layout: 'colFormItem',
      required: false,
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: false,
      formId: 'formItem3930be',
      renderKey: 1768965863740,
    },
    style: {
      width: '100%',
    },
    type: 'currTime',
    readonly: true,
    placeholder: '',
    __vModel__: 'F_CreatorTime',
  },
  {
    label: '备注',
    labelI18nCode: '',
    prop: 'F_Description',
    jnpfKey: 'textarea',
    searchType: 2,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_Description',
    fullName: '备注',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'textarea',
      label: '备注',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfTextarea',
      tagIcon: 'icon-ym icon-ym-generator-textarea',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItem5c9c3f',
      renderKey: 1768965855486,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    autoSize: {
      minRows: 2,
      maxRows: 2,
    },
    clearable: true,
    maxlength: 500,
    showCount: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_Description',
  },
  {
    label: '客户',
    labelI18nCode: '',
    prop: 'F_CustomerName',
    jnpfKey: 'select',
    searchType: 1,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_CustomerName',
    fullName: '客户',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '客户',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: true,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dynamic',
      dictionaryType: '',
      propsUrl: '2009458830353764352',
      propsName: '客户',
      useCache: true,
      templateJson: [],
      formId: 'formItem4a8f7a',
      renderKey: 1775650288350,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [
      {
        F_Id: '2027656220634124288',
        F_CustomerName: '绵阳丰瑞德技术有限公司',
        F_CustomerCode: 'KH000013',
      },
      {
        F_Id: '2027656090354847744',
        F_CustomerName: '绵阳四聚恒机械制造有限公司',
        F_CustomerCode: 'KH000012',
      },
      {
        F_Id: '2027655966534799360',
        F_CustomerName: '四川中科恒通科技有限公司',
        F_CustomerCode: 'KH000011',
      },
      {
        F_Id: '2027655806144614400',
        F_CustomerName: '绵阳卡力特科技有限公司',
        F_CustomerCode: 'KH000010',
      },
      {
        F_Id: '2027655656160497664',
        F_CustomerName: '四川遄颉科技有限公司',
        F_CustomerCode: 'KH000009',
      },
      {
        F_Id: '2027655225116069888',
        F_CustomerName: '四川劢科制造科技',
        F_CustomerCode: 'KH000008',
      },
      {
        F_Id: '2027655078755831808',
        F_CustomerName: '四川凯拓电器有限公司',
        F_CustomerCode: 'KH000007',
      },
      {
        F_Id: '2027645053006123008',
        F_CustomerName: '绵阳市巢匠技术有限公司',
        F_CustomerCode: 'KH000006',
      },
      {
        F_Id: '2027644818141876224',
        F_CustomerName: '绵阳德玛斯科技有限公司',
        F_CustomerCode: 'KH000005',
      },
      {
        F_Id: '2027644515703197696',
        F_CustomerName: '四川和心亿科技有限公司',
        F_CustomerCode: 'KH000004',
      },
      {
        F_Id: '2027624013123162112',
        F_CustomerName: '绵阳信瑞达科技有限公司',
        F_CustomerCode: 'KH000005',
      },
      {
        F_Id: '2027623594334490624',
        F_CustomerName: '四川华信智创科技有限公司',
        F_CustomerCode: 'KH000003',
      },
      {
        F_Id: '2027620286773465088',
        F_CustomerName: '四川爱创科技有限公司',
        F_CustomerCode: 'KH000001',
      },
      {
        F_Id: '2027619036317224960',
        F_CustomerName: '绵阳市攀丰智能制造有限公司',
        F_CustomerCode: 'KH000002',
      },
    ],
    props: {
      label: 'F_CustomerName',
      value: 'F_Id',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_CustomerName',
  },
  {
    label: '门板厚度',
    labelI18nCode: '',
    prop: 'F_DoorPlateThickness',
    jnpfKey: 'select',
    searchType: 1,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_DoorPlateThickness',
    fullName: '门板厚度',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '门板厚度',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: true,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dictionary',
      dictionaryType: '2013183327061807104',
      propsUrl: '',
      propsName: '',
      useCache: true,
      templateJson: [],
      formId: 'formItem5a9eb1',
      renderKey: 1768965849222,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [
      {
        id: '2013183365305470976',
        fullName: '0.8',
        enCode: '0.8',
        sortCode: 0,
      },
      {
        id: '2013183391305961472',
        fullName: '1.0',
        enCode: '1.0',
        sortCode: 1,
      },
      {
        id: '2013183440664530944',
        fullName: '1.2',
        enCode: '1.2',
        sortCode: 2,
      },
      {
        id: '2013183489666584576',
        fullName: '1.5',
        enCode: '1.5',
        sortCode: 3,
      },
      {
        id: '2013183538110795776',
        fullName: '2.0',
        enCode: '2.0',
        sortCode: 4,
      },
      {
        id: '2013183565050810368',
        fullName: '3.0',
        enCode: '3.0',
        sortCode: 5,
      },
    ],
    props: {
      label: 'fullName',
      value: 'enCode',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_DoorPlateThickness',
  },
  {
    label: '箱体板厚',
    labelI18nCode: '',
    prop: 'F_BoxPlateThickness',
    jnpfKey: 'select',
    searchType: 1,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_BoxPlateThickness',
    fullName: '箱体板厚',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '箱体板厚',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: true,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dictionary',
      dictionaryType: '2013183327061807104',
      propsUrl: '',
      propsName: '',
      useCache: true,
      templateJson: [],
      formId: 'formItemd57b8a',
      renderKey: 1768965849584,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [
      {
        id: '2013183365305470976',
        fullName: '0.8',
        enCode: '0.8',
        sortCode: 0,
      },
      {
        id: '2013183391305961472',
        fullName: '1.0',
        enCode: '1.0',
        sortCode: 1,
      },
      {
        id: '2013183440664530944',
        fullName: '1.2',
        enCode: '1.2',
        sortCode: 2,
      },
      {
        id: '2013183489666584576',
        fullName: '1.5',
        enCode: '1.5',
        sortCode: 3,
      },
      {
        id: '2013183538110795776',
        fullName: '2.0',
        enCode: '2.0',
        sortCode: 4,
      },
      {
        id: '2013183565050810368',
        fullName: '3.0',
        enCode: '3.0',
        sortCode: 5,
      },
    ],
    props: {
      label: 'fullName',
      value: 'enCode',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_BoxPlateThickness',
  },
  {
    label: '安装板或安装梁',
    labelI18nCode: '',
    prop: 'F_InstallOrBeam',
    jnpfKey: 'select',
    searchType: 1,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_InstallOrBeam',
    fullName: '安装板或安装梁',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '安装板或安装梁',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: true,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dictionary',
      dictionaryType: '2013183327061807104',
      propsUrl: '',
      propsName: '',
      useCache: true,
      templateJson: [],
      formId: 'formItemf058ac',
      renderKey: 1768965850157,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [
      {
        id: '2013183365305470976',
        fullName: '0.8',
        enCode: '0.8',
        sortCode: 0,
      },
      {
        id: '2013183391305961472',
        fullName: '1.0',
        enCode: '1.0',
        sortCode: 1,
      },
      {
        id: '2013183440664530944',
        fullName: '1.2',
        enCode: '1.2',
        sortCode: 2,
      },
      {
        id: '2013183489666584576',
        fullName: '1.5',
        enCode: '1.5',
        sortCode: 3,
      },
      {
        id: '2013183538110795776',
        fullName: '2.0',
        enCode: '2.0',
        sortCode: 4,
      },
      {
        id: '2013183565050810368',
        fullName: '3.0',
        enCode: '3.0',
        sortCode: 5,
      },
    ],
    props: {
      label: 'fullName',
      value: 'enCode',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_InstallOrBeam',
  },
  {
    label: '锁具',
    labelI18nCode: '',
    prop: 'F_LockSet',
    jnpfKey: 'input',
    searchType: 2,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_LockSet',
    fullName: '锁具',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '锁具',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: true,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItem93964c',
      renderKey: 1768965851588,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_LockSet',
  },
  {
    label: '铰链',
    labelI18nCode: '',
    prop: 'F_Hinge',
    jnpfKey: 'input',
    searchType: 2,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_Hinge',
    fullName: '铰链',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '铰链',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: true,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItemc5f75a',
      renderKey: 1768965851885,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_Hinge',
  },
  {
    label: '颜色',
    labelI18nCode: '',
    prop: 'F_Color',
    jnpfKey: 'input',
    searchType: 2,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_Color',
    fullName: '颜色',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '颜色',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: true,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItem29a867',
      renderKey: 1768965852254,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_Color',
  },
  {
    label: '类别',
    labelI18nCode: '',
    prop: 'F_Type',
    jnpfKey: 'cascader',
    searchType: 1,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_Type',
    fullName: '类别',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'cascader',
      label: '类别',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfCascader',
      tagIcon: 'icon-ym icon-ym-generator-cascader',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: [],
      required: true,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dynamic',
      propsUrl: '2008414575283802112',
      propsName: '设备管理类别',
      useCache: true,
      templateJson: [],
      dictionaryType: '',
      formId: 'formIteme77d77',
      renderKey: 1768965854736,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [
      {
        F_Id: '2008446880085839872',
        F_category: '',
        F_category_id: null,
        F_Name: '超市',
        F_Tiem: '',
        children: [
          {
            F_Id: '2008446931591892992',
            F_category: '',
            F_category_id: '2008446880085839872',
            F_Name: '水果',
            F_Tiem: '',
            children: [
              {
                F_Id: '2011709255329124352',
                F_category: '',
                F_category_id: '2008446931591892992',
                F_Name: '石榴',
                F_Tiem: '',
                children: [],
              },
              {
                F_Id: '2008447030254505984',
                F_category: '',
                F_category_id: '2008446931591892992',
                F_Name: '香蕉',
                F_Tiem: '',
                children: [],
              },
              {
                F_Id: '2008446977947340800',
                F_category: '',
                F_category_id: '2008446931591892992',
                F_Name: '苹果',
                F_Tiem: '',
                children: [],
              },
            ],
          },
        ],
      },
    ],
    props: {
      value: 'id',
      label: 'F_Name',
      children: 'children',
    },
    placeholder: '请选择',
    disabled: false,
    clearable: true,
    filterable: true,
    multiple: false,
    __vModel__: 'F_Type',
  },
];
export default searchList;
