const searchList = [
  {
    label: '客户',
    labelI18nCode: '',
    prop: 'F_CustomerId',
    jnpfKey: 'select',
    searchType: 1,
    searchMultiple: true,
    isKeyword: false,
    id: 'F_CustomerId',
    fullName: '客户',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '客户',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: true,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_ctc_sales',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dynamic',
      dictionaryType: '',
      propsUrl: '2009458830353764352',
      propsName: '客户',
      useCache: true,
      templateJson: [],
      formId: 'formItem5396e1',
      renderKey: 1768269887070,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [],
    props: {
      label: 'F_CustomerName',
      value: 'F_Id',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: false,
    multiple: false,
    __vModel__: 'F_CustomerId',
  },
  {
    label: '支出日期',
    labelI18nCode: '',
    prop: 'F_ExpendDate',
    jnpfKey: 'datePicker',
    value: [],
    searchType: 3,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_ExpendDate',
    fullName: '支出日期',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'datePicker',
      label: '支出日期',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfDatePicker',
      tagIcon: 'icon-ym icon-ym-generator-date',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      defaultCurrent: true,
      required: true,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_ctc_sales',
      noShow: false,
      regList: [],
      trigger: 'change',
      startTimeRule: false,
      startTimeType: 1,
      startTimeTarget: 1,
      startTimeValue: null,
      startRelationField: '',
      endTimeRule: false,
      endTimeType: 1,
      endTimeTarget: 1,
      endTimeValue: null,
      endRelationField: '',
      formId: 'formItem3ad3b4',
      renderKey: 1768270153711,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    format: 'yyyy-MM-dd',
    startTime: null,
    endTime: null,
    disabled: false,
    clearable: true,
    __vModel__: 'F_ExpendDate',
  },
  {
    label: '支出类别',
    labelI18nCode: '',
    prop: 'F_ExpendType',
    jnpfKey: 'select',
    searchType: 1,
    searchMultiple: true,
    isKeyword: false,
    id: 'F_ExpendType',
    fullName: '支出类别',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '支出类别',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: true,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_ctc_sales',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dictionary',
      dictionaryType: '2010895416983425024',
      propsUrl: '',
      propsName: '',
      useCache: true,
      templateJson: [],
      formId: 'formItem517356',
      renderKey: 1768270175478,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [],
    props: {
      label: 'fullName',
      value: 'enCode',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: false,
    multiple: false,
    __vModel__: 'F_ExpendType',
  },
  {
    label: '金额',
    labelI18nCode: '',
    prop: 'F_Money',
    jnpfKey: 'inputNumber',
    value: [],
    searchType: 3,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_Money',
    fullName: '金额',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'inputNumber',
      label: '金额',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInputNumber',
      tagIcon: 'icon-ym icon-ym-generator-number',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: true,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_ctc_sales',
      noShow: false,
      regList: [],
      trigger: ['blur', 'change'],
      formId: 'formItemebb4fa',
      renderKey: 1768270207894,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    controls: false,
    addonBefore: '',
    addonAfter: '',
    thousands: false,
    isAmountChinese: false,
    step: 1,
    disabled: false,
    __vModel__: 'F_Money',
  },
  {
    label: '创建时间',
    labelI18nCode: '',
    prop: 'F_CreatorTime',
    jnpfKey: 'createTime',
    searchType: 3,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_CreatorTime',
    fullName: '创建时间',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'createTime',
      label: '创建时间',
      showLabel: true,
      tag: 'JnpfOpenData',
      tagIcon: 'icon-ym icon-ym-generator-createtime',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      layout: 'colFormItem',
      required: false,
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_ctc_sales',
      noShow: true,
      formId: 'formItem27542d',
      renderKey: 1768270315789,
    },
    style: {
      width: '100%',
    },
    type: 'currTime',
    readonly: true,
    placeholder: '',
    __vModel__: 'F_CreatorTime',
  },
  {
    label: '创建人员',
    labelI18nCode: '',
    prop: 'F_CreatorUserId',
    jnpfKey: 'createUser',
    searchType: 1,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_CreatorUserId',
    fullName: '创建人员',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'createUser',
      label: '创建人员',
      showLabel: true,
      tag: 'JnpfOpenData',
      tagIcon: 'icon-ym icon-ym-generator-founder',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_ctc_sales',
      noShow: true,
      formId: 'formItem13e82b',
      renderKey: 1768270304023,
    },
    style: {
      width: '100%',
    },
    type: 'currUser',
    readonly: true,
    placeholder: '',
    __vModel__: 'F_CreatorUserId',
  },
];
export default searchList;
