const searchList = [
  {
    label: '开票状态',
    labelI18nCode: '',
    prop: 'F_Status',
    jnpfKey: 'select',
    searchType: 1,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_Status',
    fullName: '开票状态',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '开票状态',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '0',
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_ctc_invoice',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dictionary',
      dictionaryType: '2039943312961572864',
      propsUrl: '',
      propsName: '',
      useCache: true,
      templateJson: [],
      formId: 'formItema8a694',
      renderKey: 1775195421628,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [
      {
        id: '2039943359392518144',
        fullName: '待开票',
        enCode: '0',
        sortCode: 0,
      },
      {
        id: '2039943392519131136',
        fullName: '开票完成',
        enCode: '1',
        sortCode: 1,
      },
    ],
    props: {
      label: 'fullName',
      value: 'enCode',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_Status',
  },
  {
    label: '开票时间',
    labelI18nCode: '',
    prop: 'F_InvoiceTime',
    jnpfKey: 'datePicker',
    value: [],
    searchType: 3,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_InvoiceTime',
    fullName: '开票时间',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'datePicker',
      label: '开票时间',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfDatePicker',
      tagIcon: 'icon-ym icon-ym-generator-date',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      defaultCurrent: false,
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_ctc_invoice',
      noShow: false,
      regList: [],
      trigger: 'change',
      startTimeRule: false,
      startTimeType: 1,
      startTimeTarget: 1,
      startTimeValue: null,
      startRelationField: '',
      endTimeRule: false,
      endTimeType: 1,
      endTimeTarget: 1,
      endTimeValue: null,
      endRelationField: '',
      formId: 'formItem1bc45a',
      renderKey: 1768268903799,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    format: 'yyyy-MM-dd',
    startTime: null,
    endTime: null,
    disabled: false,
    clearable: true,
    __vModel__: 'F_InvoiceTime',
  },
  {
    label: '开票人员',
    labelI18nCode: '',
    prop: 'F_InvoiceUserId',
    jnpfKey: 'userSelect',
    searchType: 1,
    searchMultiple: true,
    isKeyword: false,
    id: 'F_InvoiceUserId',
    fullName: '开票人员',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'userSelect',
      label: '开票人员',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfUserSelect',
      tagIcon: 'icon-ym icon-ym-generator-user',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      defaultCurrent: false,
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_ctc_invoice',
      noShow: false,
      regList: [],
      trigger: 'change',
      formId: 'formItem09a586',
      renderKey: 1768268899333,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    selectType: 'all',
    ableIds: [],
    ableRelationIds: [],
    relationField: '',
    multiple: false,
    clearable: true,
    disabled: false,
    __vModel__: 'F_InvoiceUserId',
  },
  {
    label: '申请人员',
    labelI18nCode: '',
    prop: 'F_ApplyUserId',
    jnpfKey: 'userSelect',
    searchType: 1,
    searchMultiple: true,
    isKeyword: false,
    id: 'F_ApplyUserId',
    fullName: '申请人员',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'userSelect',
      label: '申请人员',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfUserSelect',
      tagIcon: 'icon-ym icon-ym-generator-user',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      defaultCurrent: false,
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_ctc_invoice',
      noShow: false,
      regList: [],
      trigger: 'change',
      formId: 'formItem7ef739',
      renderKey: 1768268884100,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    selectType: 'all',
    ableIds: [],
    ableRelationIds: [],
    relationField: '',
    multiple: false,
    clearable: true,
    disabled: false,
    __vModel__: 'F_ApplyUserId',
  },
];
export default searchList;
