const columnList = [
  {
    label: '工单编号',
    labelI18nCode: '',
    prop: 'F_RepairNo',
    fixed: 'left',
    align: 'left',
    jnpfKey: 'input',
    sortable: false,
    width: 150,
    id: 'F_RepairNo',
    fullName: '工单编号',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '工单编号',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_maint_repair',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItem1ac98b',
      renderKey: 1769599344390,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请填写，忽略将自动生成',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_RepairNo',
  },
  {
    label: '维修设备',
    labelI18nCode: '',
    prop: 'F_DeviceId',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'popupSelect',
    sortable: false,
    width: 150,
    id: 'F_DeviceId',
    fullName: '维修设备',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'popupSelect',
      label: '维修设备',
      tipLabel: '',
      showLabel: true,
      required: true,
      tag: 'JnpfPopupSelect',
      tagIcon: 'icon-ym icon-ym-generator-popup',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_maint_repair',
      noShow: false,
      regList: [],
      trigger: 'change',
      transferList: [],
      useCache: true,
      formId: 'formItem53e724',
      renderKey: 1769600828923,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    interfaceId: '2016476904974061568',
    interfaceName: '弹窗获取设备档案列表',
    templateJson: [],
    hasPage: true,
    pageSize: 20,
    extraOptions: [],
    columnOptions: [
      {
        value: 'F_DeviceNo',
        label: '设备编号',
      },
      {
        value: 'F_DeviceName',
        label: '设备名称',
      },
      {
        value: 'F_DeviceSpec',
        label: '设备规格',
      },
      {
        value: 'F_DeviceStatus',
        label: '设备状态',
      },
      {
        value: 'F_DeviceType',
        label: '设备类别',
      },
      {
        value: 'F_WorkshopId',
        label: '车间',
      },
      {
        value: 'F_LineId',
        label: '产线',
      },
      {
        value: 'F_DeviceUsersId',
        label: '负责人',
      },
      {
        value: 'F_GroupId',
        label: '分组',
      },
      {
        value: 'F_CreatorTime',
        label: '创建时间',
      },
    ],
    propsValue: 'id',
    relationField: 'F_DeviceName',
    popupType: 'dialog',
    popupTitle: '选择数据',
    popupWidth: '1000px',
    disabled: false,
    clearable: true,
    __vModel__: 'F_DeviceId',
    interfaceHasPage: 0,
  },
  {
    label: '处理人',
    labelI18nCode: '',
    prop: 'F_HandlerUserId',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'userSelect',
    sortable: false,
    width: null,
    id: 'F_HandlerUserId',
    fullName: '处理人',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'userSelect',
      label: '处理人',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfUserSelect',
      tagIcon: 'icon-ym icon-ym-generator-user',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      defaultCurrent: true,
      required: true,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_maint_repair',
      noShow: false,
      regList: [],
      trigger: 'change',
      formId: 'formItem229d8c',
      renderKey: 1769599373990,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    selectType: 'all',
    ableIds: [],
    ableRelationIds: [],
    relationField: '',
    multiple: false,
    clearable: true,
    disabled: false,
    __vModel__: 'F_HandlerUserId',
  },
  // {
  //   "label": "分组",
  //   "labelI18nCode": "",
  //   "prop": "F_GroupId",
  //   "fixed": "none",
  //   "align": "left",
  //   "jnpfKey": "groupSelect",
  //   "sortable": false,
  //   "width": null,
  //   "id": "F_GroupId",
  //   "fullName": "分组",
  //   "fullNameI18nCode": [
  //     ""
  //   ],
  //   "__config__": {
  //     "jnpfKey": "groupSelect",
  //     "label": "分组",
  //     "tipLabel": "",
  //     "showLabel": true,
  //     "tag": "JnpfGroupSelect",
  //     "tagIcon": "icon-ym icon-ym-generator-group1",
  //     "tableAlign": "left",
  //     "tableFixed": "none",
  //     "className": [],
  //     "defaultValue": "2016346530658783232",
  //     "defaultCurrent": false,
  //     "required": false,
  //     "layout": "colFormItem",
  //     "span": 12,
  //     "dragDisabled": false,
  //     "visibility": [
  //       "pc",
  //       "app"
  //     ],
  //     "tableName": "a_maint_repair",
  //     "noShow": false,
  //     "regList": [],
  //     "trigger": "change",
  //     "formId": "formItem91f891",
  //     "renderKey": 1769599355800
  //   },
  //   "on": {
  //     "change": "({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}"
  //   },
  //   "style": {
  //     "width": "100%"
  //   },
  //   "placeholder": "请选择",
  //   "selectType": "all",
  //   "ableIds": [],
  //   "multiple": false,
  //   "clearable": true,
  //   "filterable": false,
  //   "disabled": false,
  //   "__vModel__": "F_GroupId"
  // },
  {
    label: '接单时间',
    labelI18nCode: '',
    prop: 'F_ReceiveTime',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'datePicker',
    sortable: false,
    width: 150,
    id: 'F_ReceiveTime',
    fullName: '接单时间',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'datePicker',
      label: '接单时间',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfDatePicker',
      tagIcon: 'icon-ym icon-ym-generator-date',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      defaultCurrent: false,
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_maint_repair',
      noShow: false,
      regList: [],
      trigger: 'change',
      startTimeRule: false,
      startTimeType: 1,
      startTimeTarget: 1,
      startTimeValue: null,
      startRelationField: '',
      endTimeRule: false,
      endTimeType: 1,
      endTimeTarget: 1,
      endTimeValue: null,
      endRelationField: '',
      formId: 'formItem4c016f',
      renderKey: 1769599503656,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    format: 'yyyy-MM-dd HH:mm:ss',
    startTime: null,
    endTime: null,
    disabled: false,
    clearable: true,
    __vModel__: 'F_ReceiveTime',
  },
  {
    label: '处理时间',
    labelI18nCode: '',
    prop: 'F_HandleTime',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'datePicker',
    sortable: false,
    width: 150,
    id: 'F_HandleTime',
    fullName: '处理时间',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'datePicker',
      label: '处理时间',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfDatePicker',
      tagIcon: 'icon-ym icon-ym-generator-date',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      defaultCurrent: false,
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_maint_repair',
      noShow: false,
      regList: [],
      trigger: 'change',
      startTimeRule: false,
      startTimeType: 1,
      startTimeTarget: 1,
      startTimeValue: null,
      startRelationField: '',
      endTimeRule: false,
      endTimeType: 1,
      endTimeTarget: 1,
      endTimeValue: null,
      endRelationField: '',
      formId: 'formItemf0ff54',
      renderKey: 1769599504156,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    format: 'yyyy-MM-dd HH:mm:ss',
    startTime: null,
    endTime: null,
    disabled: false,
    clearable: true,
    __vModel__: 'F_HandleTime',
  },
  {
    label: '故障描述',
    labelI18nCode: '',
    prop: 'F_Description',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'textarea',
    sortable: false,
    width: 260,
    id: 'F_Description',
    fullName: '故障描述',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'textarea',
      label: '故障描述',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfTextarea',
      tagIcon: 'icon-ym icon-ym-generator-textarea',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: true,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_maint_repair',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItemda67b0',
      renderKey: 1769599401523,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    autoSize: {
      minRows: 4,
      maxRows: 4,
    },
    clearable: true,
    maxlength: 500,
    showCount: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_Description',
  },
  {
    label: '状态',
    labelI18nCode: '',
    prop: 'F_State',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'select',
    sortable: false,
    width: null,
    id: 'F_State',
    fullName: '状态',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '状态',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_maint_repair',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dictionary',
      dictionaryType: '2016473505696190464',
      propsUrl: '',
      propsName: '',
      useCache: true,
      templateJson: [],
      formId: 'formItema1eb1d',
      renderKey: 1769599517047,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [],
    props: {
      label: 'fullName',
      value: 'enCode',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_State',
  },
  {
    label: '暂停原因',
    labelI18nCode: '',
    prop: 'F_PauseReason',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'textarea',
    sortable: false,
    width: 260,
    id: 'F_PauseReason',
    fullName: '暂停原因',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'textarea',
      label: '暂停原因',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfTextarea',
      tagIcon: 'icon-ym icon-ym-generator-textarea',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: true,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_maint_repair',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItem29ae17',
      renderKey: 1769599527391,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    autoSize: {
      minRows: 4,
      maxRows: 4,
    },
    clearable: true,
    maxlength: 500,
    showCount: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_PauseReason',
  },
  {
    label: '取消原因',
    labelI18nCode: '',
    prop: 'F_CancelReason',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'textarea',
    sortable: false,
    width: 260,
    id: 'F_CancelReason',
    fullName: '取消原因',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'textarea',
      label: '取消原因',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfTextarea',
      tagIcon: 'icon-ym icon-ym-generator-textarea',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: true,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_maint_repair',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formIteme4066f',
      renderKey: 1769599527908,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    autoSize: {
      minRows: 4,
      maxRows: 4,
    },
    clearable: true,
    maxlength: 500,
    showCount: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_CancelReason',
  },
  {
    label: '报修人',
    labelI18nCode: '',
    prop: 'F_CreatorUserId',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'createUser',
    sortable: false,
    width: null,
    id: 'F_CreatorUserId',
    fullName: '报修人',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'createUser',
      label: '报修人',
      showLabel: true,
      tag: 'JnpfOpenData',
      tagIcon: 'icon-ym icon-ym-generator-founder',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_maint_repair',
      noShow: true,
      formId: 'formItemff9448',
      renderKey: 1769599571564,
    },
    style: {
      width: '100%',
    },
    type: 'currUser',
    readonly: true,
    placeholder: '',
    __vModel__: 'F_CreatorUserId',
  },
  {
    label: '审核人',
    labelI18nCode: '',
    prop: 'F_AuditorUserId',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'userSelect',
    sortable: false,
    width: null,
    id: 'F_AuditorUserId',
    fullName: '审核人',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'userSelect',
      label: '审核人',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfUserSelect',
      tagIcon: 'icon-ym icon-ym-generator-user',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      defaultCurrent: false,
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_maint_repair',
      noShow: false,
      regList: [],
      trigger: 'change',
      formId: 'formItemb1489f',
      renderKey: 1769599544756,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    selectType: 'all',
    ableIds: [],
    ableRelationIds: [],
    relationField: '',
    multiple: false,
    clearable: true,
    disabled: false,
    __vModel__: 'F_AuditorUserId',
  },
  {
    label: '审核时间',
    labelI18nCode: '',
    prop: 'F_AuditTime',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'datePicker',
    sortable: false,
    width: 150,
    id: 'F_AuditTime',
    fullName: '审核时间',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'datePicker',
      label: '审核时间',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfDatePicker',
      tagIcon: 'icon-ym icon-ym-generator-date',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      defaultCurrent: false,
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_maint_repair',
      noShow: false,
      regList: [],
      trigger: 'change',
      startTimeRule: false,
      startTimeType: 1,
      startTimeTarget: 1,
      startTimeValue: null,
      startRelationField: '',
      endTimeRule: false,
      endTimeType: 1,
      endTimeTarget: 1,
      endTimeValue: null,
      endRelationField: '',
      formId: 'formItem9a30cb',
      renderKey: 1769599554170,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    format: 'yyyy-MM-dd HH:mm:ss',
    startTime: null,
    endTime: null,
    disabled: false,
    clearable: true,
    __vModel__: 'F_AuditTime',
  },
  {
    label: '是否解决问题',
    labelI18nCode: '',
    prop: 'F_IsSolved',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'select',
    sortable: false,
    width: null,
    id: 'F_IsSolved',
    fullName: '是否解决问题',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '是否解决问题',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_maint_repair',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'static',
      dictionaryType: '',
      propsUrl: '',
      propsName: '',
      useCache: true,
      templateJson: [],
      formId: 'formItemdf5c7d',
      renderKey: 1769599567660,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [
      {
        fullName: '是',
        id: '1',
      },
      {
        fullName: '否',
        id: '0',
      },
    ],
    props: {
      label: 'fullName',
      value: 'id',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_IsSolved',
  },
  {
    label: '处理结果',
    labelI18nCode: '',
    prop: 'F_HandleResult',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'textarea',
    sortable: false,
    width: 260,
    id: 'F_HandleResult',
    fullName: '处理结果',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'textarea',
      label: '处理结果',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfTextarea',
      tagIcon: 'icon-ym icon-ym-generator-textarea',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: true,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_maint_repair',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItem054638',
      renderKey: 1769599568350,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    autoSize: {
      minRows: 4,
      maxRows: 4,
    },
    clearable: true,
    maxlength: 500,
    showCount: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_HandleResult',
  },
  {
    label: '报修时间',
    labelI18nCode: '',
    prop: 'F_CreatorTime',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'createTime',
    sortable: false,
    width: 150,
    id: 'F_CreatorTime',
    fullName: '报修时间',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'createTime',
      label: '报修时间',
      showLabel: true,
      tag: 'JnpfOpenData',
      tagIcon: 'icon-ym icon-ym-generator-createtime',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      layout: 'colFormItem',
      required: false,
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_maint_repair',
      noShow: true,
      formId: 'formItem37d140',
      renderKey: 1769599571902,
    },
    style: {
      width: '100%',
    },
    type: 'currTime',
    readonly: true,
    placeholder: '',
    __vModel__: 'F_CreatorTime',
  },
];
export default columnList;
