const columnList = [
  {
    label: '商品编号',
    labelI18nCode: '',
    prop: 'F_GoodsNo',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'input',
    sortable: false,
    width: '150px',
    id: 'F_GoodsNo',
    fullName: '商品编号',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '商品编号',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_goods',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItem034b17',
      renderKey: 1767670574434,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_GoodsNo',
  },
  {
    label: '商品名称',
    labelI18nCode: '',
    prop: 'F_GoodsName',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'input',
    sortable: false,
    width: 150,
    id: 'F_GoodsName',
    fullName: '商品名称',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '商品名称',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_goods',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItemc10586',
      renderKey: 1767670609283,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_GoodsName',
  },

  {
    label: '规格',
    labelI18nCode: '',
    prop: 'F_Specification',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'input',
    sortable: false,
    width: 150,
    id: 'F_Specification',
    fullName: '规格',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '规格',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_goods',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItemc812df',
      renderKey: 1767670964466,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_Specification',
  },
  {
    label: '材质',
    labelI18nCode: '',
    prop: 'F_Material',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'input',
    sortable: false,
    width: null,
    id: 'F_Material',
    fullName: '材质',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '材质',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_goods',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItemc85ee1',
      renderKey: 1775629382335,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_Material',
  },
  {
    label: '类别',
    labelI18nCode: '',
    prop: 'F_CategoryId',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'cascader',
    sortable: false,
    width: null,
    id: 'F_CategoryId',
    fullName: '类别',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'cascader',
      label: '类别',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfCascader',
      tagIcon: 'icon-ym icon-ym-generator-cascader',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_goods',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dynamic',
      propsUrl: '2008414575283802112',
      propsName: '设备管理类别',
      useCache: true,
      templateJson: [],
      dictionaryType: '',
      formId: 'formItem50822f',
      renderKey: 1767679306569,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [],
    props: {
      value: 'F_Id',
      label: 'F_Name',
      children: 'children',
    },
    placeholder: '请选择',
    disabled: false,
    clearable: true,
    filterable: false,
    multiple: false,
    __vModel__: 'F_CategoryId',
  },
  {
    label: '单位',
    labelI18nCode: '',
    prop: 'F_Unit',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'input',
    sortable: false,
    width: null,
    id: 'F_Unit',
    fullName: '单位',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '单位',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_goods',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItem0b360f',
      renderKey: 1767670685500,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_Unit',
  },
  {
    label: '销售单价',
    labelI18nCode: '',
    prop: 'F_SalePrice',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'inputNumber',
    sortable: false,
    width: null,
    id: 'F_SalePrice',
    fullName: '销售单价',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'inputNumber',
      label: '销售单价',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInputNumber',
      tagIcon: 'icon-ym icon-ym-generator-number',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_goods',
      noShow: false,
      regList: [],
      trigger: ['blur', 'change'],
      formId: 'formItemf981b1',
      renderKey: 1767682279017,
      defaultValue: null,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    controls: true,
    addonBefore: '',
    addonAfter: '',
    thousands: false,
    isAmountChinese: false,
    step: 1,
    disabled: false,
    __vModel__: 'F_SalePrice',
  },
  {
    label: '成本单价',
    labelI18nCode: '',
    prop: 'F_CostPrice',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'inputNumber',
    sortable: false,
    width: null,
    id: 'F_CostPrice',
    fullName: '成本单价',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'inputNumber',
      label: '成本单价',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInputNumber',
      tagIcon: 'icon-ym icon-ym-generator-number',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_goods',
      noShow: false,
      regList: [],
      trigger: ['blur', 'change'],
      formId: 'formItema77dec',
      renderKey: 1767670714034,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    controls: false,
    addonBefore: '',
    addonAfter: '',
    thousands: false,
    isAmountChinese: false,
    step: 1,
    disabled: false,
    __vModel__: 'F_CostPrice',
  },
  {
    label: '售后佣金',
    labelI18nCode: '',
    prop: 'F_CommissionFixed',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'inputNumber',
    sortable: false,
    width: null,
    id: 'F_CommissionFixed',
    fullName: '售后佣金',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'inputNumber',
      label: '售后佣金',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInputNumber',
      tagIcon: 'icon-ym icon-ym-generator-number',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_goods',
      noShow: false,
      regList: [],
      trigger: ['blur', 'change'],
      formId: 'formItem0daec6',
      renderKey: 1767670743851,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    controls: false,
    addonBefore: '',
    addonAfter: '',
    thousands: false,
    isAmountChinese: false,
    step: 1,
    disabled: false,
    __vModel__: 'F_CommissionFixed',
  },
  {
    label: '商品来源',
    labelI18nCode: '',
    prop: 'F_Source',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'input',
    sortable: false,
    width: 120,
    id: 'F_Source',
    fullName: '商品来源',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '商品来源',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_goods',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItemd773e8',
      renderKey: 1767670804851,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_Source',
  },
  {
    label: '商品类型',
    labelI18nCode: '',
    prop: 'F_Type',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'select',
    sortable: false,
    width: null,
    id: 'F_Type',
    fullName: '商品类型',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '商品类型',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_goods',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dictionary',
      dictionaryType: '2029481827470807040',
      propsUrl: '',
      propsName: '',
      useCache: true,
      templateJson: [],
      formId: 'formItemf48b7b',
      renderKey: 1772701906547,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [],
    props: {
      label: 'fullName',
      value: 'enCode',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_Type',
  },
  {
    label: '检验规范',
    labelI18nCode: '',
    prop: 'F_InspectRule',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'input',
    sortable: false,
    width: null,
    id: 'F_InspectRule',
    fullName: '检验规范',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '检验规范',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_goods',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItembb8f48',
      renderKey: 1767670977587,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_InspectRule',
  },
  {
    label: '库存上限警告值',
    labelI18nCode: '',
    prop: 'F_StockUpperLimit',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'inputNumber',
    sortable: false,
    width: 120,
    id: 'F_StockUpperLimit',
    fullName: '库存上限警告值',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'inputNumber',
      label: '库存上限警告值',
      tipLabel: '设置该商品在仓库中的默认库存上限的警告值。',
      showLabel: true,
      tag: 'JnpfInputNumber',
      tagIcon: 'icon-ym icon-ym-generator-number',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_goods',
      noShow: false,
      regList: [],
      trigger: ['blur', 'change'],
      formId: 'formItem16780b',
      renderKey: 1767671041736,
      defaultValue: null,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    controls: false,
    addonBefore: '',
    addonAfter: '',
    thousands: false,
    isAmountChinese: false,
    step: 1,
    precision: 1,
    disabled: false,
    __vModel__: 'F_StockUpperLimit',
  },
  {
    label: '库存下限警告值',
    labelI18nCode: '',
    prop: 'F_StockLowerLimit',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'inputNumber',
    sortable: false,
    width: 120,
    id: 'F_StockLowerLimit',
    fullName: '库存下限警告值',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'inputNumber',
      label: '库存下限警告值',
      tipLabel: '设置该商品在仓库中的默认库存下限的警告值。',
      showLabel: true,
      tag: 'JnpfInputNumber',
      tagIcon: 'icon-ym icon-ym-generator-number',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_goods',
      noShow: false,
      regList: [],
      trigger: ['blur', 'change'],
      formId: 'formItemd6ec58',
      renderKey: 1767671064772,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    controls: false,
    addonBefore: '',
    addonAfter: '',
    thousands: false,
    isAmountChinese: false,
    step: 1,
    precision: 1,
    disabled: false,
    __vModel__: 'F_StockLowerLimit',
  },
  {
    label: '外协单价',
    labelI18nCode: '',
    prop: 'F_OutsourcePrice',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'inputNumber',
    sortable: false,
    width: null,
    id: 'F_OutsourcePrice',
    fullName: '外协单价',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'inputNumber',
      label: '外协单价',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInputNumber',
      tagIcon: 'icon-ym icon-ym-generator-number',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_goods',
      noShow: false,
      regList: [],
      trigger: ['blur', 'change'],
      formId: 'formItem899814',
      renderKey: 1767670816092,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    controls: false,
    addonBefore: '',
    addonAfter: '',
    thousands: false,
    isAmountChinese: false,
    step: 1,
    disabled: false,
    __vModel__: 'F_OutsourcePrice',
  },
  {
    label: '供应商',
    labelI18nCode: '',
    prop: 'F_SupplierId',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'input',
    sortable: false,
    width: null,
    id: 'F_SupplierId',
    fullName: '供应商ID',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '供应商ID',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_goods',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItem5b87aa',
      renderKey: 1767670948553,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_SupplierId',
  },
  {
    label: '商品编码',
    labelI18nCode: '',
    prop: 'F_Encoding',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'input',
    sortable: false,
    width: null,
    id: 'F_Encoding',
    fullName: '商品编码',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '商品编码',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_goods',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItema40069',
      renderKey: 1773904130700,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_Encoding',
  },
  {
    label: '商品图片',
    labelI18nCode: '',
    prop: 'F_Image',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'uploadImg',
    sortable: false,
    width: null,
    id: 'F_Image',
    fullName: '商品图片',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'uploadImg',
      label: '商品图片',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfUploadImg',
      tagIcon: 'icon-ym icon-ym-generator-upload',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: [],
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_goods',
      noShow: false,
      regList: [],
      trigger: 'change',
      formId: 'formItemc1088a',
      renderKey: 1767671086919,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    disabled: false,
    fileSize: 10,
    sizeUnit: 'MB',
    buttonText: '点击上传',
    limit: 9,
    pathType: 'defaultPath',
    sortRule: [],
    timeFormat: 'YYYY',
    folder: '',
    tipText: '',
    showType: 'card',
    __vModel__: 'F_Image',
  },
  {
    label: '创建用户',
    labelI18nCode: '',
    prop: 'F_CreatorUserId',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'createUser',
    sortable: false,
    width: 120,
    id: 'F_CreatorUserId',
    fullName: '创建用户',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'createUser',
      label: '创建用户',
      showLabel: true,
      tag: 'JnpfOpenData',
      tagIcon: 'icon-ym icon-ym-generator-founder',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_goods',
      noShow: true,
      formId: 'formItem6d9dfe',
      renderKey: 1767671290900,
    },
    style: {
      width: '100%',
    },
    type: 'currUser',
    readonly: true,
    placeholder: '',
    __vModel__: 'F_CreatorUserId',
  },
  {
    label: '创建时间',
    labelI18nCode: '',
    prop: 'F_CreatorTime',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'createTime',
    sortable: false,
    width: 150,
    id: 'F_CreatorTime',
    fullName: '创建时间',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'createTime',
      label: '创建时间',
      showLabel: true,
      tag: 'JnpfOpenData',
      tagIcon: 'icon-ym icon-ym-generator-createtime',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      layout: 'colFormItem',
      required: false,
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_goods',
      noShow: true,
      formId: 'formItemb2c1f3',
      renderKey: 1767671290353,
    },
    style: {
      width: '100%',
    },
    type: 'currTime',
    readonly: true,
    placeholder: '',
    __vModel__: 'F_CreatorTime',
  },
  {
    label: '附件',
    labelI18nCode: '',
    prop: 'F_AttachmentUrl',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'uploadFile',
    sortable: false,
    width: null,
    id: 'F_AttachmentUrl',
    fullName: '附件',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'uploadFile',
      label: '附件',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfUploadFile',
      tagIcon: 'icon-ym icon-ym-generator-upload',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: [],
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_goods',
      noShow: false,
      regList: [],
      trigger: 'change',
      formId: 'formItem21cb6f',
      renderKey: 1767671100169,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    disabled: false,
    accept: '',
    fileSize: 10,
    sizeUnit: 'MB',
    buttonText: '点击上传',
    limit: 9,
    pathType: 'defaultPath',
    sortRule: [],
    timeFormat: 'YYYY',
    folder: '',
    tipText: '',
    __vModel__: 'F_AttachmentUrl',
  },
];
export default columnList;
