const searchList = [
  {
    label: '商品',
    labelI18nCode: '',
    prop: 'F_GoodsId',
    jnpfKey: 'select',
    searchType: 1,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_GoodsId',
    fullName: '商品',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '商品',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_goods_inventory',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dynamic',
      dictionaryType: '',
      propsUrl: '2012085692393459712',
      propsName: '弹窗获取商品列表（可传合同ID）',
      useCache: true,
      templateJson: [
        {
          id: 'b6217b',
          field: 'contractId',
          dataType: 'varchar',
          defaultValue: '',
          required: 0,
          fieldName: '合同ID',
          relationField: '',
          sourceType: 3,
        },
      ],
      formId: 'formItem8ae28a',
      renderKey: 1769152534785,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [
      {
        id: '2014578461892546560',
        F_GoodsNo: 'SP202601230003',
        F_GoodsName: 'JG3-SP202601230003',
        F_CategoryId: '超市',
        F_Unit: '个',
        F_SalePrice: null,
        F_CostPrice: null,
        F_CommissionFixed: null,
        F_Source: null,
        F_OutsourcePrice: null,
        F_SupplierId: null,
        F_Specification: null,
        F_InspectRule: null,
        F_StockUpperLimit: null,
        F_StockLowerLimit: null,
        F_Image: null,
        F_AttachmentUrl: null,
        F_CreatorTime: '2026-01-23T13:58:29Z',
        F_CreatorUserId: null,
        F_Remark: null,
      },
      {
        id: '2014578381563236352',
        F_GoodsNo: 'SP202601230002',
        F_GoodsName: 'JG2-SP202601230002',
        F_CategoryId: '超市',
        F_Unit: '台',
        F_SalePrice: null,
        F_CostPrice: null,
        F_CommissionFixed: null,
        F_Source: null,
        F_OutsourcePrice: null,
        F_SupplierId: null,
        F_Specification: null,
        F_InspectRule: null,
        F_StockUpperLimit: null,
        F_StockLowerLimit: null,
        F_Image: null,
        F_AttachmentUrl: null,
        F_CreatorTime: '2026-01-23T13:58:09Z',
        F_CreatorUserId: null,
        F_Remark: null,
      },
      {
        id: '2014578308263579648',
        F_GoodsNo: 'SP202601230001',
        F_GoodsName: 'JG1-SP202601230001',
        F_CategoryId: '超市',
        F_Unit: '个',
        F_SalePrice: null,
        F_CostPrice: null,
        F_CommissionFixed: null,
        F_Source: null,
        F_OutsourcePrice: null,
        F_SupplierId: null,
        F_Specification: null,
        F_InspectRule: null,
        F_StockUpperLimit: null,
        F_StockLowerLimit: null,
        F_Image: null,
        F_AttachmentUrl: null,
        F_CreatorTime: '2026-01-23T13:57:52Z',
        F_CreatorUserId: null,
        F_Remark: null,
      },
      {
        id: '2013948044566990848',
        F_GoodsNo: 'SP202601210001',
        F_GoodsName: '披萨-SP202601210001',
        F_CategoryId: null,
        F_Unit: null,
        F_SalePrice: null,
        F_CostPrice: null,
        F_CommissionFixed: null,
        F_Source: null,
        F_OutsourcePrice: null,
        F_SupplierId: null,
        F_Specification: null,
        F_InspectRule: null,
        F_StockUpperLimit: null,
        F_StockLowerLimit: null,
        F_Image: null,
        F_AttachmentUrl: null,
        F_CreatorTime: '2026-01-21T20:13:25Z',
        F_CreatorUserId: null,
        F_Remark: null,
      },
      {
        id: '2011713069100699648',
        F_GoodsNo: 'SP20260115160001',
        F_GoodsName: 'CS2-SP20260115160001',
        F_CategoryId: '超市',
        F_Unit: '个',
        F_SalePrice: null,
        F_CostPrice: null,
        F_CommissionFixed: null,
        F_Source: null,
        F_OutsourcePrice: null,
        F_SupplierId: null,
        F_Specification: null,
        F_InspectRule: null,
        F_StockUpperLimit: null,
        F_StockLowerLimit: null,
        F_Image: null,
        F_AttachmentUrl: null,
        F_CreatorTime: '2026-01-15T16:12:26Z',
        F_CreatorUserId: null,
        F_Remark: null,
      },
      {
        id: '2011713010275586048',
        F_GoodsNo: 'sp20260115160001',
        F_GoodsName: 'CS1-sp20260115160001',
        F_CategoryId: null,
        F_Unit: '台',
        F_SalePrice: null,
        F_CostPrice: null,
        F_CommissionFixed: null,
        F_Source: null,
        F_OutsourcePrice: null,
        F_SupplierId: null,
        F_Specification: null,
        F_InspectRule: null,
        F_StockUpperLimit: null,
        F_StockLowerLimit: null,
        F_Image: null,
        F_AttachmentUrl: null,
        F_CreatorTime: '2026-01-15T16:12:12Z',
        F_CreatorUserId: null,
        F_Remark: null,
      },
      {
        id: '2010976325753507840',
        F_GoodsNo: 'SP20260115160003',
        F_GoodsName: '苹果-SP20260115160003',
        F_CategoryId: '超市',
        F_Unit: '个',
        F_SalePrice: null,
        F_CostPrice: null,
        F_CommissionFixed: null,
        F_Source: null,
        F_OutsourcePrice: null,
        F_SupplierId: null,
        F_Specification: '1*1',
        F_InspectRule: '无',
        F_StockUpperLimit: null,
        F_StockLowerLimit: null,
        F_Image: null,
        F_AttachmentUrl: null,
        F_CreatorTime: '2026-01-13T07:24:53Z',
        F_CreatorUserId: null,
        F_Remark: '测试备注',
      },
      {
        id: '2008839754363310080',
        F_GoodsNo: 'sp20260107170001',
        F_GoodsName: '木材-sp20260107170001',
        F_CategoryId: null,
        F_Unit: '台',
        F_SalePrice: null,
        F_CostPrice: null,
        F_CommissionFixed: null,
        F_Source: null,
        F_OutsourcePrice: null,
        F_SupplierId: null,
        F_Specification: null,
        F_InspectRule: null,
        F_StockUpperLimit: null,
        F_StockLowerLimit: null,
        F_Image: null,
        F_AttachmentUrl: null,
        F_CreatorTime: '2026-01-07T17:54:54Z',
        F_CreatorUserId: null,
        F_Remark: null,
      },
    ],
    props: {
      label: 'F_GoodsName',
      value: 'id',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_GoodsId',
  },
  {
    label: '仓库',
    labelI18nCode: '',
    prop: 'F_WarehouseId',
    jnpfKey: 'select',
    searchType: 1,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_WarehouseId',
    fullName: '仓库',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '仓库',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_goods_inventory',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dynamic',
      dictionaryType: '',
      propsUrl: '2012073572784279552',
      propsName: '入库仓库',
      useCache: true,
      templateJson: [],
      formId: 'formIteme2f59d',
      renderKey: 1769152535273,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [
      {
        F_Id: '2014233789731049472',
        F_Name: '金家林5G仓',
      },
    ],
    props: {
      label: 'F_Name',
      value: 'F_Id',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_WarehouseId',
  },
  {
    label: '库存数量',
    labelI18nCode: '',
    prop: 'F_Num',
    jnpfKey: 'inputNumber',
    value: [],
    searchType: 3,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_Num',
    fullName: '库存数量',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'inputNumber',
      label: '库存数量',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInputNumber',
      tagIcon: 'icon-ym icon-ym-generator-number',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_goods_inventory',
      noShow: false,
      regList: [],
      trigger: ['blur', 'change'],
      formId: 'formItem7a3fa2',
      renderKey: 1769152715133,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    min: 0,
    controls: false,
    addonBefore: '',
    addonAfter: '',
    thousands: false,
    isAmountChinese: false,
    step: 1,
    precision: 0,
    disabled: false,
    __vModel__: 'F_Num',
  },
  {
    label: '创建时间',
    labelI18nCode: '',
    prop: 'F_CreatorTime',
    jnpfKey: 'createTime',
    searchType: 3,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_CreatorTime',
    fullName: '创建时间',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'createTime',
      label: '创建时间',
      showLabel: true,
      tag: 'JnpfOpenData',
      tagIcon: 'icon-ym icon-ym-generator-createtime',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      layout: 'colFormItem',
      required: false,
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_goods_inventory',
      noShow: true,
      formId: 'formItem5f198b',
      renderKey: 1769152539421,
    },
    style: {
      width: '100%',
    },
    type: 'currTime',
    readonly: true,
    placeholder: '',
    __vModel__: 'F_CreatorTime',
  },
];
export default searchList;
