const columnList = [
  {
    label: '调拨单号',
    labelI18nCode: '',
    prop: 'F_TransferNo',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'userSelect',
    sortable: false,
    width: 150,
    resizable: true,
    id: 'F_TransferNo',
    fullName: '调拨单号',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'userSelect',
      label: '调拨单号',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfUserSelect',
      tagIcon: 'icon-ym icon-ym-generator-user',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      defaultCurrent: true,
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_pu_transfer',
      noShow: false,
      regList: [],
      trigger: 'change',
      formId: 'formItem9733e1',
      renderKey: 1768896464386,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    selectType: 'all',
    ableIds: [],
    ableRelationIds: [],
    relationField: '',
    multiple: false,
    clearable: true,
    disabled: false,
    __vModel__: 'F_TransferNo',
  },
  {
    label: '调拨日期',
    labelI18nCode: '',
    prop: 'F_TransferDate',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'datePicker',
    sortable: false,
    width: null,
    resizable: true,
    id: 'F_TransferDate',
    fullName: '调拨日期',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'datePicker',
      label: '调拨日期',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfDatePicker',
      tagIcon: 'icon-ym icon-ym-generator-date',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      defaultCurrent: true,
      required: true,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_pu_transfer',
      noShow: false,
      regList: [],
      trigger: 'change',
      startTimeRule: false,
      startTimeType: 1,
      startTimeTarget: 1,
      startTimeValue: null,
      startRelationField: '',
      endTimeRule: false,
      endTimeType: 1,
      endTimeTarget: 1,
      endTimeValue: null,
      endRelationField: '',
      formId: 'formItem0b6990',
      renderKey: 1768896449509,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    format: 'yyyy-MM-dd',
    startTime: null,
    endTime: null,
    disabled: false,
    clearable: true,
    __vModel__: 'F_TransferDate',
  },
  {
    label: '调拨人',
    labelI18nCode: '',
    prop: 'F_TransferUserId',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'userSelect',
    sortable: false,
    width: null,
    resizable: true,
    id: 'F_TransferUserId',
    fullName: '调拨人',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'userSelect',
      label: '调拨人',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfUserSelect',
      tagIcon: 'icon-ym icon-ym-generator-user',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      defaultCurrent: true,
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_pu_transfer',
      noShow: false,
      regList: [],
      trigger: 'change',
      formId: 'formItem9733e1',
      renderKey: 1768896464386,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    selectType: 'all',
    ableIds: [],
    ableRelationIds: [],
    relationField: '',
    multiple: false,
    clearable: true,
    disabled: false,
    __vModel__: 'F_TransferUserId',
  },
  {
    label: '发出仓库',
    labelI18nCode: '',
    prop: 'F_FromWarehouseId',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'cascader',
    sortable: false,
    width: 150,
    resizable: true,
    id: 'F_FromWarehouseId',
    fullName: '发出仓库',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'cascader',
      label: '发出仓库',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfCascader',
      tagIcon: 'icon-ym icon-ym-generator-cascader',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: [],
      required: true,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_pu_transfer',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dynamic',
      propsUrl: '2021045201115680768',
      propsName: '仓库管理（树状）',
      useCache: true,
      templateJson: [],
      dictionaryType: '',
      formId: 'formItemb42a3b',
      renderKey: 1772444178193,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [],
    props: {
      value: 'F_Id',
      label: 'F_Name',
      children: 'children',
    },
    placeholder: '请选择',
    disabled: false,
    clearable: true,
    filterable: false,
    multiple: false,
    __vModel__: 'F_FromWarehouseId',
  },
  {
    label: '收入仓库',
    labelI18nCode: '',
    prop: 'F_ToWarehouseId',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'cascader',
    sortable: false,
    width: 150,
    resizable: true,
    id: 'F_ToWarehouseId',
    fullName: '收入仓库',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'cascader',
      label: '收入仓库',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfCascader',
      tagIcon: 'icon-ym icon-ym-generator-cascader',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: [],
      required: true,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_pu_transfer',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dynamic',
      propsUrl: '2021045201115680768',
      propsName: '仓库管理（树状）',
      useCache: true,
      templateJson: [],
      dictionaryType: '',
      formId: 'formItem9f1a22',
      renderKey: 1772444294105,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [],
    props: {
      value: 'F_Id',
      label: 'F_Name',
      children: 'children',
    },
    placeholder: '请选择',
    disabled: false,
    clearable: true,
    filterable: true,
    multiple: false,
    __vModel__: 'F_ToWarehouseId',
  },

  {
    label: '调拨人员',
    labelI18nCode: '',
    prop: 'F_CreatorUserId',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'createUser',
    sortable: false,
    width: null,
    resizable: true,
    id: 'F_CreatorUserId',
    fullName: '创建人员',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'createUser',
      label: '创建人员',
      showLabel: true,
      tag: 'JnpfOpenData',
      tagIcon: 'icon-ym icon-ym-generator-founder',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_pu_transfer',
      noShow: false,
      formId: 'formItem724641',
      renderKey: 1768896671034,
    },
    style: {
      width: '100%',
    },
    type: 'currUser',
    readonly: true,
    placeholder: '',
    __vModel__: 'F_CreatorUserId',
  },
  {
    label: '调拨时间',
    labelI18nCode: '',
    prop: 'F_CreatorTime',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'createTime',
    sortable: false,
    width: 150,
    resizable: true,
    id: 'F_CreatorTime',
    fullName: '创建时间',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'createTime',
      label: '创建时间',
      showLabel: true,
      tag: 'JnpfOpenData',
      tagIcon: 'icon-ym icon-ym-generator-createtime',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      layout: 'colFormItem',
      required: false,
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_pu_transfer',
      noShow: false,
      formId: 'formItem19cc98',
      renderKey: 1768896671482,
    },
    style: {
      width: '100%',
    },
    type: 'currTime',
    readonly: true,
    placeholder: '',
    __vModel__: 'F_CreatorTime',
  },
  {
    label: '备注',
    labelI18nCode: '',
    prop: 'F_Description',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'textarea',
    sortable: false,
    width: 260,
    resizable: true,
    id: 'F_Description',
    fullName: '备注',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'textarea',
      label: '备注',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfTextarea',
      tagIcon: 'icon-ym icon-ym-generator-textarea',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_pu_transfer',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItem1f82c2',
      renderKey: 1768896654287,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    autoSize: {
      minRows: 2,
      maxRows: 4,
    },
    clearable: true,
    maxlength: null,
    showCount: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_Description',
  },
];
export default columnList;
