const searchList = [
  {
    label: '调拨日期',
    labelI18nCode: '',
    prop: 'F_TransferDate',
    jnpfKey: 'datePicker',
    value: [],
    searchType: 3,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_TransferDate',
    fullName: '调拨日期',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'datePicker',
      label: '调拨日期',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfDatePicker',
      tagIcon: 'icon-ym icon-ym-generator-date',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      defaultCurrent: true,
      required: true,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_pu_transfer',
      noShow: false,
      regList: [],
      trigger: 'change',
      startTimeRule: false,
      startTimeType: 1,
      startTimeTarget: 1,
      startTimeValue: null,
      startRelationField: '',
      endTimeRule: false,
      endTimeType: 1,
      endTimeTarget: 1,
      endTimeValue: null,
      endRelationField: '',
      formId: 'formItem0b6990',
      renderKey: 1768896449509,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    format: 'yyyy-MM-dd',
    startTime: null,
    endTime: null,
    disabled: false,
    clearable: true,
    __vModel__: 'F_TransferDate',
  },
  {
    label: '发出仓库',
    labelI18nCode: '',
    prop: 'F_FromWarehouseId',
    jnpfKey: 'input',
    searchType: 2,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_FromWarehouseId',
    fullName: '发出仓库',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '发出仓库',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_customer',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItemd5ff29',
      renderKey: 1767858434670,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_FromWarehouseId',
  },
  // {
  //   label: '发出仓库',
  //   labelI18nCode: '',
  //   prop: 'F_FromWarehouseId',
  //   jnpfKey: 'cascader',
  //   searchType: 1,
  //   searchMultiple: false,
  //   isKeyword: false,
  //   id: 'F_FromWarehouseId',
  //   fullName: '发出仓库',
  //   fullNameI18nCode: [''],
  //   __config__: {
  //     jnpfKey: 'cascader',
  //     label: '发出仓库',
  //     tipLabel: '',
  //     showLabel: true,
  //     tag: 'JnpfCascader',
  //     tagIcon: 'icon-ym icon-ym-generator-cascader',
  //     tableAlign: 'left',
  //     tableFixed: 'none',
  //     className: [],
  //     defaultValue: [],
  //     required: true,
  //     layout: 'colFormItem',
  //     span: 8,
  //     dragDisabled: false,
  //     visibility: ['pc', 'app'],
  //     tableName: 'a_pu_transfer',
  //     noShow: false,
  //     regList: [],
  //     trigger: 'change',
  //     dataType: 'dynamic',
  //     propsUrl: '2021045201115680768',
  //     propsName: '仓库管理（树状）',
  //     useCache: true,
  //     templateJson: [],
  //     dictionaryType: '',
  //     formId: 'formItemb42a3b',
  //     renderKey: 1772444178193,
  //   },
  //   on: {
  //     change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
  //     blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
  //   },
  //   style: {
  //     width: '100%',
  //   },
  //   options: [
  //     {
  //       F_Id: '2021048550619746304',
  //       F_ParentId: null,
  //       F_Name: '测试储存2级',
  //       F_Address: '002',
  //       _realParentId: null,
  //       children: [],
  //     },
  //     {
  //       F_Id: '2014233789731049472',
  //       F_ParentId: null,
  //       F_Name: '金家林5G仓',
  //       F_Address: '金家林',
  //       _realParentId: null,
  //       children: [
  //         {
  //           F_Id: '2026473367191818240',
  //           F_ParentId: '["2014233789731049472"]',
  //           F_Name: '5G仓库2级',
  //           F_Address: '001',
  //           _realParentId: '2014233789731049472',
  //           children: [
  //             {
  //               F_Id: '2026483124422184960',
  //               F_ParentId: '["2014233789731049472","2026473367191818240"]',
  //               F_Name: '5G仓库3级',
  //               F_Address: '测试',
  //               _realParentId: '2026473367191818240',
  //               children: [],
  //             },
  //           ],
  //         },
  //       ],
  //     },
  //   ],
  //   props: {
  //     value: 'F_Id',
  //     label: 'F_Name',
  //     children: 'children',
  //   },
  //   placeholder: '请选择',
  //   disabled: false,
  //   clearable: true,
  //   filterable: false,
  //   multiple: false,
  //   __vModel__: 'F_FromWarehouseId',
  // },
  {
    label: '调拨人',
    labelI18nCode: '',
    prop: 'F_TransferUserId',
    jnpfKey: 'userSelect',
    searchType: 1,
    searchMultiple: true,
    isKeyword: false,
    id: 'F_TransferUserId',
    fullName: '调拨人',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'userSelect',
      label: '调拨人',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfUserSelect',
      tagIcon: 'icon-ym icon-ym-generator-user',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      defaultCurrent: true,
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_pu_transfer',
      noShow: false,
      regList: [],
      trigger: 'change',
      formId: 'formItem9733e1',
      renderKey: 1768896464386,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    selectType: 'all',
    ableIds: [],
    ableRelationIds: [],
    relationField: '',
    multiple: false,
    clearable: true,
    disabled: false,
    __vModel__: 'F_TransferUserId',
  },

  {
    label: '收入仓库',
    labelI18nCode: '',
    prop: 'F_ToWarehouseId',
    jnpfKey: 'input',
    searchType: 2,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_ToWarehouseId',
    fullName: '收入仓库',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '收入仓库',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_customer',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItemd5ff29',
      renderKey: 1767858434670,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_ToWarehouseId',
  },
  // {
  //   label: '收入仓库',
  //   labelI18nCode: '',
  //   prop: 'F_ToWarehouseId',
  //   jnpfKey: 'cascader',
  //   searchType: 1,
  //   searchMultiple: false,
  //   isKeyword: false,
  //   id: 'F_ToWarehouseId',
  //   fullName: '收入仓库',
  //   fullNameI18nCode: [''],
  //   __config__: {
  //     jnpfKey: 'cascader',
  //     label: '收入仓库',
  //     tipLabel: '',
  //     showLabel: true,
  //     tag: 'JnpfCascader',
  //     tagIcon: 'icon-ym icon-ym-generator-cascader',
  //     tableAlign: 'left',
  //     tableFixed: 'none',
  //     className: [],
  //     defaultValue: [],
  //     required: true,
  //     layout: 'colFormItem',
  //     span: 8,
  //     dragDisabled: false,
  //     visibility: ['pc', 'app'],
  //     tableName: 'a_pu_transfer',
  //     noShow: false,
  //     regList: [],
  //     trigger: 'change',
  //     dataType: 'dynamic',
  //     propsUrl: '2021045201115680768',
  //     propsName: '仓库管理（树状）',
  //     useCache: true,
  //     templateJson: [],
  //     dictionaryType: '',
  //     formId: 'formItem9f1a22',
  //     renderKey: 1772444294105,
  //   },
  //   on: {
  //     change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
  //     blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
  //   },
  //   style: {
  //     width: '100%',
  //   },
  //   options: [
  //     {
  //       F_Id: '2021048550619746304',
  //       F_ParentId: null,
  //       F_Name: '测试储存2级',
  //       F_Address: '002',
  //       _realParentId: null,
  //       children: [],
  //     },
  //     {
  //       F_Id: '2014233789731049472',
  //       F_ParentId: null,
  //       F_Name: '金家林5G仓',
  //       F_Address: '金家林',
  //       _realParentId: null,
  //       children: [
  //         {
  //           F_Id: '2026473367191818240',
  //           F_ParentId: '["2014233789731049472"]',
  //           F_Name: '5G仓库2级',
  //           F_Address: '001',
  //           _realParentId: '2014233789731049472',
  //           children: [
  //             {
  //               F_Id: '2026483124422184960',
  //               F_ParentId: '["2014233789731049472","2026473367191818240"]',
  //               F_Name: '5G仓库3级',
  //               F_Address: '测试',
  //               _realParentId: '2026473367191818240',
  //               children: [],
  //             },
  //           ],
  //         },
  //       ],
  //     },
  //   ],
  //   props: {
  //     value: 'F_Id',
  //     label: 'F_Name',
  //     children: 'children',
  //   },
  //   placeholder: '请选择',
  //   disabled: false,
  //   clearable: true,
  //   filterable: true,
  //   multiple: false,
  //   __vModel__: 'F_ToWarehouseId',
  // },
  {
    label: '创建时间',
    labelI18nCode: '',
    prop: 'F_CreatorTime',
    jnpfKey: 'createTime',
    searchType: 3,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_CreatorTime',
    fullName: '创建时间',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'createTime',
      label: '创建时间',
      showLabel: true,
      tag: 'JnpfOpenData',
      tagIcon: 'icon-ym icon-ym-generator-createtime',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      layout: 'colFormItem',
      required: false,
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_pu_transfer',
      noShow: false,
      formId: 'formItem19cc98',
      renderKey: 1768896671482,
    },
    style: {
      width: '100%',
    },
    type: 'currTime',
    readonly: true,
    placeholder: '',
    __vModel__: 'F_CreatorTime',
  },
  {
    label: '创建人员',
    labelI18nCode: '',
    prop: 'F_CreatorUserId',
    jnpfKey: 'createUser',
    searchType: 1,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_CreatorUserId',
    fullName: '创建人员',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'createUser',
      label: '创建人员',
      showLabel: true,
      tag: 'JnpfOpenData',
      tagIcon: 'icon-ym icon-ym-generator-founder',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_pu_transfer',
      noShow: false,
      formId: 'formItem724641',
      renderKey: 1768896671034,
    },
    style: {
      width: '100%',
    },
    type: 'currUser',
    readonly: true,
    placeholder: '',
    __vModel__: 'F_CreatorUserId',
  },
];
export default searchList;
