const columnList = [
  {
    label: '二维码编号',
    labelI18nCode: '',
    prop: 'F_Code',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'input',
    sortable: false,
    width: 150,
    id: 'F_Code',
    fullName: '二维码编号',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '二维码编号',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_maint_device_qr',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItem62788c',
      renderKey: 1769571741128,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_Code',
  },
  {
    label: '设备编号',
    labelI18nCode: '',
    prop: 'F_DeviceNo',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'input',
    sortable: false,
    width: 150,
    id: 'F_DeviceNo',
    fullName: '设备编号',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '设备编号',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_maint_device_qr',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItem62788c',
      renderKey: 1769571741128,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_DeviceNo',
  },
  {
    label: '设备名称',
    labelI18nCode: '',
    prop: 'F_DeviceName',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'input',
    sortable: false,
    width: 150,
    id: 'F_DeviceName',
    fullName: '设备名称',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '设备名称',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_maint_device_qr',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItem62788c',
      renderKey: 1769571741128,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_DeviceName',
  },
  {
    label: '设备规格',
    labelI18nCode: '',
    prop: 'F_DeviceSpec',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'input',
    sortable: false,
    width: 150,
    id: 'F_DeviceSpec',
    fullName: '设备规格',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '设备规格',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_maint_device_qr',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItem62788c',
      renderKey: 1769571741128,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_DeviceSpec',
  },
  {
    label: '生成用户',
    labelI18nCode: '',
    prop: 'F_CreatorUserId',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'createUser',
    sortable: false,
    width: null,
    id: 'F_CreatorUserId',
    fullName: '生成用户',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'createUser',
      label: '生成用户',
      showLabel: true,
      tag: 'JnpfOpenData',
      tagIcon: 'icon-ym icon-ym-generator-founder',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_maint_device_qr',
      noShow: true,
      formId: 'formItem99329a',
      renderKey: 1769571745124,
    },
    style: {
      width: '100%',
    },
    type: 'currUser',
    readonly: true,
    placeholder: '',
    __vModel__: 'F_CreatorUserId',
  },
  {
    label: '生成时间',
    labelI18nCode: '',
    prop: 'F_CreatorTime',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'createTime',
    sortable: false,
    width: null,
    id: 'F_CreatorTime',
    fullName: '生成时间',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'createTime',
      label: '生成时间',
      showLabel: true,
      tag: 'JnpfOpenData',
      tagIcon: 'icon-ym icon-ym-generator-createtime',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      layout: 'colFormItem',
      required: false,
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_maint_device_qr',
      noShow: true,
      formId: 'formItemd213a4',
      renderKey: 1769571745430,
    },
    style: {
      width: '100%',
    },
    type: 'currTime',
    readonly: true,
    placeholder: '',
    __vModel__: 'F_CreatorTime',
  },
];
export default columnList;
