const searchList = [
  {
    label: '商品',
    labelI18nCode: '',
    prop: 'F_GoodsId',
    jnpfKey: 'select',
    searchType: 1,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_GoodsId',
    fullName: '商品',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '商品',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_goods_inventory',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dynamic',
      dictionaryType: '',
      propsUrl: '2012085692393459712',
      propsName: '弹窗获取商品列表（可传合同ID）',
      useCache: true,
      templateJson: [
        {
          id: 'b6217b',
          field: 'contractId',
          dataType: 'varchar',
          defaultValue: '',
          required: 0,
          fieldName: '合同ID',
          relationField: '',
          sourceType: 3,
        },
      ],
      formId: 'formItem8ae28a',
      renderKey: 1769152534785,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [
      {
        id: '2016472595339284480',
        F_GoodsNo: 'SP202601280001',
        F_GoodsName: '1.28商品测试1-SP202601280001',
        F_CategoryId: '0.8',
        F_Unit: '台',
        F_SalePrice: null,
        F_CostPrice: null,
        F_CommissionFixed: null,
        F_Source: null,
        F_OutsourcePrice: null,
        F_SupplierId: null,
        F_Specification: '2*3',
        F_InspectRule: '检查',
        F_StockUpperLimit: null,
        F_StockLowerLimit: null,
        F_Image: null,
        F_AttachmentUrl: null,
        F_CreatorTime: '2026-01-28T19:25:05Z',
        F_CreatorUserId: null,
        F_Remark: '备注',
        F_InventoryNum: 0,
        F_CreatorOrganizeId: null,
      },
      {
        id: '2015738620983513088',
        F_GoodsNo: 'SP202601260003',
        F_GoodsName: '测试商品2-SP202601260003',
        F_CategoryId: '1.0',
        F_Unit: '台',
        F_SalePrice: null,
        F_CostPrice: null,
        F_CommissionFixed: null,
        F_Source: null,
        F_OutsourcePrice: null,
        F_SupplierId: null,
        F_Specification: '1',
        F_InspectRule: '3',
        F_StockUpperLimit: null,
        F_StockLowerLimit: null,
        F_Image: null,
        F_AttachmentUrl: null,
        F_CreatorTime: '2026-01-26T18:48:32Z',
        F_CreatorUserId: null,
        F_Remark: '备注',
        F_InventoryNum: 21,
        F_CreatorOrganizeId: null,
      },
      {
        id: '2015735688410042368',
        F_GoodsNo: 'SP202601260002',
        F_GoodsName: '商品一-SP202601260002',
        F_CategoryId: '明装柜/1.0-1.2',
        F_Unit: '台',
        F_SalePrice: null,
        F_CostPrice: null,
        F_CommissionFixed: null,
        F_Source: null,
        F_OutsourcePrice: null,
        F_SupplierId: null,
        F_Specification: '个',
        F_InspectRule: '无',
        F_StockUpperLimit: null,
        F_StockLowerLimit: null,
        F_Image: null,
        F_AttachmentUrl: null,
        F_CreatorTime: '2026-01-26T18:36:53Z',
        F_CreatorUserId: null,
        F_Remark: '测试',
        F_InventoryNum: 27,
        F_CreatorOrganizeId: null,
      },
      {
        id: '2015734210689634304',
        F_GoodsNo: 'SP202601260001',
        F_GoodsName: '测试商品-SP202601260001',
        F_CategoryId: '0.8-1.0',
        F_Unit: '个',
        F_SalePrice: null,
        F_CostPrice: null,
        F_CommissionFixed: null,
        F_Source: null,
        F_OutsourcePrice: null,
        F_SupplierId: null,
        F_Specification: '3',
        F_InspectRule: '5',
        F_StockUpperLimit: null,
        F_StockLowerLimit: null,
        F_Image: null,
        F_AttachmentUrl: null,
        F_CreatorTime: '2026-01-26T18:31:01Z',
        F_CreatorUserId: null,
        F_Remark: '2备注',
        F_InventoryNum: 8,
        F_CreatorOrganizeId: null,
      },
      {
        id: '2014578461892546560',
        F_GoodsNo: 'SP202601230003',
        F_GoodsName: 'JG3-SP202601230003',
        F_CategoryId: '明装柜/1.0-1.2',
        F_Unit: '个',
        F_SalePrice: null,
        F_CostPrice: null,
        F_CommissionFixed: null,
        F_Source: null,
        F_OutsourcePrice: null,
        F_SupplierId: null,
        F_Specification: null,
        F_InspectRule: null,
        F_StockUpperLimit: null,
        F_StockLowerLimit: null,
        F_Image: null,
        F_AttachmentUrl: null,
        F_CreatorTime: '2026-01-23T13:58:29Z',
        F_CreatorUserId: null,
        F_Remark: null,
        F_InventoryNum: 31,
        F_CreatorOrganizeId: null,
      },
      {
        id: '2014578381563236352',
        F_GoodsNo: 'SP202601230002',
        F_GoodsName: 'JG2-SP202601230002',
        F_CategoryId: '明装柜/1.0-1.2',
        F_Unit: '台',
        F_SalePrice: null,
        F_CostPrice: null,
        F_CommissionFixed: null,
        F_Source: null,
        F_OutsourcePrice: null,
        F_SupplierId: null,
        F_Specification: null,
        F_InspectRule: null,
        F_StockUpperLimit: null,
        F_StockLowerLimit: null,
        F_Image: null,
        F_AttachmentUrl: null,
        F_CreatorTime: '2026-01-23T13:58:09Z',
        F_CreatorUserId: null,
        F_Remark: null,
        F_InventoryNum: 38,
        F_CreatorOrganizeId: null,
      },
      {
        id: '2014578308263579648',
        F_GoodsNo: 'SP202601230001',
        F_GoodsName: 'JG1-SP202601230001',
        F_CategoryId: '明装柜/1.0-1.2',
        F_Unit: '个',
        F_SalePrice: null,
        F_CostPrice: null,
        F_CommissionFixed: null,
        F_Source: null,
        F_OutsourcePrice: null,
        F_SupplierId: null,
        F_Specification: null,
        F_InspectRule: null,
        F_StockUpperLimit: null,
        F_StockLowerLimit: null,
        F_Image: null,
        F_AttachmentUrl: null,
        F_CreatorTime: '2026-01-23T13:57:52Z',
        F_CreatorUserId: null,
        F_Remark: null,
        F_InventoryNum: 30,
        F_CreatorOrganizeId: null,
      },
      {
        id: '2013948044566990848',
        F_GoodsNo: 'SP202601210001',
        F_GoodsName: '披萨-SP202601210001',
        F_CategoryId: '0.8-1.0',
        F_Unit: null,
        F_SalePrice: null,
        F_CostPrice: null,
        F_CommissionFixed: null,
        F_Source: null,
        F_OutsourcePrice: null,
        F_SupplierId: null,
        F_Specification: null,
        F_InspectRule: null,
        F_StockUpperLimit: null,
        F_StockLowerLimit: null,
        F_Image: null,
        F_AttachmentUrl: null,
        F_CreatorTime: '2026-01-21T20:13:25Z',
        F_CreatorUserId: null,
        F_Remark: null,
        F_InventoryNum: 18,
        F_CreatorOrganizeId: null,
      },
      {
        id: '2011713069100699648',
        F_GoodsNo: 'SP20260115160001',
        F_GoodsName: 'CS2-SP20260115160001',
        F_CategoryId: '2.0-3.0',
        F_Unit: '个',
        F_SalePrice: null,
        F_CostPrice: null,
        F_CommissionFixed: null,
        F_Source: null,
        F_OutsourcePrice: null,
        F_SupplierId: null,
        F_Specification: null,
        F_InspectRule: null,
        F_StockUpperLimit: null,
        F_StockLowerLimit: null,
        F_Image: null,
        F_AttachmentUrl: null,
        F_CreatorTime: '2026-01-15T16:12:26Z',
        F_CreatorUserId: null,
        F_Remark: null,
        F_InventoryNum: 3,
        F_CreatorOrganizeId: null,
      },
      {
        id: '2011713010275586048',
        F_GoodsNo: 'sp20260115160001',
        F_GoodsName: 'CS1-sp20260115160001',
        F_CategoryId: null,
        F_Unit: '台',
        F_SalePrice: null,
        F_CostPrice: null,
        F_CommissionFixed: null,
        F_Source: null,
        F_OutsourcePrice: null,
        F_SupplierId: null,
        F_Specification: null,
        F_InspectRule: null,
        F_StockUpperLimit: null,
        F_StockLowerLimit: null,
        F_Image: null,
        F_AttachmentUrl: null,
        F_CreatorTime: '2026-01-15T16:12:12Z',
        F_CreatorUserId: null,
        F_Remark: null,
        F_InventoryNum: 53,
        F_CreatorOrganizeId: null,
      },
      {
        id: '2010976325753507840',
        F_GoodsNo: 'SP20260115160003',
        F_GoodsName: '苹果-SP20260115160003',
        F_CategoryId: '40角钢',
        F_Unit: '个',
        F_SalePrice: null,
        F_CostPrice: null,
        F_CommissionFixed: null,
        F_Source: null,
        F_OutsourcePrice: null,
        F_SupplierId: null,
        F_Specification: '1*1',
        F_InspectRule: '无',
        F_StockUpperLimit: null,
        F_StockLowerLimit: null,
        F_Image: null,
        F_AttachmentUrl: null,
        F_CreatorTime: '2026-01-13T07:24:53Z',
        F_CreatorUserId: null,
        F_Remark: '测试备注',
        F_InventoryNum: 19,
        F_CreatorOrganizeId: null,
      },
      {
        id: '2008839754363310080',
        F_GoodsNo: 'sp20260107170001',
        F_GoodsName: '木材-sp20260107170001',
        F_CategoryId: null,
        F_Unit: '台',
        F_SalePrice: null,
        F_CostPrice: null,
        F_CommissionFixed: null,
        F_Source: null,
        F_OutsourcePrice: null,
        F_SupplierId: null,
        F_Specification: null,
        F_InspectRule: null,
        F_StockUpperLimit: null,
        F_StockLowerLimit: null,
        F_Image: null,
        F_AttachmentUrl: null,
        F_CreatorTime: '2026-01-07T17:54:54Z',
        F_CreatorUserId: null,
        F_Remark: null,
        F_InventoryNum: 17,
        F_CreatorOrganizeId: null,
      },
    ],
    props: {
      label: 'F_GoodsName',
      value: 'id',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_GoodsId',
  },
  {
    label: '仓库',
    labelI18nCode: '',
    prop: 'F_WarehouseId',
    jnpfKey: 'input',
    searchType: 2,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_WarehouseId',
    fullName: '仓库',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '仓库',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_customer',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItemd5ff29',
      renderKey: 1767858434670,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_WarehouseId',
  },
  // {
  //   label: '仓库',
  //   labelI18nCode: '',
  //   prop: 'F_WarehouseId',
  //   jnpfKey: 'cascader',
  //   searchType: 1,
  //   searchMultiple: false,
  //   isKeyword: false,
  //   id: 'F_WarehouseId',
  //   fullName: '仓库',
  //   fullNameI18nCode: [''],
  //   __config__: {
  //     jnpfKey: 'cascader',
  //     label: '仓库',
  //     tipLabel: '',
  //     showLabel: true,
  //     tag: 'JnpfCascader',
  //     tagIcon: 'icon-ym icon-ym-generator-cascader',
  //     tableAlign: 'left',
  //     tableFixed: 'none',
  //     className: [],
  //     defaultValue: [],
  //     required: false,
  //     layout: 'colFormItem',
  //     span: 24,
  //     dragDisabled: false,
  //     visibility: ['pc', 'app'],
  //     tableName: 'a_goods_inventory',
  //     noShow: false,
  //     regList: [],
  //     trigger: 'change',
  //     dataType: 'dynamic',
  //     propsUrl: '2021045201115680768',
  //     propsName: '仓库管理（树状）',
  //     useCache: true,
  //     templateJson: [],
  //     dictionaryType: '',
  //     formId: 'formItemdd74d3',
  //     renderKey: 1772420282348,
  //   },
  //   on: {
  //     change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
  //     blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
  //   },
  //   style: {
  //     width: '100%',
  //   },
  //   options: [
  //     {
  //       F_Id: '2021048550619746304',
  //       F_ParentId: null,
  //       F_Name: '测试储存2级',
  //       F_Address: '002',
  //       _realParentId: null,
  //       children: [],
  //     },
  //     {
  //       F_Id: '2014233789731049472',
  //       F_ParentId: null,
  //       F_Name: '金家林5G仓',
  //       F_Address: '金家林',
  //       _realParentId: null,
  //       children: [
  //         {
  //           F_Id: '2026473367191818240',
  //           F_ParentId: '["2014233789731049472"]',
  //           F_Name: '5G仓库2级',
  //           F_Address: '001',
  //           _realParentId: '2014233789731049472',
  //           children: [
  //             {
  //               F_Id: '2026483124422184960',
  //               F_ParentId: '["2014233789731049472","2026473367191818240"]',
  //               F_Name: '5G仓库3级',
  //               F_Address: '测试',
  //               _realParentId: '2026473367191818240',
  //               children: [],
  //             },
  //           ],
  //         },
  //       ],
  //     },
  //   ],
  //   props: {
  //     value: 'F_Id',
  //     label: 'F_Name',
  //     children: 'children',
  //   },
  //   placeholder: '请选择',
  //   disabled: false,
  //   clearable: true,
  //   filterable: false,
  //   multiple: false,
  //   __vModel__: 'F_WarehouseId',
  // },
];
export default searchList;
