const columnList = [
  {
    label: '工序',
    labelI18nCode: '',
    prop: 'F_ProcessName',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'select',
    sortable: false,
    width: 120,
    resizable: true,
    id: 'F_ProcessName',
    fullName: '工序',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '工序',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_task',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dynamic',
      dictionaryType: '',
      propsUrl: '2012092092830060544',
      propsName: '弹窗获取工序列表',
      useCache: true,
      templateJson: [],
      formId: 'formIteme07d23',
      renderKey: 1768976206980,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [],
    props: {
      label: 'F_ProcessName',
      value: 'id',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_ProcessName',
  },
  {
    label: '加工单',
    labelI18nCode: '',
    prop: 'F_ProcessingId',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'select',
    sortable: false,
    width: 150,
    resizable: true,
    id: 'F_ProcessingId',
    fullName: '加工单',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '加工单',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_task',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dynamic',
      dictionaryType: '',
      propsUrl: '2013860549426810880',
      propsName: '加工单信息',
      useCache: true,
      templateJson: [],
      formId: 'formItem2ff0b0',
      renderKey: 1768976206811,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [],
    props: {
      label: 'F_ProcessNo',
      value: 'F_Id',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_ProcessingId',
  },

  {
    label: '商品名',
    labelI18nCode: '',
    prop: 'F_GoodsName',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'select',
    sortable: false,
    width: 120,
    resizable: true,
    id: 'F_GoodsName',
    fullName: '商品名',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '商品名',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_task',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dynamic',
      dictionaryType: '',
      propsUrl: '2013860549426810880',
      propsName: '加工单信息',
      useCache: true,
      templateJson: [],
      formId: 'formItem2ff0b0',
      renderKey: 1768976206811,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [],
    props: {
      label: 'F_ProcessNo',
      value: 'F_Id',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_GoodsName',
  },
  {
    label: '商品编号',
    labelI18nCode: '',
    prop: 'F_GoodsNo',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'select',
    sortable: false,
    width: 150,
    resizable: true,
    id: 'F_GoodsNo',
    fullName: '商品编号',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '商品编号',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_task',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dynamic',
      dictionaryType: '',
      propsUrl: '2013860549426810880',
      propsName: '加工单信息',
      useCache: true,
      templateJson: [],
      formId: 'formItem2ff0b0',
      renderKey: 1768976206811,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [],
    props: {
      label: 'F_ProcessNo',
      value: 'F_Id',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_GoodsNo',
  },
  {
    label: '商品规格',
    labelI18nCode: '',
    prop: 'F_Specification',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'select',
    sortable: false,
    width: 100,
    resizable: true,
    id: 'F_Specification',
    fullName: '商品规格',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '商品规格',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_task',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dynamic',
      dictionaryType: '',
      propsUrl: '2013860549426810880',
      propsName: '加工单信息',
      useCache: true,
      templateJson: [],
      formId: 'formItem2ff0b0',
      renderKey: 1768976206811,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [],
    props: {
      label: 'F_ProcessNo',
      value: 'F_Id',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_Specification',
  },

  {
    label: '任务类型',
    labelI18nCode: '',
    prop: 'F_TaskType',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'select',
    sortable: false,
    width: null,
    resizable: true,
    id: 'F_TaskType',
    fullName: '任务类型',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '任务类型',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_task',
      noShow: true,
      regList: [],
      trigger: 'change',
      dataType: 'dictionary',
      dictionaryType: '2013859641523572736',
      propsUrl: '',
      propsName: '',
      useCache: true,
      templateJson: [],
      formId: 'formItem556ea8',
      renderKey: 1768976373662,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [],
    props: {
      label: 'fullName',
      value: 'enCode',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_TaskType',
  },

  {
    label: '工序编号',
    labelI18nCode: '',
    prop: 'F_ProcessCode',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'select',
    sortable: false,
    width: null,
    resizable: true,
    id: 'F_ProcessCode',
    fullName: '工序编号',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '工序编号',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_task',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dynamic',
      dictionaryType: '',
      propsUrl: '2013860549426810880',
      propsName: '加工单信息',
      useCache: true,
      templateJson: [],
      formId: 'formItem2ff0b0',
      renderKey: 1768976206811,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [],
    props: {
      label: 'F_ProcessNo',
      value: 'F_Id',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_ProcessCode',
  },
  {
    label: '工序计划开始',
    labelI18nCode: '',
    prop: 'F_PlanStartDate',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'select',
    sortable: false,
    width: 150,
    resizable: true,
    id: 'F_PlanStartDate',
    fullName: '工序计划开始',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '工序计划开始',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_task',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dynamic',
      dictionaryType: '',
      propsUrl: '2013860549426810880',
      propsName: '加工单信息',
      useCache: true,
      templateJson: [],
      formId: 'formItem2ff0b0',
      renderKey: 1768976206811,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [],
    props: {
      label: 'F_ProcessNo',
      value: 'F_Id',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_PlanStartDate',
  },
  {
    label: '工序计划结束',
    labelI18nCode: '',
    prop: 'F_PlanEndDate',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'select',
    sortable: false,
    width: 150,
    resizable: true,
    id: 'F_PlanEndDate',
    fullName: '工序计划结束',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '工序计划结束',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_task',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dynamic',
      dictionaryType: '',
      propsUrl: '2013860549426810880',
      propsName: '加工单信息',
      useCache: true,
      templateJson: [],
      formId: 'formItem2ff0b0',
      renderKey: 1768976206811,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [],
    props: {
      label: 'F_ProcessNo',
      value: 'F_Id',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_PlanEndDate',
  },
  {
    label: '生产数量',
    labelI18nCode: '',
    prop: 'F_ProdQty',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'inputNumber',
    sortable: false,
    width: null,
    resizable: true,
    id: 'F_ProdQty',
    fullName: '生产数量',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'inputNumber',
      label: '生产数量',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInputNumber',
      tagIcon: 'icon-ym icon-ym-generator-number',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_task',
      noShow: false,
      regList: [],
      trigger: ['blur', 'change'],
      formId: 'formItem21c87e',
      renderKey: 1768976310087,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    min: 1,
    controls: false,
    addonBefore: '',
    addonAfter: '',
    thousands: false,
    isAmountChinese: false,
    step: 1,
    precision: 0,
    disabled: false,
    __vModel__: 'F_ProdQty',
  },
  {
    label: '任务状态',
    labelI18nCode: '',
    prop: 'F_TaskStatus',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'select',
    sortable: false,
    width: null,
    resizable: true,
    id: 'F_TaskStatus',
    fullName: '任务状态',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '任务状态',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_task',
      noShow: true,
      regList: [],
      trigger: 'change',
      dataType: 'dictionary',
      dictionaryType: '2013859706900189184',
      propsUrl: '',
      propsName: '',
      useCache: true,
      templateJson: [],
      formId: 'formItembd88b3',
      renderKey: 1768976314300,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [],
    props: {
      label: 'fullName',
      value: 'enCode',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_TaskStatus',
  },

  {
    label: '任务暂停原因',
    labelI18nCode: '',
    prop: 'F_Reason',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'select',
    sortable: false,
    width: 180,
    resizable: true,
    id: 'F_Reason',
    fullName: '任务暂停原因',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '任务暂停原因',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_task',
      noShow: true,
      regList: [],
      trigger: 'change',
      dataType: 'dictionary',
      dictionaryType: '2013859706900189184',
      propsUrl: '',
      propsName: '',
      useCache: true,
      templateJson: [],
      formId: 'formItembd88b3',
      renderKey: 1768976314300,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [],
    props: {
      label: 'fullName',
      value: 'enCode',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_Reason',
  },
  {
    label: '任务开始时间',
    labelI18nCode: '',
    prop: 'F_StartDate',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'select',
    sortable: false,
    width: 150,
    resizable: true,
    id: 'F_StartDate',
    fullName: '任务开始时间',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '任务开始时间',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_task',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dynamic',
      dictionaryType: '',
      propsUrl: '2013860549426810880',
      propsName: '加工单信息',
      useCache: true,
      templateJson: [],
      formId: 'formItem2ff0b0',
      renderKey: 1768976206811,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [],
    props: {
      label: 'F_ProcessNo',
      value: 'F_Id',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_StartDate',
  },
  {
    label: '任务结束时间',
    labelI18nCode: '',
    prop: 'F_EndDate',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'select',
    sortable: false,
    width: 150,
    resizable: true,
    id: 'F_EndDate',
    fullName: '任务结束时间',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '任务结束时间',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_task',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dynamic',
      dictionaryType: '',
      propsUrl: '2013860549426810880',
      propsName: '加工单信息',
      useCache: true,
      templateJson: [],
      formId: 'formItem2ff0b0',
      renderKey: 1768976206811,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [],
    props: {
      label: 'F_ProcessNo',
      value: 'F_Id',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_EndDate',
  },

  {
    label: '生产人员',
    labelI18nCode: '',
    prop: 'F_ProdUserIds',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'select',
    sortable: false,
    width: 180,
    resizable: true,
    id: 'F_ProdUserIds',
    fullName: '生产人员',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '生产人员',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_task',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dynamic',
      dictionaryType: '',
      propsUrl: '2013860549426810880',
      propsName: '加工单信息',
      useCache: true,
      templateJson: [],
      formId: 'formItem2ff0b0',
      renderKey: 1768976206811,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [],
    props: {
      label: 'F_ProcessNo',
      value: 'F_Id',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_ProdUserIds',
  },

  {
    label: '生产派工',
    labelI18nCode: '',
    prop: 'F_ProdDispatch',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'select',
    sortable: false,
    width: 180,
    resizable: true,
    id: 'F_ProdDispatch',
    fullName: '生产派工',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '生产派工',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: [],
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_task',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'static',
      dictionaryType: '',
      propsUrl: '',
      propsName: '',
      useCache: true,
      templateJson: [],
      formId: 'formIteme61a66',
      renderKey: 1768976282030,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [
      {
        fullName: '选项一',
        id: '1',
      },
      {
        fullName: '选项二',
        id: '2',
      },
    ],
    props: {
      label: 'fullName',
      value: 'id',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: true,
    __vModel__: 'F_ProdDispatch',
  },

  {
    label: '质检人员',
    labelI18nCode: '',
    prop: 'F_QcUserIds',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'select',
    sortable: false,
    width: 180,
    resizable: true,
    id: 'F_QcUserIds',
    fullName: '质检人员',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '质检人员',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_task',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dynamic',
      dictionaryType: '',
      propsUrl: '2013860549426810880',
      propsName: '加工单信息',
      useCache: true,
      templateJson: [],
      formId: 'formItem2ff0b0',
      renderKey: 1768976206811,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [],
    props: {
      label: 'F_ProcessNo',
      value: 'F_Id',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_QcUserIds',
  },

  {
    label: '质检派工',
    labelI18nCode: '',
    prop: 'F_QcDispatch',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'select',
    sortable: false,
    width: 180,
    resizable: true,
    id: 'F_QcDispatch',
    fullName: '质检派工',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '质检派工',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: [],
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_task',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'static',
      dictionaryType: '',
      propsUrl: '',
      propsName: '',
      useCache: true,
      templateJson: [],
      formId: 'formItem141287',
      renderKey: 1768976282177,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [
      {
        fullName: '选项一',
        id: '1',
      },
      {
        fullName: '选项二',
        id: '2',
      },
    ],
    props: {
      label: 'fullName',
      value: 'id',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: true,
    __vModel__: 'F_QcDispatch',
  },
  {
    label: '不良品项',
    labelI18nCode: '',
    prop: 'F_DefectIds',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'select',
    sortable: false,
    width: 150,
    resizable: true,
    id: 'F_DefectIds',
    fullName: '不良品项',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '不良品项',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: [],
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_task',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'static',
      dictionaryType: '',
      propsUrl: '',
      propsName: '',
      useCache: true,
      templateJson: [],
      formId: 'formItem141287',
      renderKey: 1768976282177,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [
      {
        fullName: '选项一',
        id: '1',
      },
      {
        fullName: '选项二',
        id: '2',
      },
    ],
    props: {
      label: 'fullName',
      value: 'id',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: true,
    __vModel__: 'F_DefectIds',
  },
  {
    label: '备注',
    labelI18nCode: '',
    prop: 'F_Description',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'textarea',
    sortable: false,
    width: 180,
    resizable: true,
    id: 'F_Description',
    fullName: '备注',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'textarea',
      label: '备注',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfTextarea',
      tagIcon: 'icon-ym icon-ym-generator-textarea',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_task',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItem871081',
      renderKey: 1768976319232,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    autoSize: {
      minRows: 4,
      maxRows: 4,
    },
    clearable: true,
    maxlength: null,
    showCount: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_Description',
  },
  {
    label: '创建时间',
    labelI18nCode: '',
    prop: 'F_CreatorTime',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'createTime',
    sortable: false,
    width: 150,
    resizable: true,
    id: 'F_CreatorTime',
    fullName: '创建时间',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'createTime',
      label: '创建时间',
      showLabel: true,
      tag: 'JnpfOpenData',
      tagIcon: 'icon-ym icon-ym-generator-createtime',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      layout: 'colFormItem',
      required: false,
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_task',
      noShow: true,
      formId: 'formItem3a6761',
      renderKey: 1768976321319,
    },
    style: {
      width: '100%',
    },
    type: 'currTime',
    readonly: true,
    placeholder: '',
    __vModel__: 'F_CreatorTime',
  },
];
export default columnList;
