const searchList = [
  {
    label: '加工单',
    labelI18nCode: '',
    prop: 'F_ProcessingId',
    jnpfKey: 'select',
    searchType: 1,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_ProcessingId',
    fullName: '加工单',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '加工单',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_task',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dynamic',
      dictionaryType: '',
      propsUrl: '2013860549426810880',
      propsName: '加工单信息',
      useCache: true,
      templateJson: [],
      formId: 'formItem2ff0b0',
      renderKey: 1768976206811,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [
      {
        F_Id: '2013898279183585280',
        F_ProcessNo: 'JG2026012116001',
      },
      {
        F_Id: '2013931751335923712',
        F_ProcessNo: 'JG2026012119001',
      },
      {
        F_Id: '2013937016802250752',
        F_ProcessNo: 'JG2026012119002',
      },
    ],
    props: {
      label: 'F_ProcessNo',
      value: 'F_Id',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_ProcessingId',
  },
  {
    label: '工序',
    labelI18nCode: '',
    prop: 'F_ProcessId',
    jnpfKey: 'select',
    searchType: 1,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_ProcessId',
    fullName: '工序',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '工序',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_task',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dynamic',
      dictionaryType: '',
      propsUrl: '2012092092830060544',
      propsName: '弹窗获取工序列表',
      useCache: true,
      templateJson: [],
      formId: 'formIteme07d23',
      renderKey: 1768976206980,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [
      {
        id: '2012102285055889408',
        F_ProcessName: '图纸排版',
        F_ProcessCode: '02',
        F_WorkshopId: null,
        F_PriceType: null,
        F_ProdUserIds: '超级管理员,001',
        F_DefectIds: 'BLPX2026011516001|不良品项01',
        F_QcUserIds: '超级管理员,002',
        F_MachineId: null,
        F_Line: null,
        F_ReportUnit: null,
        F_UnitRatio: null,
        F_WagePrice: null,
        F_IsOutsource: '0',
        F_IsQc: '1',
        F_DefectHandle: '1',
        F_DefectHandleName: '是',
        F_StdHour: null,
        F_State: null,
        F_TaskTimer: '是',
        F_Description: null,
        F_CreatorTime: '2026-01-16T17:59:02Z',
      },
      {
        id: '2011743414118387712',
        F_ProcessName: '图纸设计',
        F_ProcessCode: '01',
        F_WorkshopId: null,
        F_PriceType: null,
        F_ProdUserIds: '超级管理员,001,002',
        F_DefectIds: 'BLPX2026011516002|不良品项02,BLPX2026011516001|不良品项01',
        F_QcUserIds: '超级管理员,001,002',
        F_MachineId: null,
        F_Line: null,
        F_ReportUnit: null,
        F_UnitRatio: null,
        F_WagePrice: null,
        F_IsOutsource: '0',
        F_IsQc: '1',
        F_DefectHandle: '1',
        F_DefectHandleName: '是',
        F_StdHour: null,
        F_State: null,
        F_TaskTimer: '是',
        F_Description: '测试',
        F_CreatorTime: '2026-01-15T18:13:00Z',
      },
    ],
    props: {
      label: 'F_ProcessName',
      value: 'id',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_ProcessId',
  },
  {
    label: '计划开始',
    labelI18nCode: '',
    prop: 'F_PlanStartDate',
    jnpfKey: 'datePicker',
    value: [],
    searchType: 3,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_PlanStartDate',
    fullName: '计划开始',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'datePicker',
      label: '计划开始',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfDatePicker',
      tagIcon: 'icon-ym icon-ym-generator-date',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      defaultCurrent: false,
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_task',
      noShow: false,
      regList: [],
      trigger: 'change',
      startTimeRule: false,
      startTimeType: 1,
      startTimeTarget: 1,
      startTimeValue: null,
      startRelationField: '',
      endTimeRule: false,
      endTimeType: 1,
      endTimeTarget: 1,
      endTimeValue: null,
      endRelationField: '',
      formId: 'formItem524adb',
      renderKey: 1768976210395,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    format: 'yyyy-MM-dd',
    startTime: null,
    endTime: null,
    disabled: false,
    clearable: true,
    __vModel__: 'F_PlanStartDate',
  },
  {
    label: '计划结束',
    labelI18nCode: '',
    prop: 'F_PlanEndDate',
    jnpfKey: 'datePicker',
    value: [],
    searchType: 3,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_PlanEndDate',
    fullName: '计划结束',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'datePicker',
      label: '计划结束',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfDatePicker',
      tagIcon: 'icon-ym icon-ym-generator-date',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      defaultCurrent: false,
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_task',
      noShow: false,
      regList: [],
      trigger: 'change',
      startTimeRule: false,
      startTimeType: 1,
      startTimeTarget: 1,
      startTimeValue: null,
      startRelationField: '',
      endTimeRule: false,
      endTimeType: 1,
      endTimeTarget: 1,
      endTimeValue: null,
      endRelationField: '',
      formId: 'formItem697c01',
      renderKey: 1768976210573,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    format: 'yyyy-MM-dd',
    startTime: null,
    endTime: null,
    disabled: false,
    clearable: true,
    __vModel__: 'F_PlanEndDate',
  },
  {
    label: '生产派工',
    labelI18nCode: '',
    prop: 'F_ProdDispatch',
    jnpfKey: 'userSelect',
    searchType: 1,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_ProdDispatch',
    fullName: '生产派工',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'userSelect',
      label: '生产派工',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfUserSelect',
      tagIcon: 'icon-ym icon-ym-generator-user',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      defaultCurrent: false,
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_task',
      noShow: false,
      regList: [],
      trigger: 'change',
      formId: 'formItem3089c0',
      renderKey: 1769046062426,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    selectType: 'all',
    ableIds: [],
    ableRelationIds: [],
    relationField: '',
    multiple: false,
    clearable: true,
    disabled: false,
    __vModel__: 'F_ProdDispatch',
  },
  {
    label: '质检派工',
    labelI18nCode: '',
    prop: 'F_QcDispatch',
    jnpfKey: 'userSelect',
    searchType: 1,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_QcDispatch',
    fullName: '质检派工',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'userSelect',
      label: '质检派工',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfUserSelect',
      tagIcon: 'icon-ym icon-ym-generator-user',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      defaultCurrent: false,
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_task',
      noShow: false,
      regList: [],
      trigger: 'change',
      formId: 'formItem6bb27b',
      renderKey: 1769046060630,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    selectType: 'all',
    ableIds: [],
    ableRelationIds: [],
    relationField: '',
    multiple: false,
    clearable: true,
    disabled: false,
    __vModel__: 'F_QcDispatch',
  },
];
export default searchList;
