const searchList = [
  {
    label: '加工单',
    labelI18nCode: '',
    prop: 'F_ProcessingId',
    jnpfKey: 'select',
    searchType: 1,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_ProcessingId',
    fullName: '加工单',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '加工单',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_task',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dynamic',
      dictionaryType: '',
      propsUrl: '2013860549426810880',
      propsName: '加工单信息',
      useCache: true,
      templateJson: [],
      formId: 'formItem2ff0b0',
      renderKey: 1768976206811,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [
      {
        F_Id: '2013898279183585280',
        F_ProcessNo: 'JG2026012116001',
      },
      {
        F_Id: '2013931751335923712',
        F_ProcessNo: 'JG2026012119001',
      },
      {
        F_Id: '2013937016802250752',
        F_ProcessNo: 'JG2026012119002',
      },
    ],
    props: {
      label: 'F_ProcessNo',
      value: 'F_Id',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_ProcessingId',
  },
  {
    label: '工序',
    labelI18nCode: '',
    prop: 'F_ProcessId',
    jnpfKey: 'select',
    searchType: 1,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_ProcessId',
    fullName: '工序',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '工序',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_task',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dynamic',
      dictionaryType: '',
      propsUrl: '2012092092830060544',
      propsName: '弹窗获取工序列表',
      useCache: true,
      templateJson: [],
      formId: 'formIteme07d23',
      renderKey: 1768976206980,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [
      {
        id: '2012102285055889408',
        F_ProcessName: '图纸排版',
        F_ProcessCode: '02',
        F_WorkshopId: null,
        F_PriceType: null,
        F_ProdUserIds: '超级管理员,001',
        F_DefectIds: 'BLPX2026011516001|不良品项01',
        F_QcUserIds: '超级管理员,002',
        F_MachineId: null,
        F_Line: null,
        F_ReportUnit: null,
        F_UnitRatio: null,
        F_WagePrice: null,
        F_IsOutsource: '0',
        F_IsQc: '1',
        F_DefectHandle: '1',
        F_DefectHandleName: '是',
        F_StdHour: null,
        F_State: null,
        F_TaskTimer: '是',
        F_Description: null,
        F_CreatorTime: '2026-01-16T17:59:02Z',
      },
      {
        id: '2011743414118387712',
        F_ProcessName: '图纸设计',
        F_ProcessCode: '01',
        F_WorkshopId: null,
        F_PriceType: null,
        F_ProdUserIds: '超级管理员,001,002',
        F_DefectIds: 'BLPX2026011516002|不良品项02,BLPX2026011516001|不良品项01',
        F_QcUserIds: '超级管理员,001,002',
        F_MachineId: null,
        F_Line: null,
        F_ReportUnit: null,
        F_UnitRatio: null,
        F_WagePrice: null,
        F_IsOutsource: '0',
        F_IsQc: '1',
        F_DefectHandle: '1',
        F_DefectHandleName: '是',
        F_StdHour: null,
        F_State: null,
        F_TaskTimer: '是',
        F_Description: '测试',
        F_CreatorTime: '2026-01-15T18:13:00Z',
      },
    ],
    props: {
      label: 'F_ProcessName',
      value: 'id',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_ProcessId',
  },
  {
    label: '生产人员',
    labelI18nCode: '',
    prop: 'F_ProdUserId',
    jnpfKey: 'userSelect',
    value: [],
    searchType: 1,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_ProdUserId',
    fullName: '生产人员',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'userSelect',
      label: '生产人员',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfUserSelect',
      tagIcon: 'icon-ym icon-ym-generator-user',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: [],
      defaultCurrent: false,
      required: true,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_report',
      noShow: false,
      regList: [],
      trigger: 'change',
      formId: 'formItem0425dc',
      renderKey: 1769067564681,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    selectType: 'all',
    ableIds: [],
    ableRelationIds: [],
    relationField: '',
    multiple: true,
    clearable: true,
    disabled: false,
    __vModel__: 'F_ProdUserId',
  },
  {
    label: '良品数',
    labelI18nCode: '',
    prop: 'F_GoodQty',
    jnpfKey: 'inputNumber',
    value: [],
    searchType: 3,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_GoodQty',
    fullName: '良品数',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'inputNumber',
      label: '良品数',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInputNumber',
      tagIcon: 'icon-ym icon-ym-generator-number',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_report',
      noShow: false,
      regList: [],
      trigger: ['blur', 'change'],
      formId: 'formItemb8be59',
      renderKey: 1769067589889,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    min: 0,
    controls: false,
    addonBefore: '',
    addonAfter: '',
    thousands: false,
    isAmountChinese: false,
    step: 1,
    precision: 0,
    disabled: false,
    __vModel__: 'F_GoodQty',
  },
  {
    label: '不良品数',
    labelI18nCode: '',
    prop: 'F_GoodNotQty',
    jnpfKey: 'inputNumber',
    value: [],
    searchType: 3,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_GoodNotQty',
    fullName: '不良品数',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'inputNumber',
      label: '不良品数',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInputNumber',
      tagIcon: 'icon-ym icon-ym-generator-number',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_report',
      noShow: false,
      regList: [],
      trigger: ['blur', 'change'],
      formId: 'formItemadaf25',
      renderKey: 1769069478536,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    min: 0,
    controls: false,
    addonBefore: '',
    addonAfter: '',
    thousands: false,
    isAmountChinese: false,
    step: 1,
    precision: 0,
    disabled: false,
    __vModel__: 'F_GoodNotQty',
  },
  {
    label: '开始时间',
    labelI18nCode: '',
    prop: 'F_StartTime',
    jnpfKey: 'datePicker',
    value: [],
    searchType: 3,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_StartTime',
    fullName: '开始时间',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'datePicker',
      label: '开始时间',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfDatePicker',
      tagIcon: 'icon-ym icon-ym-generator-date',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      defaultCurrent: false,
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_report',
      noShow: false,
      regList: [],
      trigger: 'change',
      startTimeRule: false,
      startTimeType: 1,
      startTimeTarget: 1,
      startTimeValue: null,
      startRelationField: '',
      endTimeRule: false,
      endTimeType: 1,
      endTimeTarget: 1,
      endTimeValue: null,
      endRelationField: '',
      formId: 'formItem3a7c82',
      renderKey: 1769067665449,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    format: 'yyyy-MM-dd',
    startTime: null,
    endTime: null,
    disabled: false,
    clearable: true,
    __vModel__: 'F_StartTime',
  },
  {
    label: '结束时间',
    labelI18nCode: '',
    prop: 'F_EndTime',
    jnpfKey: 'datePicker',
    value: [],
    searchType: 3,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_EndTime',
    fullName: '结束时间',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'datePicker',
      label: '结束时间',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfDatePicker',
      tagIcon: 'icon-ym icon-ym-generator-date',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      defaultCurrent: false,
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_report',
      noShow: false,
      regList: [],
      trigger: 'change',
      startTimeRule: false,
      startTimeType: 1,
      startTimeTarget: 1,
      startTimeValue: null,
      startRelationField: '',
      endTimeRule: false,
      endTimeType: 1,
      endTimeTarget: 1,
      endTimeValue: null,
      endRelationField: '',
      formId: 'formItem63b0af',
      renderKey: 1769067666132,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    format: 'yyyy-MM-dd',
    startTime: null,
    endTime: null,
    disabled: false,
    clearable: true,
    __vModel__: 'F_EndTime',
  },
  {
    label: '不良品项',
    labelI18nCode: '',
    prop: 'tableField579169-F_DefectId',
    jnpfKey: 'select',
    searchType: 1,
    searchMultiple: false,
    isKeyword: false,
    id: 'tableField579169-F_DefectId',
    fullName: '不良品项-不良品项',
    fullNameI18nCode: ['', ''],
    __config__: {
      jnpfKey: 'select',
      label: '不良品项',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_report',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dynamic',
      dictionaryType: '',
      propsUrl: '2011648481097289728',
      propsName: '不良品项',
      useCache: true,
      templateJson: [],
      isSubTable: true,
      parentVModel: 'tableField579169',
      relationTable: 'a_prod_report_defect',
      formId: 'formItemc6f4e7',
      renderKey: 1769069563849,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [
      {
        F_Id: '2011714670574047232',
        F_Name: 'BLPX2026011516003|不良品项03',
      },
      {
        F_Id: '2011714560414846976',
        F_Name: 'BLPX2026011516002|不良品项02',
      },
      {
        F_Id: '2011714536058523648',
        F_Name: 'BLPX2026011516001|不良品项01',
      },
    ],
    props: {
      label: 'F_Name',
      value: 'F_Id',
    },
    placeholder: '',
    clearable: true,
    disabled: true,
    filterable: false,
    multiple: false,
    __vModel__: 'F_DefectId',
  },
  {
    label: '描述',
    labelI18nCode: '',
    prop: 'F_Description',
    jnpfKey: 'textarea',
    searchType: 2,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_Description',
    fullName: '备注',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'textarea',
      label: '备注',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfTextarea',
      tagIcon: 'icon-ym icon-ym-generator-textarea',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_report',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItemb0db50',
      renderKey: 1769067675624,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    autoSize: {
      minRows: 3,
      maxRows: 3,
    },
    clearable: true,
    maxlength: 500,
    showCount: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_Description',
  },
  {
    label: '创建时间',
    labelI18nCode: '',
    prop: 'F_CreatorTime',
    jnpfKey: 'createTime',
    searchType: 3,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_CreatorTime',
    fullName: '创建时间',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'createTime',
      label: '创建时间',
      showLabel: true,
      tag: 'JnpfOpenData',
      tagIcon: 'icon-ym icon-ym-generator-createtime',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      layout: 'colFormItem',
      required: false,
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_report',
      noShow: true,
      formId: 'formItemdfe45d',
      renderKey: 1769067679119,
    },
    style: {
      width: '100%',
    },
    type: 'currTime',
    readonly: true,
    placeholder: '',
    __vModel__: 'F_CreatorTime',
  },
];
export default searchList;
