const searchList = [
  {
    label: '计划编号',
    labelI18nCode: '',
    prop: 'F_PlanNo',
    jnpfKey: 'input',
    searchType: 2,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_PlanNo',
    fullName: '计划编号',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '计划编号',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_pu_plan',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItem686197',
      renderKey: 1768456989493,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请填写，忽略将自动生成',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_PlanNo',
  },
  {
    label: '计划名称',
    labelI18nCode: '',
    prop: 'F_PlanName',
    jnpfKey: 'input',
    searchType: 2,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_PlanName',
    fullName: '计划名称',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '计划名称',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: true,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_pu_plan',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItem5edc20',
      renderKey: 1768457032469,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_PlanName',
  },
  {
    label: '供应商',
    labelI18nCode: '',
    prop: 'F_SupplierId',
    jnpfKey: 'select',
    searchType: 1,
    searchMultiple: true,
    isKeyword: false,
    id: 'F_SupplierId',
    fullName: '供应商',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '供应商',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_pu_plan',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dynamic',
      dictionaryType: '',
      propsUrl: '2008457397298925568',
      propsName: '仓库供应商',
      useCache: true,
      templateJson: [],
      formId: 'formItemb7aeff',
      renderKey: 1768457049219,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [],
    props: {
      label: 'F_SupplierName',
      value: 'F_Id',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: false,
    multiple: false,
    __vModel__: 'F_SupplierId',
  },
  {
    label: '交货日期',
    labelI18nCode: '',
    prop: 'F_DeliveryDate',
    jnpfKey: 'datePicker',
    value: [],
    searchType: 3,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_DeliveryDate',
    fullName: '交货日期',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'datePicker',
      label: '交货日期',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfDatePicker',
      tagIcon: 'icon-ym icon-ym-generator-date',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      defaultCurrent: false,
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_pu_plan',
      noShow: false,
      regList: [],
      trigger: 'change',
      startTimeRule: false,
      startTimeType: 1,
      startTimeTarget: 1,
      startTimeValue: null,
      startRelationField: '',
      endTimeRule: false,
      endTimeType: 1,
      endTimeTarget: 1,
      endTimeValue: null,
      endRelationField: '',
      formId: 'formItemaf0a0f',
      renderKey: 1768457118290,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    format: 'yyyy-MM-dd',
    startTime: null,
    endTime: null,
    disabled: false,
    clearable: true,
    __vModel__: 'F_DeliveryDate',
  },
  {
    label: '负责人',
    labelI18nCode: '',
    prop: 'F_ResponsibleUserId',
    jnpfKey: 'userSelect',
    searchType: 1,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_ResponsibleUserId',
    fullName: '负责人',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'userSelect',
      label: '负责人',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfUserSelect',
      tagIcon: 'icon-ym icon-ym-generator-user',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      defaultCurrent: false,
      required: false,
      layout: 'colFormItem',
      span: 10,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_pu_plan',
      noShow: false,
      regList: [],
      trigger: 'change',
      formId: 'formItem718fcf',
      renderKey: 1775728051130,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    selectType: 'all',
    ableIds: [],
    ableRelationIds: [],
    relationField: '',
    multiple: false,
    clearable: true,
    disabled: false,
    __vModel__: 'F_ResponsibleUserId',
  },
  {
    label: '审核状态',
    labelI18nCode: '',
    prop: 'F_CheckState',
    jnpfKey: 'select',
    searchType: 1,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_CheckState',
    fullName: '审核状态',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '审核状态',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_pu_plan',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dictionary',
      dictionaryType: '2043513064111869952',
      propsUrl: '',
      propsName: '',
      useCache: true,
      templateJson: [],
      formId: 'formItem687ac9',
      renderKey: 1776046483328,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [],
    props: {
      label: 'fullName',
      value: 'enCode',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_CheckState',
  },
];
export default searchList;
