using JNPF.Common.Security;
using JNPF.Common.Models;
using JNPF.example.Entitys.Dto.ACtcContractItem;
using Mapster;
 
namespace JNPF.example.Entitys.Mapper.ACtcContractItem;

public class Mapper : IRegister
{
	public void Register(TypeAdapterConfig config)
	{
		config.ForType<ACtcContractItemCrInput, ACtcContractItemEntity>()
			.Map(dest => dest.F_CustomerId, src => src.F_CustomerId != null ? src.F_CustomerId : null)
			.Map(dest => dest.F_Price, src => src.F_Price != null ? src.F_Price : null)
			.Map(dest => dest.F_SaleQty, src => src.F_SaleQty != null ? src.F_SaleQty : null)
			.Map(dest => dest.F_Discount, src => src.F_Discount != null ? src.F_Discount : null)
			.Map(dest => dest.F_Description, src => src.F_Description != null ? src.F_Description : null)
			.Map(dest => dest.F_DoorPlateThickness, src => src.F_DoorPlateThickness != null ? src.F_DoorPlateThickness : null)
			.Map(dest => dest.F_BoxPlateThickness, src => src.F_BoxPlateThickness != null ? src.F_BoxPlateThickness : null)
			.Map(dest => dest.F_InstallOrBeam, src => src.F_InstallOrBeam != null ? src.F_InstallOrBeam : null)
			.Map(dest => dest.F_LockSet, src => src.F_LockSet != null ? src.F_LockSet : null)
			.Map(dest => dest.F_Hinge, src => src.F_Hinge != null ? src.F_Hinge : null)
			.Map(dest => dest.F_Color, src => src.F_Color != null ? src.F_Color : null)
			.Map(dest => dest.F_Material, src => src.F_Material != null ? src.F_Material : null)
			.Map(dest => dest.F_F_AuditStatus, src => src.F_F_AuditStatus != null ? src.F_F_AuditStatus : null)
            .Map(dest => dest.F_DrawingFiles, src => src.F_DrawingFiles != null && src.F_DrawingFiles.Count > 0 ? src.F_DrawingFiles.ToJsonString().Replace("\r\n", "").Replace(" ", "") : null)
            .Map(dest => dest.F_Category, src => src.F_Category != null && src.F_Category.Count > 0 ? src.F_Category.ToJsonString().Replace("\r\n", "").Replace(" ", "") : null)
            .Map(dest => dest.F_Files, src => src.F_Files != null && src.F_Files.Count > 0 ? src.F_Files.ToJsonString().Replace("\r\n", "").Replace(" ", "") : null)
			.Map(dest => dest.F_CreatorUserId, src => src.F_CreatorUserId != null ? src.F_CreatorUserId : null)
		;
		config.ForType<ACtcContractItemEntity, ACtcContractItemListOutput>()
			.Map(dest => dest.F_CustomerId, src => src.F_CustomerId != null ? src.F_CustomerId : null)
			.Map(dest => dest.F_Price, src => src.F_Price != null ? src.F_Price : null)
			.Map(dest => dest.F_SaleQty, src => src.F_SaleQty != null ? src.F_SaleQty : null)
			.Map(dest => dest.F_Discount, src => src.F_Discount != null ? src.F_Discount : null)
			.Map(dest => dest.F_Description, src => src.F_Description != null ? src.F_Description : null)
			.Map(dest => dest.F_DoorPlateThickness, src => src.F_DoorPlateThickness != null ? src.F_DoorPlateThickness : null)
			.Map(dest => dest.F_BoxPlateThickness, src => src.F_BoxPlateThickness != null ? src.F_BoxPlateThickness : null)
			.Map(dest => dest.F_InstallOrBeam, src => src.F_InstallOrBeam != null ? src.F_InstallOrBeam : null)
			.Map(dest => dest.F_LockSet, src => src.F_LockSet != null ? src.F_LockSet : null)
			.Map(dest => dest.F_Hinge, src => src.F_Hinge != null ? src.F_Hinge : null)
			.Map(dest => dest.F_Color, src => src.F_Color != null ? src.F_Color : null)
			.Map(dest => dest.F_Material, src => src.F_Material != null ? src.F_Material : null)
			.Map(dest => dest.F_F_AuditStatus, src => src.F_F_AuditStatus != null ? src.F_F_AuditStatus : null)
			.Map(dest => dest.F_Files, src => src.F_Files != null ? src.F_Files : null)
            .Map(dest => dest.F_Category, src => src.F_Category != null ? src.F_Category.ToObject<List<string>>() : null)
            .Map(dest => dest.F_DrawingFiles, src => src.F_DrawingFiles != null ? src.F_DrawingFiles.ToObject<List<FileControlsModel>>() : new List<FileControlsModel>())
            .Map(dest => dest.F_CreatorUserId, src => src.F_CreatorUserId != null ? src.F_CreatorUserId : null)
			.Map(dest => dest.F_CreatorTime, src => src.F_CreatorTime != null ? src.F_CreatorTime : null)
		;
		config.ForType<ACtcContractItemEntity, ACtcContractItemInfoOutput>()
			.Map(dest => dest.F_CustomerId, src => src.F_CustomerId != null ? src.F_CustomerId : null)
			.Map(dest => dest.F_Price, src => src.F_Price != null ? src.F_Price : null)
			.Map(dest => dest.F_SaleQty, src => src.F_SaleQty != null ? src.F_SaleQty : null)
			.Map(dest => dest.F_Discount, src => src.F_Discount != null ? src.F_Discount : null)
			.Map(dest => dest.F_Description, src => src.F_Description != null ? src.F_Description : null)
			.Map(dest => dest.F_DoorPlateThickness, src => src.F_DoorPlateThickness != null ? src.F_DoorPlateThickness : null)
			.Map(dest => dest.F_BoxPlateThickness, src => src.F_BoxPlateThickness != null ? src.F_BoxPlateThickness : null)
			.Map(dest => dest.F_InstallOrBeam, src => src.F_InstallOrBeam != null ? src.F_InstallOrBeam : null)
			.Map(dest => dest.F_LockSet, src => src.F_LockSet != null ? src.F_LockSet : null)
			.Map(dest => dest.F_Hinge, src => src.F_Hinge != null ? src.F_Hinge : null)
			.Map(dest => dest.F_Color, src => src.F_Color != null ? src.F_Color : null)
			.Map(dest => dest.F_Material, src => src.F_Material != null ? src.F_Material : null)
			.Map(dest => dest.F_F_AuditStatus, src => src.F_F_AuditStatus != null ? src.F_F_AuditStatus : null)
            .Map(dest => dest.F_Category, src => src.F_Category != null ? src.F_Category.ToObject<List<string>>() : null)
            .Map(dest => dest.F_DrawingFiles, src => src.F_DrawingFiles != null ? src.F_DrawingFiles.ToObject<List<FileControlsModel>>() : new List<FileControlsModel>())
            .Map(dest => dest.F_Files, src => src.F_Files != null ? src.F_Files.ToObject<List<FileControlsModel>>() : new List<FileControlsModel>())
			.Map(dest => dest.F_CreatorUserId, src => src.F_CreatorUserId != null ? src.F_CreatorUserId : null)
			.Map(dest => dest.F_CreatorTime, src => src.F_CreatorTime != null ? src.F_CreatorTime : null)
		;
		config.ForType<ACtcContractItemEntity, ACtcContractItemDetailOutput>()
			.Map(dest => dest.F_CustomerId, src => src.F_CustomerId != null ? src.F_CustomerId : null)
			.Map(dest => dest.F_Price, src => src.F_Price != null ? src.F_Price : null)
			.Map(dest => dest.F_SaleQty, src => src.F_SaleQty != null ? src.F_SaleQty : null)
			.Map(dest => dest.F_Discount, src => src.F_Discount != null ? src.F_Discount : null)
			.Map(dest => dest.F_Description, src => src.F_Description != null ? src.F_Description : null)
			.Map(dest => dest.F_DoorPlateThickness, src => src.F_DoorPlateThickness != null ? src.F_DoorPlateThickness : null)
			.Map(dest => dest.F_BoxPlateThickness, src => src.F_BoxPlateThickness != null ? src.F_BoxPlateThickness : null)
			.Map(dest => dest.F_InstallOrBeam, src => src.F_InstallOrBeam != null ? src.F_InstallOrBeam : null)
            .Map(dest => dest.F_DrawingFiles, src => src.F_DrawingFiles != null ? src.F_DrawingFiles.ToObject<List<FileControlsModel>>() : new List<FileControlsModel>())
            .Map(dest => dest.F_Category, src => src.F_Category != null ? src.F_Category : null)
            .Map(dest => dest.F_LockSet, src => src.F_LockSet != null ? src.F_LockSet : null)
			.Map(dest => dest.F_Hinge, src => src.F_Hinge != null ? src.F_Hinge : null)
			.Map(dest => dest.F_Color, src => src.F_Color != null ? src.F_Color : null)
			.Map(dest => dest.F_Material, src => src.F_Material != null ? src.F_Material : null)
			.Map(dest => dest.F_F_AuditStatus, src => src.F_F_AuditStatus != null ? src.F_F_AuditStatus : null)
			.Map(dest => dest.F_Files, src => src.F_Files != null ? src.F_Files.ToObject<List<FileControlsModel>>() : new List<FileControlsModel>())
			.Map(dest => dest.F_CreatorUserId, src => src.F_CreatorUserId != null ? src.F_CreatorUserId : null)
			.Map(dest => dest.F_CreatorTime, src => src.F_CreatorTime != null ? src.F_CreatorTime : null)
		;
	}
}
