const searchList = [
  {
    label: '机台编号',
    labelI18nCode: '',
    prop: 'F_MachineCode',
    jnpfKey: 'input',
    searchType: 2,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_MachineCode',
    fullName: '机台编号',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '机台编号',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_machine',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItem1d0d13',
      renderKey: 1768445472015,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请填写，忽略将自动生成',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_MachineCode',
  },
  {
    label: '机台名称',
    labelI18nCode: '',
    prop: 'F_MachineName',
    jnpfKey: 'input',
    searchType: 2,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_MachineName',
    fullName: '机台名称',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '机台名称',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: true,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_machine',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItem753b92',
      renderKey: 1768445473521,
      unique: true,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_MachineName',
  },
  {
    label: '机台类别',
    labelI18nCode: '',
    prop: 'F_MachineType',
    jnpfKey: 'cascader',
    searchType: 1,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_MachineType',
    fullName: '机台类别',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'cascader',
      label: '机台类别',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfCascader',
      tagIcon: 'icon-ym icon-ym-generator-cascader',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: true,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_machine',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dynamic',
      propsUrl: '2011621811959238656',
      propsName: '机台类别',
      useCache: true,
      templateJson: [],
      dictionaryType: '',
      formId: 'formItema706bf',
      renderKey: 1768465466553,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [
      {
        F_Id: '2011712512025825280',
        F_category: '0',
        F_category_id: null,
        F_Name: '机台三',
        F_Tiem: '',
        children: [],
      },
      {
        F_Id: '2011699312031043584',
        F_category: '0',
        F_category_id: null,
        F_Name: '机台二',
        F_Tiem: '',
        children: [
          {
            F_Id: '2011712611116257280',
            F_category: '0',
            F_category_id: '2011699312031043584',
            F_Name: 'JT2',
            F_Tiem: '',
            children: [],
          },
        ],
      },
      {
        F_Id: '2011699271837028352',
        F_category: '0',
        F_category_id: null,
        F_Name: '机台一',
        F_Tiem: '',
        children: [
          {
            F_Id: '2011712558138003456',
            F_category: '0',
            F_category_id: '2011699271837028352',
            F_Name: 'JT1',
            F_Tiem: '',
            children: [
              {
                F_Id: '2011712657480093696',
                F_category: '0',
                F_category_id: '2011712558138003456',
                F_Name: 'JT1-1',
                F_Tiem: '',
                children: [],
              },
            ],
          },
        ],
      },
    ],
    props: {
      value: 'F_Id',
      label: 'F_Name',
      children: 'children',
    },
    placeholder: '请选择',
    disabled: false,
    clearable: true,
    filterable: true,
    multiple: false,
    __vModel__: 'F_MachineType',
  },
  {
    label: '车间',
    labelI18nCode: '',
    prop: 'F_WorkshopId',
    jnpfKey: 'cascader',
    searchType: 1,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_WorkshopId',
    fullName: '车间',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'cascader',
      label: '车间',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfCascader',
      tagIcon: 'icon-ym icon-ym-generator-cascader',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_machine',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dynamic',
      propsUrl: '2011621894347952128',
      propsName: '车间',
      useCache: true,
      templateJson: [],
      dictionaryType: '',
      formId: 'formItem8374dd',
      renderKey: 1768465433364,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [
      {
        F_Id: '2011696825425334272',
        F_category: '0',
        F_category_id: null,
        F_Name: '车间二',
        F_Tiem: '',
        children: [
          {
            F_Id: '2011712346749276160',
            F_category: '0',
            F_category_id: '2011696825425334272',
            F_Name: 'CJ2',
            F_Tiem: '',
            children: [],
          },
        ],
      },
      {
        F_Id: '2011677892978806784',
        F_category: '0',
        F_category_id: null,
        F_Name: '车间一',
        F_Tiem: '',
        children: [
          {
            F_Id: '2011712328319504384',
            F_category: '0',
            F_category_id: '2011677892978806784',
            F_Name: 'CJ1',
            F_Tiem: '',
            children: [
              {
                F_Id: '2011712403548540928',
                F_category: '0',
                F_category_id: '2011712328319504384',
                F_Name: 'CJ1-1',
                F_Tiem: '',
                children: [],
              },
            ],
          },
        ],
      },
    ],
    props: {
      value: 'F_Id',
      label: 'F_Name',
      children: 'children',
    },
    placeholder: '请选择',
    disabled: false,
    clearable: true,
    filterable: true,
    multiple: false,
    __vModel__: 'F_WorkshopId',
  },
  {
    label: '产线',
    labelI18nCode: '',
    prop: 'F_LineId',
    jnpfKey: 'select',
    searchType: 1,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_LineId',
    fullName: '产线',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '产线',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_machine',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dictionary',
      dictionaryType: '2011623836151320576',
      propsUrl: '',
      propsName: '',
      useCache: true,
      templateJson: [],
      formId: 'formItemada655',
      renderKey: 1768445522374,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [
      {
        id: '2011623876534079488',
        fullName: '示例产线',
        enCode: '0',
        sortCode: 0,
      },
    ],
    props: {
      label: 'fullName',
      value: 'enCode',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: false,
    multiple: false,
    __vModel__: 'F_LineId',
  },
  {
    label: '机台状态',
    labelI18nCode: '',
    prop: 'F_MachineStatus',
    jnpfKey: 'select',
    searchType: 1,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_MachineStatus',
    fullName: '机台状态',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '机台状态',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: true,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_machine',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dictionary',
      dictionaryType: '2011620395194650624',
      propsUrl: '',
      propsName: '',
      useCache: true,
      templateJson: [],
      formId: 'formItem8e3617',
      renderKey: 1768445486265,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [
      {
        id: '2011624015319404544',
        fullName: '正常',
        enCode: '0',
        sortCode: 0,
      },
      {
        id: '2011624046621495296',
        fullName: '维修中',
        enCode: '1',
        sortCode: 1,
      },
    ],
    props: {
      label: 'fullName',
      value: 'enCode',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_MachineStatus',
  },
  {
    label: '创建时间',
    labelI18nCode: '',
    prop: 'F_CreatorTime',
    jnpfKey: 'createTime',
    searchType: 3,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_CreatorTime',
    fullName: '创建时间',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'createTime',
      label: '创建时间',
      showLabel: true,
      tag: 'JnpfOpenData',
      tagIcon: 'icon-ym icon-ym-generator-createtime',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      layout: 'colFormItem',
      required: false,
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_machine',
      noShow: true,
      formId: 'formItem5c61fb',
      renderKey: 1768445564283,
    },
    style: {
      width: '100%',
    },
    type: 'currTime',
    readonly: true,
    placeholder: '',
    __vModel__: 'F_CreatorTime',
  },
];
export default searchList;
