const columnList = [
  {
    label: '商品名称',
    labelI18nCode: '',
    prop: 'F_GoodsName',
    fixed: 'left',
    align: 'left',
    jnpfKey: 'text',
    sortable: false,
    width: 200,
    id: 'F_GoodsName',
    fullName: '商品名称',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '商品名称',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'left',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItemName',
      renderKey: 1,
    },
    style: {
      width: '100%',
    },
    placeholder: '',
    disabled: false,
    __vModel__: 'F_GoodsName',
  },
  {
    label: '商品规格',
    labelI18nCode: '',
    prop: 'F_Specification',
    fixed: 'left',
    align: 'left',
    jnpfKey: 'text',
    sortable: false,
    width: 200,
    id: 'F_Specification',
    fullName: '商品规格',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '商品规格',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'left',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItemName',
      renderKey: 1,
    },
    style: {
      width: '100%',
    },
    placeholder: '',
    disabled: false,
    __vModel__: 'F_Specification',
  },
  {
    label: '商品编码',
    labelI18nCode: '',
    prop: 'F_GoodsNo',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'text',
    sortable: false,
    width: 150,
    id: 'F_GoodsNo',
    fullName: '商品编码',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '商品编码',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItemNo',
      renderKey: 2,
    },
    style: {
      width: '100%',
    },
    placeholder: '',
    disabled: false,
    __vModel__: 'F_GoodsNo',
  },
  {
    label: '单位',
    labelI18nCode: '',
    prop: 'F_Unit',
    fixed: 'none',
    align: 'center',
    jnpfKey: 'text',
    sortable: false,
    width: 80,
    id: 'F_Unit',
    fullName: '单位',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '单位',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'center',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItemUnit',
      renderKey: 3,
    },
    style: {
      width: '100%',
    },
    placeholder: '',
    disabled: false,
    __vModel__: 'F_Unit',
  },
  {
    label: '当前库存',
    labelI18nCode: '',
    prop: 'F_CurrentNum',
    fixed: 'none',
    align: 'center',
    jnpfKey: 'inputNumber',
    sortable: false,
    width: 120,
    id: 'F_CurrentNum',
    fullName: '当前库存',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'inputNumber',
      label: '当前库存',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInputNumber',
      tagIcon: 'icon-ym icon-ym-generator-number',
      tableAlign: 'center',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: ['blur', 'change'],
      formId: 'formItemNum',
      renderKey: 4,
    },
    style: {
      width: '100%',
    },
    placeholder: '',
    min: 0,
    controls: false,
    step: 1,
    precision: 2,
    disabled: false,
    __vModel__: 'F_CurrentNum',
  },
  {
    label: '上限阈值',
    labelI18nCode: '',
    prop: 'F_StockUpperLimit',
    fixed: 'none',
    align: 'center',
    jnpfKey: 'inputNumber',
    sortable: false,
    width: 120,
    id: 'F_StockUpperLimit',
    fullName: '上限阈值',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'inputNumber',
      label: '上限阈值',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInputNumber',
      tagIcon: 'icon-ym icon-ym-generator-number',
      tableAlign: 'center',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: ['blur', 'change'],
      formId: 'formItemUpper',
      renderKey: 5,
    },
    style: {
      width: '100%',
    },
    placeholder: '',
    min: 0,
    controls: false,
    step: 1,
    precision: 0,
    disabled: false,
    __vModel__: 'F_StockUpperLimit',
  },
  {
    label: '下限阈值',
    labelI18nCode: '',
    prop: 'F_StockLowerLimit',
    fixed: 'none',
    align: 'center',
    jnpfKey: 'inputNumber',
    sortable: false,
    width: 120,
    id: 'F_StockLowerLimit',
    fullName: '下限阈值',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'inputNumber',
      label: '下限阈值',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInputNumber',
      tagIcon: 'icon-ym icon-ym-generator-number',
      tableAlign: 'center',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: ['blur', 'change'],
      formId: 'formItemLower',
      renderKey: 6,
    },
    style: {
      width: '100%',
    },
    placeholder: '',
    min: 0,
    controls: false,
    step: 1,
    precision: 0,
    disabled: false,
    __vModel__: 'F_StockLowerLimit',
  },
  {
    label: '库存状态',
    labelI18nCode: '',
    prop: 'alertStatus',
    fixed: 'none',
    align: 'center',
    jnpfKey: 'text',
    sortable: false,
    width: 120,
    id: 'alertStatus',
    fullName: '库存状态',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '库存状态',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'center',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItemStatus',
      renderKey: 7,
    },
    style: {
      width: '100%',
    },
    placeholder: '',
    disabled: false,
    __vModel__: 'alertStatus',
  },
  {
    label: '偏离数量',
    labelI18nCode: '',
    prop: 'deviationValue',
    fixed: 'none',
    align: 'center',
    jnpfKey: 'inputNumber',
    sortable: false,
    width: 120,
    id: 'deviationValue',
    fullName: '偏离数量',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'inputNumber',
      label: '偏离数量',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInputNumber',
      tagIcon: 'icon-ym icon-ym-generator-number',
      tableAlign: 'center',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: '',
      noShow: false,
      regList: [],
      trigger: ['blur', 'change'],
      formId: 'formItemDev',
      renderKey: 8,
    },
    style: {
      width: '100%',
    },
    placeholder: '',
    min: 0,
    controls: false,
    step: 1,
    precision: 2,
    disabled: false,
    __vModel__: 'deviationValue',
  },
];
export default columnList;
