const columnList = [
  {
    label: '商品',
    labelI18nCode: '',
    prop: 'F_GoodsId',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'popupSelect',
    sortable: false,
    width: 150,
    id: 'F_GoodsId',
    fullName: '商品',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'popupSelect',
      label: '商品',
      tipLabel: '',
      showLabel: true,
      required: true,
      tag: 'JnpfPopupSelect',
      tagIcon: 'icon-ym icon-ym-generator-popup',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_goods_inventory_qr',
      noShow: false,
      regList: [],
      trigger: 'change',
      transferList: [],
      useCache: true,
      formId: 'formIteme5ccf0',
      renderKey: 1774315664073,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    interfaceId: '2012085692393459712',
    interfaceName: '弹窗获取商品列表（可传合同ID）',
    templateJson: [
      {
        id: 'b6217b',
        field: 'contractId',
        dataType: 'varchar',
        defaultValue: '',
        required: 0,
        fieldName: '合同ID',
        relationField: '',
        sourceType: 1,
      },
    ],
    hasPage: true,
    pageSize: 20,
    extraOptions: [],
    columnOptions: [
      {
        value: 'F_GoodsName',
        label: '商品',
      },
      {
        value: 'F_Specification',
        label: '商品规格',
      },
      {
        value: 'F_InventoryNum',
        label: '库存',
      },
      {
        value: 'F_Remark',
        label: '备注',
      },
    ],
    propsValue: 'id',
    relationField: 'F_GoodsName',
    popupType: 'dialog',
    popupTitle: '选择数据',
    popupWidth: '1000px',
    disabled: false,
    clearable: true,
    __vModel__: 'F_GoodsId',
    interfaceHasPage: 0,
  },
  {
    label: '二维码编号',
    labelI18nCode: '',
    prop: 'F_Code',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'input',
    sortable: false,
    width: 150,
    id: 'F_Code',
    fullName: '二维码编号',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '二维码编号',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: true,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_goods_inventory_qr',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItema5efe0',
      renderKey: 1774315650116,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_Code',
  },
  // {
  //   label: '备注',
  //   labelI18nCode: '',
  //   prop: 'F_Description',
  //   fixed: 'none',
  //   align: 'left',
  //   jnpfKey: 'textarea',
  //   sortable: false,
  //   width: null,
  //   id: 'F_Description',
  //   fullName: '备注',
  //   fullNameI18nCode: [''],
  //   __config__: {
  //     jnpfKey: 'textarea',
  //     label: '备注',
  //     tipLabel: '',
  //     showLabel: true,
  //     tag: 'JnpfTextarea',
  //     tagIcon: 'icon-ym icon-ym-generator-textarea',
  //     tableAlign: 'left',
  //     tableFixed: 'none',
  //     className: [],
  //     required: false,
  //     layout: 'colFormItem',
  //     span: 24,
  //     dragDisabled: false,
  //     visibility: ['pc', 'app'],
  //     tableName: 'a_goods_inventory_qr',
  //     noShow: false,
  //     regList: [],
  //     trigger: 'blur',
  //     formId: 'formItemdf2176',
  //     renderKey: 1774315697744,
  //   },
  //   on: {
  //     change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
  //     blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
  //   },
  //   style: {
  //     width: '100%',
  //   },
  //   placeholder: '请输入',
  //   autoSize: {
  //     minRows: 4,
  //     maxRows: 4,
  //   },
  //   clearable: true,
  //   maxlength: 500,
  //   showCount: false,
  //   readonly: false,
  //   disabled: false,
  //   __vModel__: 'F_Description',
  // },
  {
    label: '创建用户',
    labelI18nCode: '',
    prop: 'F_CreatorUserId',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'createUser',
    sortable: false,
    width: null,
    id: 'F_CreatorUserId',
    fullName: '创建用户',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'createUser',
      label: '创建用户',
      showLabel: true,
      tag: 'JnpfOpenData',
      tagIcon: 'icon-ym icon-ym-generator-founder',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_goods_inventory_qr',
      noShow: true,
      formId: 'formItemd37c8b',
      renderKey: 1774315674226,
    },
    style: {
      width: '100%',
    },
    type: 'currUser',
    readonly: true,
    placeholder: '',
    __vModel__: 'F_CreatorUserId',
  },
  {
    label: '创建时间',
    labelI18nCode: '',
    prop: 'F_CreatorTime',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'createTime',
    sortable: false,
    width: 150,
    id: 'F_CreatorTime',
    fullName: '创建时间',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'createTime',
      label: '创建时间',
      showLabel: true,
      tag: 'JnpfOpenData',
      tagIcon: 'icon-ym icon-ym-generator-createtime',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      layout: 'colFormItem',
      required: false,
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_goods_inventory_qr',
      noShow: true,
      formId: 'formItemf1b5cd',
      renderKey: 1774315675068,
    },
    style: {
      width: '100%',
    },
    type: 'currTime',
    readonly: true,
    placeholder: '',
    __vModel__: 'F_CreatorTime',
  },
];
export default columnList;
