const columnList = [
  {
    label: '计划编号',
    labelI18nCode: '',
    prop: 'F_PlanNo',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'input',
    sortable: false,
    width: 180,
    resizable: true,
    id: 'F_PlanNo',
    fullName: '计划编号',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '计划编号',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_plan',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItemc2ccc5',
      renderKey: 1768911132721,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请填写，忽略将自动生成',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_PlanNo',
  },
  {
    label: '计划名称',
    labelI18nCode: '',
    prop: 'F_PlanName',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'input',
    sortable: false,
    width: 180,
    resizable: true,
    id: 'F_PlanName',
    fullName: '计划名称',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '计划名称',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: true,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_plan',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItem9d8635',
      renderKey: 1768911132993,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_PlanName',
  },
  {
    label: '物料分析状态',
    labelI18nCode: '',
    prop: 'F_State',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'select',
    sortable: false,
    width: null,
    resizable: true,
    id: 'F_State',
    fullName: '物料分析状态',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '物料分析状态',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_plan',
      noShow: true,
      regList: [],
      trigger: 'change',
      dataType: 'static',
      dictionaryType: '',
      propsUrl: '',
      propsName: '',
      useCache: true,
      templateJson: [],
      formId: 'formItemd10ce4',
      renderKey: 1768911140038,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [
      {
        fullName: '已分析',
        id: '1',
      },
      {
        fullName: '未分析',
        id: '0',
      },
    ],
    props: {
      label: 'fullName',
      value: 'id',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: false,
    multiple: false,
    __vModel__: 'F_State',
  },
  {
    label: '交货日期',
    labelI18nCode: '',
    prop: 'F_DeliveryDate',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'datePicker',
    sortable: false,
    width: null,
    resizable: true,
    id: 'F_DeliveryDate',
    fullName: '交货日期',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'datePicker',
      label: '交货日期',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfDatePicker',
      tagIcon: 'icon-ym icon-ym-generator-date',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      defaultCurrent: false,
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_plan',
      noShow: false,
      regList: [],
      trigger: 'change',
      startTimeRule: false,
      startTimeType: 1,
      startTimeTarget: 1,
      startTimeValue: null,
      startRelationField: '',
      endTimeRule: false,
      endTimeType: 1,
      endTimeTarget: 1,
      endTimeValue: null,
      endRelationField: '',
      formId: 'formItema1bdd7',
      renderKey: 1768911134481,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    format: 'yyyy-MM-dd',
    startTime: null,
    endTime: null,
    disabled: false,
    clearable: true,
    __vModel__: 'F_DeliveryDate',
  },
  {
    label: '创建人员',
    labelI18nCode: '',
    prop: 'F_CreatorUserId',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'createUser',
    sortable: false,
    width: null,
    resizable: true,
    id: 'F_CreatorUserId',
    fullName: '创建人员',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'createUser',
      label: '创建人员',
      showLabel: true,
      tag: 'JnpfOpenData',
      tagIcon: 'icon-ym icon-ym-generator-founder',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_plan',
      noShow: true,
      formId: 'formItem98ef91',
      renderKey: 1768911200709,
    },
    style: {
      width: '100%',
    },
    type: 'currUser',
    readonly: true,
    placeholder: '',
    __vModel__: 'F_CreatorUserId',
  },
  {
    label: '创建时间',
    labelI18nCode: '',
    prop: 'F_CreatorTime',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'createTime',
    sortable: false,
    width: 150,
    resizable: true,
    id: 'F_CreatorTime',
    fullName: '创建时间',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'createTime',
      label: '创建时间',
      showLabel: true,
      tag: 'JnpfOpenData',
      tagIcon: 'icon-ym icon-ym-generator-createtime',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      layout: 'colFormItem',
      required: false,
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_plan',
      noShow: true,
      formId: 'formItem213bab',
      renderKey: 1768911141595,
    },
    style: {
      width: '100%',
    },
    type: 'currTime',
    readonly: true,
    placeholder: '',
    __vModel__: 'F_CreatorTime',
  },
];
export default columnList;
