const columnList = [
  {
    label: '生产出库单号',
    labelI18nCode: '',
    prop: 'F_StockOutNo',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'input',
    sortable: false,
    width: 150,
    resizable: true,
    id: 'F_StockOutNo',
    fullName: '生产出库单号',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '生产出库单号',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_pu_out_stock_prod',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItem9f95ca',
      renderKey: 1769072966002,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请填写，忽略将自动生成',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_StockOutNo',
  },
  // {
  //   label: '仓库',
  //   labelI18nCode: '',
  //   prop: 'F_WarehouseId',
  //   fixed: 'none',
  //   align: 'left',
  //   jnpfKey: 'cascader',
  //   sortable: false,
  //   width: null,
  //   id: 'F_WarehouseId',
  //   fullName: '仓库',
  //   fullNameI18nCode: [''],
  //   __config__: {
  //     jnpfKey: 'cascader',
  //     label: '仓库',
  //     tipLabel: '',
  //     showLabel: true,
  //     tag: 'JnpfCascader',
  //     tagIcon: 'icon-ym icon-ym-generator-cascader',
  //     tableAlign: 'left',
  //     tableFixed: 'none',
  //     className: [],
  //     defaultValue: [],
  //     required: true,
  //     layout: 'colFormItem',
  //     span: 8,
  //     dragDisabled: false,
  //     visibility: ['pc', 'app'],
  //     tableName: 'a_pu_out_stock_prod',
  //     noShow: false,
  //     regList: [],
  //     trigger: 'change',
  //     dataType: 'dynamic',
  //     propsUrl: '2021045201115680768',
  //     propsName: '仓库管理（树状）',
  //     useCache: true,
  //     templateJson: [],
  //     dictionaryType: '',
  //     formId: 'formItem274c6f',
  //     renderKey: 1772441484499,
  //   },
  //   on: {
  //     change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
  //     blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
  //   },
  //   style: {
  //     width: '100%',
  //   },
  //   options: [],
  //   props: {
  //     value: 'F_Id',
  //     label: 'F_Name',
  //     children: 'children',
  //   },
  //   placeholder: '请选择',
  //   disabled: false,
  //   clearable: true,
  //   filterable: true,
  //   multiple: false,
  //   __vModel__: 'F_WarehouseId',
  // },
  {
    label: '出库类型',
    labelI18nCode: '',
    prop: 'F_StockOutType',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'select',
    sortable: false,
    width: null,
    resizable: true,
    id: 'F_StockOutType',
    fullName: '出库类型',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '出库类型',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_pu_out_stock_prod',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dictionary',
      dictionaryType: '2013096194263355392',
      propsUrl: '',
      propsName: '',
      useCache: true,
      templateJson: [],
      formId: 'formItemcf8a23',
      renderKey: 1769073062260,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [],
    props: {
      label: 'fullName',
      value: 'enCode',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: false,
    multiple: false,
    __vModel__: 'F_StockOutType',
  },
  {
    label: '出库日期',
    labelI18nCode: '',
    prop: 'F_StockOutDate',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'datePicker',
    sortable: false,
    width: null,
    resizable: true,
    id: 'F_StockOutDate',
    fullName: '出库日期',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'datePicker',
      label: '出库日期',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfDatePicker',
      tagIcon: 'icon-ym icon-ym-generator-date',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      defaultCurrent: false,
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_pu_out_stock_prod',
      noShow: false,
      regList: [],
      trigger: 'change',
      startTimeRule: false,
      startTimeType: 1,
      startTimeTarget: 1,
      startTimeValue: null,
      startRelationField: '',
      endTimeRule: false,
      endTimeType: 1,
      endTimeTarget: 1,
      endTimeValue: null,
      endRelationField: '',
      formId: 'formItem85caca',
      renderKey: 1769073092719,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    format: 'yyyy-MM-dd',
    startTime: null,
    endTime: null,
    disabled: false,
    clearable: true,
    __vModel__: 'F_StockOutDate',
  },
  {
    label: '工单',
    labelI18nCode: '',
    prop: 'F_WorkOrderId',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'select',
    sortable: false,
    width: 150,
    resizable: true,
    id: 'F_WorkOrderId',
    fullName: '工单',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '工单',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_pu_out_stock_prod',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'static',
      dictionaryType: '',
      propsUrl: '',
      propsName: '',
      useCache: true,
      templateJson: [],
      formId: 'formItemb48fcd',
      renderKey: 1769073119865,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [
      {
        fullName: '选项一',
        id: '1',
      },
      {
        fullName: '选项二',
        id: '2',
      },
    ],
    props: {
      label: 'fullName',
      value: 'id',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: false,
    multiple: false,
    __vModel__: 'F_WorkOrderId',
  },
  {
    label: '出库套数',
    labelI18nCode: '',
    prop: 'F_Num',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'inputNumber',
    sortable: false,
    width: null,
    resizable: true,
    id: 'F_Num',
    fullName: '出库套数',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'inputNumber',
      label: '出库套数',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInputNumber',
      tagIcon: 'icon-ym icon-ym-generator-number',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_pu_out_stock_prod',
      noShow: false,
      regList: [],
      trigger: ['blur', 'change'],
      formId: 'formItem96a20f',
      renderKey: 1769073151333,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    controls: false,
    addonBefore: '',
    addonAfter: '',
    thousands: false,
    isAmountChinese: false,
    step: 1,
    precision: 0,
    disabled: false,
    __vModel__: 'F_Num',
  },
  {
    label: '工单类型',
    labelI18nCode: '',
    prop: 'F_Type',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'select',
    sortable: false,
    width: null,
    resizable: true,
    id: 'F_Type',
    fullName: '工单类型',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '工单类型',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_prod_processing',
      noShow: true,
      regList: [],
      trigger: 'change',
      dataType: 'dictionary',
      dictionaryType: '2013819135649255424',
      propsUrl: '',
      propsName: '',
      useCache: true,
      templateJson: [],
      formId: 'formItem19f927',
      renderKey: 1768967117997,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [],
    props: {
      label: 'fullName',
      value: 'enCode',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_Type',
  },

  // {
  //   label: '操作方式',
  //   labelI18nCode: '',
  //   prop: 'F_Method',
  //   fixed: 'none',
  //   align: 'left',
  //   jnpfKey: 'select',
  //   sortable: false,
  //   width: null,
  //   resizable: true,
  //   id: 'F_Method',
  //   fullName: '操作方式',
  //   fullNameI18nCode: [''],
  //   __config__: {
  //     jnpfKey: 'select',
  //     label: '操作方式',
  //     tipLabel: '',
  //     showLabel: true,
  //     tag: 'JnpfSelect',
  //     tagIcon: 'icon-ym icon-ym-generator-select',
  //     tableAlign: 'left',
  //     tableFixed: 'none',
  //     className: [],
  //     defaultValue: '',
  //     required: false,
  //     layout: 'colFormItem',
  //     span: 12,
  //     dragDisabled: false,
  //     visibility: ['pc', 'app'],
  //     tableName: 'a_prod_processing',
  //     noShow: true,
  //     regList: [],
  //     trigger: 'change',
  //     dataType: 'dictionary',
  //     dictionaryType: '2013819135649255424',
  //     propsUrl: '',
  //     propsName: '',
  //     useCache: true,
  //     templateJson: [],
  //     formId: 'formItem19f927',
  //     renderKey: 1768967117997,
  //   },
  //   on: {
  //     change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
  //   },
  //   style: {
  //     width: '100%',
  //   },
  //   options: [],
  //   props: {
  //     label: 'fullName',
  //     value: 'enCode',
  //   },
  //   placeholder: '请选择',
  //   clearable: true,
  //   disabled: false,
  //   filterable: true,
  //   multiple: false,
  //   __vModel__: 'F_Method',
  // },
  {
    label: '备注',
    labelI18nCode: '',
    prop: 'F_Description',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'textarea',
    sortable: false,
    width: null,
    resizable: true,
    id: 'F_Description',
    fullName: '备注',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'textarea',
      label: '备注',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfTextarea',
      tagIcon: 'icon-ym icon-ym-generator-textarea',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_pu_out_stock_prod',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItema70b90',
      renderKey: 1769073195167,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    autoSize: {
      minRows: 2,
      maxRows: 4,
    },
    clearable: true,
    maxlength: null,
    showCount: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_Description',
  },
  {
    label: '创建人员',
    labelI18nCode: '',
    prop: 'F_CreatorUserId',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'createUser',
    sortable: false,
    width: null,
    resizable: true,
    id: 'F_CreatorUserId',
    fullName: '创建人员',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'createUser',
      label: '创建人员',
      showLabel: true,
      tag: 'JnpfOpenData',
      tagIcon: 'icon-ym icon-ym-generator-founder',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_pu_out_stock_prod',
      noShow: false,
      formId: 'formItemf9049f',
      renderKey: 1769073211265,
    },
    style: {
      width: '100%',
    },
    type: 'currUser',
    readonly: true,
    placeholder: '',
    __vModel__: 'F_CreatorUserId',
  },
  {
    label: '创建时间',
    labelI18nCode: '',
    prop: 'F_CreatorTime',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'createTime',
    sortable: false,
    width: 150,
    resizable: true,
    id: 'F_CreatorTime',
    fullName: '创建时间',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'createTime',
      label: '创建时间',
      showLabel: true,
      tag: 'JnpfOpenData',
      tagIcon: 'icon-ym icon-ym-generator-createtime',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      layout: 'colFormItem',
      required: false,
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_pu_out_stock_prod',
      noShow: false,
      formId: 'formItem666a86',
      renderKey: 1769073219620,
    },
    style: {
      width: '100%',
    },
    type: 'currTime',
    readonly: true,
    placeholder: '',
    __vModel__: 'F_CreatorTime',
  },
];
export default columnList;
