const columnList = [
  {
    label: '报价单号',
    labelI18nCode: '',
    prop: 'F_QuoteCode',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'input',
    sortable: false,
    width: null,
    id: 'F_QuoteCode',
    fullName: '报价单号',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '报价单号',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_ctc_quote',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItem02db77',
      renderKey: 1767929725110,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_QuoteCode',
  },
  {
    label: '客户',
    labelI18nCode: '',
    prop: 'F_CustomerId',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'select',
    sortable: false,
    width: null,
    id: 'F_CustomerId',
    fullName: '客户',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '客户',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: true,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_ctc_quote',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dynamic',
      dictionaryType: '',
      propsUrl: '2009458830353764352',
      propsName: '客户',
      useCache: true,
      templateJson: [],
      formId: 'formItemacc980',
      renderKey: 1767940880220,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [],
    props: {
      label: 'F_CustomerName',
      value: 'F_Id',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: false,
    multiple: false,
    __vModel__: 'F_CustomerId',
  },
  {
    label: '联系人',
    labelI18nCode: '',
    prop: 'F_ContactId',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'popupSelect',
    sortable: false,
    width: null,
    id: 'F_ContactId',
    fullName: '联系人',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'popupSelect',
      label: '联系人',
      tipLabel: '',
      showLabel: true,
      required: false,
      tag: 'JnpfPopupSelect',
      tagIcon: 'icon-ym icon-ym-generator-popup',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_ctc_quote',
      noShow: false,
      regList: [],
      trigger: 'change',
      transferList: [],
      useCache: true,
      formId: 'formItem05a9d2',
      renderKey: 1767941040448,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    interfaceId: '2009459664370143232',
    interfaceName: '联系人',
    templateJson: [
      {
        id: '781a4a',
        field: 'Id',
        dataType: 'varchar',
        defaultValue: '',
        required: 0,
        fieldName: '',
        relationField: '2009181616060108800',
        sourceType: 2,
      },
    ],
    hasPage: false,
    pageSize: 20,
    extraOptions: [],
    columnOptions: [
      {
        value: 'F_ContactName',
        label: '姓名',
      },
      {
        value: 'F_ContactPhone',
        label: '电话',
      },
    ],
    propsValue: 'id',
    relationField: 'fullName',
    popupType: 'dialog',
    popupTitle: '选择数据',
    popupWidth: '800px',
    disabled: false,
    clearable: true,
    __vModel__: 'F_ContactId',
    interfaceHasPage: 0,
  },
  // {
  //   label: '客户地址',
  //   labelI18nCode: '',
  //   prop: 'F_AddressId',
  //   fixed: 'none',
  //   align: 'left',
  //   jnpfKey: 'select',
  //   sortable: false,
  //   width: null,
  //   id: 'F_AddressId',
  //   fullName: '客户地址ID',
  //   fullNameI18nCode: [''],
  //   __config__: {
  //     jnpfKey: 'select',
  //     label: '客户地址ID',
  //     tipLabel: '',
  //     showLabel: true,
  //     tag: 'JnpfSelect',
  //     tagIcon: 'icon-ym icon-ym-generator-select',
  //     tableAlign: 'left',
  //     tableFixed: 'none',
  //     className: [],
  //     defaultValue: '',
  //     required: false,
  //     layout: 'colFormItem',
  //     span: 8,
  //     dragDisabled: false,
  //     visibility: ['pc', 'app'],
  //     tableName: 'a_ctc_quote',
  //     noShow: false,
  //     regList: [],
  //     trigger: 'change',
  //     dataType: 'dynamic',
  //     dictionaryType: '',
  //     propsUrl: '2009527238009163776',
  //     propsName: '客户地址',
  //     useCache: true,
  //     templateJson: [
  //       {
  //         id: 'b9f99c',
  //         field: 'id',
  //         dataType: 'varchar',
  //         defaultValue: '',
  //         required: 0,
  //         fieldName: '',
  //         relationField: '2009181616060108800',
  //         sourceType: 2,
  //       },
  //     ],
  //     formId: 'formItemb33ab9',
  //     renderKey: 1767941646807,
  //   },
  //   on: {
  //     change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
  //   },
  //   style: {
  //     width: '100%',
  //   },
  //   options: [],
  //   props: {
  //     label: 'F_Address',
  //     value: 'F_Id',
  //   },
  //   placeholder: '请选择',
  //   clearable: true,
  //   disabled: false,
  //   filterable: false,
  //   multiple: false,
  //   __vModel__: 'F_AddressId',
  // },
  {
    label: '报价金额',
    labelI18nCode: '',
    prop: 'F_QuoteAmount',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'inputNumber',
    sortable: false,
    width: null,
    id: 'F_QuoteAmount',
    fullName: '报价金额',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'inputNumber',
      label: '报价金额',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInputNumber',
      tagIcon: 'icon-ym icon-ym-generator-number',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_ctc_quote',
      noShow: false,
      regList: [],
      trigger: ['blur', 'change'],
      formId: 'formItema290aa',
      renderKey: 1767941719944,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    controls: false,
    addonBefore: '',
    addonAfter: '',
    thousands: false,
    isAmountChinese: false,
    step: 1,
    disabled: false,
    __vModel__: 'F_QuoteAmount',
  },
  {
    label: '商品总数',
    labelI18nCode: '',
    prop: 'F_GoodsTotal',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'inputNumber',
    sortable: false,
    width: null,
    id: 'F_GoodsTotal',
    fullName: '商品总数',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'inputNumber',
      label: '商品总数',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInputNumber',
      tagIcon: 'icon-ym icon-ym-generator-number',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_ctc_quote',
      noShow: false,
      regList: [],
      trigger: ['blur', 'change'],
      formId: 'formItem7bd32b',
      renderKey: 1767941735822,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    min: 0,
    controls: false,
    addonBefore: '',
    addonAfter: '',
    thousands: false,
    isAmountChinese: false,
    step: 1,
    precision: 1,
    disabled: false,
    __vModel__: 'F_GoodsTotal',
  },
  {
    label: '交货日期',
    labelI18nCode: '',
    prop: 'F_DeliveryDate',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'datePicker',
    sortable: false,
    width: null,
    id: 'F_DeliveryDate',
    fullName: '交货日期',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'datePicker',
      label: '交货日期',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfDatePicker',
      tagIcon: 'icon-ym icon-ym-generator-date',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      defaultCurrent: false,
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_ctc_quote',
      noShow: false,
      regList: [],
      trigger: 'change',
      startTimeRule: false,
      startTimeType: 1,
      startTimeTarget: 1,
      startTimeValue: null,
      startRelationField: '',
      endTimeRule: false,
      endTimeType: 1,
      endTimeTarget: 1,
      endTimeValue: null,
      endRelationField: '',
      formId: 'formItemd29e1b',
      renderKey: 1767941773631,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    format: 'yyyy-MM-dd',
    startTime: null,
    endTime: null,
    disabled: false,
    clearable: true,
    __vModel__: 'F_DeliveryDate',
  },
  {
    label: '报价日期',
    labelI18nCode: '',
    prop: 'F_QuoteDate',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'datePicker',
    sortable: false,
    width: null,
    id: 'F_QuoteDate',
    fullName: '报价日期',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'datePicker',
      label: '报价日期',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfDatePicker',
      tagIcon: 'icon-ym icon-ym-generator-date',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: null,
      defaultCurrent: false,
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_ctc_quote',
      noShow: false,
      regList: [],
      trigger: 'change',
      startTimeRule: false,
      startTimeType: 1,
      startTimeTarget: 1,
      startTimeValue: null,
      startRelationField: '',
      endTimeRule: false,
      endTimeType: 1,
      endTimeTarget: 1,
      endTimeValue: null,
      endRelationField: '',
      formId: 'formItem3fa825',
      renderKey: 1767941799467,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    format: 'yyyy-MM-dd',
    startTime: null,
    endTime: null,
    disabled: false,
    clearable: true,
    __vModel__: 'F_QuoteDate',
  },
  {
    label: '业务员',
    labelI18nCode: '',
    prop: 'F_SalesmanId',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'userSelect',
    sortable: false,
    width: null,
    id: 'F_SalesmanId',
    fullName: '业务员',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'userSelect',
      label: '业务员',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfUserSelect',
      tagIcon: 'icon-ym icon-ym-generator-user',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      defaultCurrent: true,
      required: true,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_ctc_quote',
      noShow: false,
      regList: [],
      trigger: 'change',
      formId: 'formItem3abff8',
      renderKey: 1767941826982,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    selectType: 'all',
    ableIds: [],
    ableRelationIds: [],
    relationField: '',
    multiple: false,
    clearable: true,
    disabled: false,
    __vModel__: 'F_SalesmanId',
  },
  {
    label: '报价状态',
    labelI18nCode: '',
    prop: 'F_QuoteStatus',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'select',
    sortable: false,
    width: null,
    id: 'F_QuoteStatus',
    fullName: '报价状态',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '报价状态',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_ctc_quote',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dictionary',
      dictionaryType: '2028350323948654592',
      propsUrl: '',
      propsName: '',
      useCache: true,
      templateJson: [],
      formId: 'formItemf9297d',
      renderKey: 1772431503164,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [],
    props: {
      label: 'fullName',
      value: 'enCode',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_QuoteStatus',
  },
  // {
  //   "label": "审核状态",
  //   "labelI18nCode": "",
  //   "prop": "F_AuditStatus",
  //   "fixed": "none",
  //   "align": "left",
  //   "jnpfKey": "input",
  //   "sortable": false,
  //   "width": null,
  //   "id": "F_AuditStatus",
  //   "fullName": "审核状态",
  //   "fullNameI18nCode": [
  //     ""
  //   ],
  //   "__config__": {
  //     "jnpfKey": "input",
  //     "label": "审核状态",
  //     "tipLabel": "",
  //     "showLabel": true,
  //     "tag": "JnpfInput",
  //     "tagIcon": "icon-ym icon-ym-generator-input",
  //     "tableAlign": "left",
  //     "tableFixed": "none",
  //     "className": [],
  //     "required": false,
  //     "layout": "colFormItem",
  //     "span": 12,
  //     "dragDisabled": false,
  //     "visibility": [
  //       "pc",
  //       "app"
  //     ],
  //     "tableName": "a_ctc_quote",
  //     "noShow": false,
  //     "regList": [],
  //     "trigger": "blur",
  //     "formId": "formItemedd293",
  //     "renderKey": 1767941879498
  //   },
  //   "on": {
  //     "change": "({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}",
  //     "blur": "({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}"
  //   },
  //   "style": {
  //     "width": "100%"
  //   },
  //   "placeholder": "请输入",
  //   "useScan": false,
  //   "useMask": false,
  //   "maskConfig": {
  //     "filler": "*",
  //     "maskType": 1,
  //     "prefixType": 1,
  //     "prefixLimit": 0,
  //     "prefixSpecifyChar": "",
  //     "suffixType": 1,
  //     "suffixLimit": 0,
  //     "suffixSpecifyChar": "",
  //     "ignoreChar": "",
  //     "useUnrealMask": false,
  //     "unrealMaskLength": 1
  //   },
  //   "clearable": true,
  //   "addonBefore": "",
  //   "addonAfter": "",
  //   "prefixIcon": "",
  //   "suffixIcon": "",
  //   "maxlength": null,
  //   "showCount": false,
  //   "showPassword": false,
  //   "readonly": false,
  //   "disabled": false,
  //   "__vModel__": "F_AuditStatus"
  // },
  {
    label: '选择报价单商品-商品ID',
    labelI18nCode: '',
    prop: 'tableFielddc29f7-F_CustomerId',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'popupSelect',
    sortable: false,
    width: null,
    id: 'tableFielddc29f7-F_CustomerId',
    fullName: '选择报价单商品-商品ID',
    fullNameI18nCode: ['', ''],
    __config__: {
      jnpfKey: 'popupSelect',
      label: '商品ID',
      tipLabel: '',
      showLabel: true,
      required: false,
      tag: 'JnpfPopupSelect',
      tagIcon: 'icon-ym icon-ym-generator-popup',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_ctc_quote',
      noShow: false,
      regList: [],
      trigger: 'change',
      transferList: [],
      useCache: true,
      formId: 'formItema4547a',
      renderKey: 1767942138454,
      isSubTable: true,
      parentVModel: 'tableFielddc29f7',
      relationTable: 'a_ctc_quote_item',
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    interfaceId: '2008721559174385664',
    interfaceName: '商品',
    templateJson: [],
    hasPage: true,
    pageSize: 20,
    extraOptions: [],
    columnOptions: [
      {
        value: 'F_GoodsNo',
        label: '编号',
      },
      {
        value: 'F_GoodsName',
        label: '商品名称',
      },
      {
        value: 'F_Unit',
        label: '单位',
      },
      {
        value: 'F_Specification',
        label: '规则',
      },
      {
        value: 'F_SalePrice',
        label: '销售单价',
      },
      {
        value: 'F_CostPrice',
        label: '成本单价',
      },
    ],
    propsValue: 'id',
    relationField: 'fullName',
    popupType: 'dialog',
    popupTitle: '选择数据',
    popupWidth: '60%',
    disabled: false,
    clearable: true,
    __vModel__: 'F_CustomerId',
    interfaceHasPage: 0,
  },
  {
    label: '选择报价单商品-单价',
    labelI18nCode: '',
    prop: 'tableFielddc29f7-F_Price',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'inputNumber',
    sortable: false,
    width: null,
    id: 'tableFielddc29f7-F_Price',
    fullName: '选择报价单商品-单价',
    fullNameI18nCode: ['', ''],
    __config__: {
      jnpfKey: 'inputNumber',
      label: '单价',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInputNumber',
      tagIcon: 'icon-ym icon-ym-generator-number',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_ctc_quote',
      noShow: false,
      regList: [],
      trigger: ['blur', 'change'],
      formId: 'formItemcc7fbe',
      renderKey: 1767943025120,
      isSubTable: true,
      parentVModel: 'tableFielddc29f7',
      relationTable: 'a_ctc_quote_item',
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    controls: false,
    addonBefore: '',
    addonAfter: '',
    thousands: false,
    isAmountChinese: false,
    step: 1,
    disabled: false,
    __vModel__: 'F_Price',
  },
  {
    label: '选择报价单商品-销售数量',
    labelI18nCode: '',
    prop: 'tableFielddc29f7-F_SaleQty',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'inputNumber',
    sortable: false,
    width: null,
    id: 'tableFielddc29f7-F_SaleQty',
    fullName: '选择报价单商品-销售数量',
    fullNameI18nCode: ['', ''],
    __config__: {
      jnpfKey: 'inputNumber',
      label: '销售数量',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInputNumber',
      tagIcon: 'icon-ym icon-ym-generator-number',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_ctc_quote',
      noShow: false,
      regList: [],
      trigger: ['blur', 'change'],
      formId: 'formItem9c9c1c',
      renderKey: 1767943037244,
      isSubTable: true,
      parentVModel: 'tableFielddc29f7',
      relationTable: 'a_ctc_quote_item',
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    controls: false,
    addonBefore: '',
    addonAfter: '',
    thousands: false,
    isAmountChinese: false,
    step: 1,
    disabled: false,
    __vModel__: 'F_SaleQty',
  },
  {
    label: '选择报价单商品-折扣',
    labelI18nCode: '',
    prop: 'tableFielddc29f7-F_Discount',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'inputNumber',
    sortable: false,
    width: null,
    id: 'tableFielddc29f7-F_Discount',
    fullName: '选择报价单商品-折扣',
    fullNameI18nCode: ['', ''],
    __config__: {
      jnpfKey: 'inputNumber',
      label: '折扣',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInputNumber',
      tagIcon: 'icon-ym icon-ym-generator-number',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_ctc_quote',
      noShow: false,
      regList: [],
      trigger: ['blur', 'change'],
      formId: 'formItemb4c196',
      renderKey: 1767943058688,
      isSubTable: true,
      parentVModel: 'tableFielddc29f7',
      relationTable: 'a_ctc_quote_item',
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    controls: false,
    addonBefore: '',
    addonAfter: '',
    thousands: false,
    isAmountChinese: false,
    step: 1,
    disabled: false,
    __vModel__: 'F_Discount',
  },
  {
    label: '选择报价单商品-优惠金额',
    labelI18nCode: '',
    prop: 'tableFielddc29f7-F_DiscountAmount',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'inputNumber',
    sortable: false,
    width: null,
    id: 'tableFielddc29f7-F_DiscountAmount',
    fullName: '选择报价单商品-优惠金额',
    fullNameI18nCode: ['', ''],
    __config__: {
      jnpfKey: 'inputNumber',
      label: '优惠金额',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInputNumber',
      tagIcon: 'icon-ym icon-ym-generator-number',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_ctc_quote',
      noShow: false,
      regList: [],
      trigger: ['blur', 'change'],
      formId: 'formItem6ae341',
      renderKey: 1767943206040,
      isSubTable: true,
      parentVModel: 'tableFielddc29f7',
      relationTable: 'a_ctc_quote_item',
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    controls: false,
    addonBefore: '',
    addonAfter: '',
    thousands: false,
    isAmountChinese: false,
    step: 1,
    disabled: false,
    __vModel__: 'F_DiscountAmount',
  },
  {
    label: '选择报价单商品-商品备注',
    labelI18nCode: '',
    prop: 'tableFielddc29f7-F_Description',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'input',
    sortable: false,
    width: null,
    id: 'tableFielddc29f7-F_Description',
    fullName: '选择报价单商品-商品备注',
    fullNameI18nCode: ['', ''],
    __config__: {
      jnpfKey: 'input',
      label: '商品备注',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_ctc_quote',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItem8ae934',
      renderKey: 1767943094410,
      isSubTable: true,
      parentVModel: 'tableFielddc29f7',
      relationTable: 'a_ctc_quote_item',
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_Description',
  },
  {
    label: '选择报价单商品-附件',
    labelI18nCode: '',
    prop: 'tableFielddc29f7-F_Files',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'uploadFile',
    sortable: false,
    width: null,
    id: 'tableFielddc29f7-F_Files',
    fullName: '选择报价单商品-附件',
    fullNameI18nCode: ['', ''],
    __config__: {
      jnpfKey: 'uploadFile',
      label: '附件',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfUploadFile',
      tagIcon: 'icon-ym icon-ym-generator-upload',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: [],
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_ctc_quote',
      noShow: false,
      regList: [],
      trigger: 'change',
      formId: 'formItem3ecaed',
      renderKey: 1767943216448,
      isSubTable: true,
      parentVModel: 'tableFielddc29f7',
      relationTable: 'a_ctc_quote_item',
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    disabled: false,
    accept: '',
    fileSize: 10,
    sizeUnit: 'MB',
    buttonText: '点击上传',
    limit: 9,
    pathType: 'defaultPath',
    sortRule: [],
    timeFormat: 'YYYY',
    folder: '',
    tipText: '',
    __vModel__: 'F_Files',
  },
  {
    label: '选择报价单商品-创建人员',
    labelI18nCode: '',
    prop: 'tableFielddc29f7-F_CreatorUserId',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'createUser',
    sortable: false,
    width: null,
    id: 'tableFielddc29f7-F_CreatorUserId',
    fullName: '选择报价单商品-创建人员',
    fullNameI18nCode: ['', ''],
    __config__: {
      jnpfKey: 'createUser',
      label: '创建人员',
      showLabel: true,
      tag: 'JnpfOpenData',
      tagIcon: 'icon-ym icon-ym-generator-founder',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_ctc_quote',
      noShow: false,
      isSubTable: true,
      parentVModel: 'tableFielddc29f7',
      relationTable: 'a_ctc_quote_item',
      formId: 'formItem76f380',
      renderKey: 1767943238413,
    },
    style: {
      width: '100%',
    },
    type: 'currUser',
    readonly: true,
    placeholder: '',
    __vModel__: 'F_CreatorUserId',
  },
  {
    label: '选择报价单商品-创建时间',
    labelI18nCode: '',
    prop: 'tableFielddc29f7-F_CreatorTime',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'createTime',
    sortable: false,
    width: null,
    id: 'tableFielddc29f7-F_CreatorTime',
    fullName: '选择报价单商品-创建时间',
    fullNameI18nCode: ['', ''],
    __config__: {
      jnpfKey: 'createTime',
      label: '创建时间',
      showLabel: true,
      tag: 'JnpfOpenData',
      tagIcon: 'icon-ym icon-ym-generator-createtime',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      layout: 'colFormItem',
      required: false,
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_ctc_quote',
      noShow: false,
      isSubTable: true,
      parentVModel: 'tableFielddc29f7',
      relationTable: 'a_ctc_quote_item',
      formId: 'formIteme65ee6',
      renderKey: 1767943243292,
    },
    style: {
      width: '100%',
    },
    type: 'currTime',
    readonly: true,
    placeholder: '',
    __vModel__: 'F_CreatorTime',
  },
  {
    label: '创建人员',
    labelI18nCode: '',
    prop: 'F_CreatorUserId',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'createUser',
    sortable: false,
    width: null,
    id: 'F_CreatorUserId',
    fullName: '创建人员',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'createUser',
      label: '创建人员',
      showLabel: true,
      tag: 'JnpfOpenData',
      tagIcon: 'icon-ym icon-ym-generator-founder',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_ctc_quote',
      noShow: false,
      formId: 'formItem7919d8',
      renderKey: 1767941912836,
    },
    style: {
      width: '100%',
    },
    type: 'currUser',
    readonly: true,
    placeholder: '',
    __vModel__: 'F_CreatorUserId',
  },
  {
    label: '创建时间',
    labelI18nCode: '',
    prop: 'F_CreatorTime',
    fixed: 'none',
    align: 'left',
    jnpfKey: 'createTime',
    sortable: false,
    width: null,
    id: 'F_CreatorTime',
    fullName: '创建时间',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'createTime',
      label: '创建时间',
      showLabel: true,
      tag: 'JnpfOpenData',
      tagIcon: 'icon-ym icon-ym-generator-createtime',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      layout: 'colFormItem',
      required: false,
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_ctc_quote',
      noShow: false,
      formId: 'formItema265b9',
      renderKey: 1767941913863,
    },
    style: {
      width: '100%',
    },
    type: 'currTime',
    readonly: true,
    placeholder: '',
    __vModel__: 'F_CreatorTime',
  },
];
export default columnList;
