const searchList = [
  {
    label: '报价单号',
    labelI18nCode: '',
    prop: 'F_QuoteCode',
    jnpfKey: 'input',
    searchType: 2,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_QuoteCode',
    fullName: '报价单号',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'input',
      label: '报价单号',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_ctc_quote',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 'formItem02db77',
      renderKey: 1767929725110,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'F_QuoteCode',
  },
  {
    label: '客户',
    labelI18nCode: '',
    prop: 'F_CustomerId',
    jnpfKey: 'select',
    searchType: 1,
    searchMultiple: true,
    isKeyword: false,
    id: 'F_CustomerId',
    fullName: '客户',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '客户',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: true,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_ctc_quote',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dynamic',
      dictionaryType: '',
      propsUrl: '2009458830353764352',
      propsName: '客户',
      useCache: true,
      templateJson: [],
      formId: 'formItemacc980',
      renderKey: 1767940880220,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [],
    props: {
      label: 'F_CustomerName',
      value: 'F_Id',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: false,
    multiple: false,
    __vModel__: 'F_CustomerId',
  },
  {
    label: '业务员',
    labelI18nCode: '',
    prop: 'F_SalesmanId',
    jnpfKey: 'userSelect',
    searchType: 1,
    searchMultiple: true,
    isKeyword: false,
    id: 'F_SalesmanId',
    fullName: '业务员',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'userSelect',
      label: '业务员',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfUserSelect',
      tagIcon: 'icon-ym icon-ym-generator-user',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      defaultCurrent: true,
      required: true,
      layout: 'colFormItem',
      span: 8,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_ctc_quote',
      noShow: false,
      regList: [],
      trigger: 'change',
      formId: 'formItem3abff8',
      renderKey: 1767941826982,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请选择',
    selectType: 'all',
    ableIds: [],
    ableRelationIds: [],
    relationField: '',
    multiple: false,
    clearable: true,
    disabled: false,
    __vModel__: 'F_SalesmanId',
  },
  {
    label: '报价状态',
    labelI18nCode: '',
    prop: 'F_QuoteStatus',
    jnpfKey: 'select',
    searchType: 1,
    searchMultiple: false,
    isKeyword: false,
    id: 'F_QuoteStatus',
    fullName: '报价状态',
    fullNameI18nCode: [''],
    __config__: {
      jnpfKey: 'select',
      label: '报价状态',
      tipLabel: '',
      showLabel: true,
      tag: 'JnpfSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 12,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'a_ctc_quote',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'dictionary',
      dictionaryType: '2028350323948654592',
      propsUrl: '',
      propsName: '',
      useCache: true,
      templateJson: [],
      formId: 'formItemf9297d',
      renderKey: 1772431503164,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [],
    props: {
      label: 'fullName',
      value: 'enCode',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: true,
    multiple: false,
    __vModel__: 'F_QuoteStatus',
  },
];
export default searchList;
